using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NeoErp.Core.Quotation
{
    public class CustomerModels
    {
        //public CustomerModels()
        //{
        //    ownerInfo = new List<OwnerModels>();
        //    customerInvoiceWiseOpening = new List<CustomerInvoiceWiseOpeningSetup>();
        //    customerDivision = new List<CustomerDivisionModels>();
        //    customerInfoList = new List<CustomerInfo>();
        //    alternativeLocationInfoList = new List<AlternativeLocationInfo>();
        //    budgetCenterList = new List<CustomerBudgetCenter>();
        //    sisterConcernsList = new List<CustomerSisterConcern>();
        //    otherTermsConditionsList = new List<CustomerOtherTermsConditions>();
        //    customerStockStatusList = new List<CustomerStockStatus>();
        //}
        public string CUSTOMER_CODE { get; set; }
        public string CUSTOMER_EDESC { get; set; }
        public string CUSTOMER_NDESC { get; set; }
        public string GROUP_SKU_FLAG { get; set; }
        public string MASTER_CUSTOMER_CODE { get; set; }
        public string PRE_CUSTOMER_CODE { get; set; }
        public int? Childrens { get; set; }
        public int LEVEL { get; set; }
        public string REGD_OFFICE_EADDRESS { get; set; }
        public string REGD_OFFICE_NADDRESS { get; set; }
        public string TELEPHONE { get; set; }
        public string TEL_MOBILE_NO1 { get; set; }
        public string TEL_MOBILE_NO2 { get; set; }
        public string CUSTOMER_PREFIX { get; set; }
        public int? CUSTOMER_STARTID { get; set; }
        public string REMARKS { get; set; }
        public string CUSTOMER_ACCOUNT { get; set; }
        public string CUSTOMER_TYPE { get; set; }
        public int? maxCustomerCode { get; set; }
        public int? maxCustomerMasterCode { get; set; }
        public string CUSTOMER_FLAG { get; set; }
        public string ACC_CODE { get; set; }
        public string CHILD_AUTOGENERATED { get; set; }
        public string PERMANENT_ADDRESS { get; set; }
        public string TEMPORARY_ADDRESS { get; set; }
        public string FAX { get; set; }
        public string ZONE_CODE { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string REGION_CODE { get; set; }
        public string DISTRICT_CODE { get; set; }
        public string CITY_CODE { get; set; }
        public string TELEPHONE2 { get; set; }
        public string TELEPHONE3 { get; set; }
        public string PAN_VAT { get; set; }
        public string EXCISE { get; set; }
        public string EMAIL { get; set; }
        public string PARTY_TYPE_CODE { get; set; }
        public string ACCOUNTMAP { get; set; }
        public string AGENT_CODE { get; set; }
        public string DEALING_PERSON { get; set; }
        public string BRANCH_CODE { get; set; }
        public string CASH_CUSTOMER_FLAG { get; set; }
        public string ACTIVE_FLAG { get; set; }
        public string AfterSaveCustomerCode { get; set; }
        public decimal? CREDIT_RATE { get; set; }
        public decimal? CREDIT_LIMIT { get; set; }
        public decimal? CUSHION_PERCENT { get; set; }
        public decimal? PRE_CREDIT_LIMIT { get; set; }
        public decimal? DUE_BILL_COUNT { get; set; }
        public decimal? EXCEED_LIMIT_PERCENTAGE { get; set; }
        public decimal? INTEREST_RATE { get; set; }
        public decimal? BANK_GUARANTEE { get; set; }
        public DateTime? OPENING_DATE { get; set; }
        public DateTime? EXPIRY_DATE { get; set; }
        public DateTime? MATURITY_DATE { get; set; }
        public decimal? DISCOUNT_FLAT_RATE { get; set; }
        public int? DISCOUNT_DAYS { get; set; }
        public decimal? DISCOUNT_PERCENT { get; set; }
        public string EXCLUSIVE_FLAG { get; set; }
        public int? CREDIT_DAYS { get; set; }
        public string CREDIT_ACTION_FLAG { get; set; }
        public string TERMS_CONDITIONS { get; set; }
        public string CUSTOMER_GROUP_ID { get; set; }
        public string CUSTOMER_ID { get; set; }
        public string CHILD_CUSTOMER_CODE { get; set; }
        public string CHILD_UPDATE_CUSTOMER_CODE { get; set; }
        public DateTime CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string PARENT_CUSTOMER_CODE { get; set; }
        public string PR_CODE { get; set; }
        public string TPIN_VAT_NO { get; set; }
        public string SYN_ROWID { get; set; }
        public string DELTA_FLAG { get; set; }
        public string APPROVED_FLAG { get; set; }
        public int? MAX_SALES_VALUE { get; set; }
        public string TEL_MOBILE_NO3 { get; set; }
        public int? GROUP_START_NO { get; set; }
        public string PREFIX_TEXT { get; set; }
        public string EXCISE_NO { get; set; }
        public string FAX_NO { get; set; }
        public string LINK_SUB_CODE { get; set; }
        public string PRICE_LIST_ID { get; set; }

        //public List<OwnerModels> ownerInfo { get; set; }
        //public List<CustomerInvoiceWiseOpeningSetup> customerInvoiceWiseOpening { get; set; }
        //public List<CustomerDivisionModels> customerDivision { get; set; }
        //public List<CustomerInfo> customerInfoList { get; set; }
        //public List<AlternativeLocationInfo> alternativeLocationInfoList { get; set; }
        //public List<CustomerBudgetCenter> budgetCenterList { get; set; }
        //public List<CustomerSisterConcern> sisterConcernsList { get; set; }
        //public List<CustomerOtherTermsConditions> otherTermsConditionsList { get; set; }
        //public List<CustomerStockStatus> customerStockStatusList { get; set; }
    }
}