//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeoErp.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHARGE_SETUP
    {
        public string CHARGE_CODE { get; set; }
        public string ACC_CODE { get; set; }
        public string LINK_SUB_CODE { get; set; }
        public string BUDGET_CODE { get; set; }
        public string CHARGE_TYPE_FLAG { get; set; }
        public string VALUE_PERCENT_FLAG { get; set; }
        public Nullable<decimal> VALUE_PERCENT_AMOUNT { get; set; }
        public string GL_FLAG { get; set; }
        public Nullable<byte> PRIORITY_INDEX_NO { get; set; }
        public string CHARGE_APPLY_ON { get; set; }
        public Nullable<System.DateTime> APPLY_FROM_DATE { get; set; }
        public Nullable<System.DateTime> APPLY_TO_DATE { get; set; }
        public string FORM_CODE { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string APPORTION_ON { get; set; }
        public string IMPACT_ON { get; set; }
        public string APPLY_ON { get; set; }
        public string SYN_ROWID { get; set; }
        public string CHARGE_ACTIVE_FLAG { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string NON_GL_FLAG { get; set; }
        public string IMPACT_ON_FLAG { get; set; }
        public string MODIFY_BY { get; set; }
    }
}
