//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeoErp.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHARGE_TRANSACTION_DETAIL
    {
        public string TRANSACTION_NO { get; set; }
        public string REFERENCE_NO { get; set; }
        public string ITEM_CODE { get; set; }
        public Nullable<short> SERIAL_NO { get; set; }
        public string CHARGE_CODE { get; set; }
        public Nullable<decimal> CHARGE_AMOUNT { get; set; }
        public string APPORTION_FLAG { get; set; }
        public string IMPACT_ON { get; set; }
        public string FORM_CODE { get; set; }
        public string COMPANY_CODE { get; set; }
        public string BRANCH_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string CURRENCY_CODE { get; set; }
        public Nullable<decimal> EXCHANGE_RATE { get; set; }
        public string SYN_ROWID { get; set; }
        public string SESSION_ROWID { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string MODIFY_BY { get; set; }
    }
}
