//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeoErp.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY_SETUP
    {
        public string COMPANY_CODE { get; set; }
        public string COMPANY_EDESC { get; set; }
        public string COMPANY_NDESC { get; set; }
        public string PRE_COMPANY_CODE { get; set; }
        public string ADDRESS { get; set; }
        public string TELEPHONE { get; set; }
        public string EMAIL { get; set; }
        public string FAX { get; set; }
        public string WEB { get; set; }
        public string LOGO_FILE_NAME { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string REGISTRATION_NO { get; set; }
        public System.DateTime VALID_DATE { get; set; }
        public string REMARKS { get; set; }
        public string TPIN_VAT_NO { get; set; }
        public string SYN_ROWID { get; set; }
        public string CONSOLIDATE_FLAG { get; set; }
        public string ABBR_CODE { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string SMTP_HOST { get; set; }
        public string FOOTER_LOGO_FILE_NAME { get; set; }
        public string MODIFY_BY { get; set; }
    }
}
