//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeoErp.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY_DETAIL_SETUP
    {
        public string COMPANY_CODE { get; set; }
        public string PROPRIETOR_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string POSITION { get; set; }
        public string TELEPHONE { get; set; }
        public string EMAIL { get; set; }
        public string FAX { get; set; }
        public string MOBILE { get; set; }
        public string PHOTO_FILE_NAME { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string SYN_ROWID { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string MODIFY_BY { get; set; }
    }
}
