//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeoErp.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FA_SINGLE_VOUCHER
    {
        public string VOUCHER_NO { get; set; }
        public System.DateTime VOUCHER_DATE { get; set; }
        public string MANUAL_NO { get; set; }
        public short SERIAL_NO { get; set; }
        public string MASTER_ACC_CODE { get; set; }
        public string MASTER_TRANSACTION_TYPE { get; set; }
        public decimal MASTER_AMOUNT { get; set; }
        public string MASTER_BUDGET_FLAG { get; set; }
        public string ACC_CODE { get; set; }
        public string PARTICULARS { get; set; }
        public string TRANSACTION_TYPE { get; set; }
        public decimal AMOUNT { get; set; }
        public string BUDGET_FLAG { get; set; }
        public string REMARKS { get; set; }
        public string FORM_CODE { get; set; }
        public string COMPANY_CODE { get; set; }
        public string BRANCH_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string CURRENCY_CODE { get; set; }
        public Nullable<decimal> EXCHANGE_RATE { get; set; }
        public string SYN_ROWID { get; set; }
        public string TRACKING_NO { get; set; }
        public string SESSION_ROWID { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string MODIFY_BY { get; set; }
        public string ACC_ID { get; set; }
        public string CHEQUE_NO { get; set; }
        public string INVOICE_NO { get; set; }
        public Nullable<System.DateTime> EXP_BUDGET_DATE { get; set; }
        public string MR_ISSUED_BY { get; set; }
        public Nullable<decimal> MR_NO { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_DATE { get; set; }
        public string DIVISION_CODE { get; set; }
        public string EMPLOYEE_CODE { get; set; }
    }
}
