//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeoErp.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORM_SETUP
    {
        public string FORM_CODE { get; set; }
        public string FORM_EDESC { get; set; }
        public string FORM_NDESC { get; set; }
        public string DR_ACC_CODE { get; set; }
        public string CR_ACC_CODE { get; set; }
        public string MASTER_FORM_CODE { get; set; }
        public string PRE_FORM_CODE { get; set; }
        public string MODULE_CODE { get; set; }
        public string TEMPLATE_CODE { get; set; }
        public string GROUP_SKU_FLAG { get; set; }
        public string NUMBERING_FORMAT { get; set; }
        public string DATE_FORMAT { get; set; }
        public string START_ID_FLAG { get; set; }
        public string ID_GENERATION_FLAG { get; set; }
        public string CUSTOM_PREFIX_TEXT { get; set; }
        public string CUSTOM_SUFFIX_TEXT { get; set; }
        public Nullable<byte> PREFIX_LENGTH { get; set; }
        public Nullable<byte> SUFFIX_LENGTH { get; set; }
        public Nullable<byte> BODY_LENGTH { get; set; }
        public Nullable<decimal> START_NO { get; set; }
        public Nullable<decimal> LAST_NO { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> LAST_DATE { get; set; }
        public string REF_COLUMN_NAME { get; set; }
        public string PRINT_REPORT_FLAG { get; set; }
        public string PRIMARY_MANUAL_FLAG { get; set; }
        public string COPY_VALUES_FLAG { get; set; }
        public string QUALITY_CHECK_FLAG { get; set; }
        public string SERIAL_TRACKING_FLAG { get; set; }
        public string BATCH_TRACKING_FLAG { get; set; }
        public string ACC_CODE { get; set; }
        public string REMARKS { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string COINAGE_FLAG { get; set; }
        public string COINAGE_SUB_CODE { get; set; }
        public string REFERENCE_FLAG { get; set; }
        public string REF_TABLE_NAME { get; set; }
        public string PUBLIC_FLAG { get; set; }
        public string FORM_ACTION_FLAG { get; set; }
        public string TOTAL_ROUND_FLAG { get; set; }
        public Nullable<decimal> TOTAL_ROUND_INDEX { get; set; }
        public string REF_FORM_CODE { get; set; }
        public string INTER_BRANCH_FLAG { get; set; }
        public Nullable<decimal> REPORT_NO { get; set; }
        public string MULTI_UNIT_FLAG { get; set; }
        public string DELTA_FLAG { get; set; }
        public string SYN_ROWID { get; set; }
        public string SALES_INVOICE_CHALAN_FLAG { get; set; }
        public string REF_FIX_QUANTITY { get; set; }
        public string REF_FIX_PRICE { get; set; }
        public Nullable<decimal> FREEZE_BACK_DAYS { get; set; }
        public string AUTO_GL_POST { get; set; }
        public string PURCHASE_INVOICE_MRR_FLAG { get; set; }
        public Nullable<byte> DECIMAL_PLACE { get; set; }
        public string PURCHASE_EXPENSES_FLAG { get; set; }
        public string BATCH_FLAG { get; set; }
        public string RATE_SCHEDULE_FIX_PRICE { get; set; }
        public string FREEZE_MANUAL_ENTRY_FLAG { get; set; }
        public string ADVANCE_FLAG { get; set; }
        public string RT_CONTROL_FLAG { get; set; }
        public string FORM_TYPE { get; set; }
        public string COSTING_FLAG { get; set; }
        public string NEGATIVE_STOCK_FLAG { get; set; }
        public string QC_PARAMETER_FLAG { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string OTHER_INFO_FLAG { get; set; }
        public string CUSTOM_MANUAL_PREFIX_TEXT { get; set; }
        public string CUSTOM_MANUAL_SUFFIX_TEXT { get; set; }
        public Nullable<byte> BODY_MANUAL_LENGTH { get; set; }
        public Nullable<decimal> START_MANUAL_NO { get; set; }
        public string ORDER_ACCESS_FAB_FLAG { get; set; }
        public string LOT_GEN_FLAG { get; set; }
        public string AFTER_VERIFY_FLAG { get; set; }
        public string ONLINE_FLAG { get; set; }
        public string ADD_ROW_FLAG { get; set; }
        public string PRICE_CONTROL_FLAG { get; set; }
        public string RATE_DIFF_FLAG { get; set; }
        public string FREEZE_MASTER_REF_FLAG { get; set; }
        public string ACCESS_BDFSM_FLAG { get; set; }
        public string CUSTOMER_APPROVAL_FLAG { get; set; }
        public string INFO_FLAG { get; set; }
        public string WM_FLAG { get; set; }
        public string FREEQTY_FLAG { get; set; }
        public string DC_VAT_FLAG { get; set; }
        public string COMMITMENT_FLAG { get; set; }
        public string ORDER_DISPATCH_FLAG { get; set; }
        public string MODIFY_BY { get; set; }
        public string PURCHASE_MRR_GRNI_FLAG { get; set; }
        public string PENDING_INFO_FLAG { get; set; }
        public string ROLL_TRACKING_FLAG { get; set; }
        public string BACK_DATE_VNO_SAVE_FLAG { get; set; }
        public string AFTER_POSTING_FLAG { get; set; }
        public string DC_TDS_FLAG { get; set; }
        public string PAYMENT_MODE_FLAG { get; set; }
        public string INVOICE_PJV_FORM_CODE { get; set; }
        public string DISCOUNT_SCHEDULE_FLAG { get; set; }
    }
}
