//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeoErp.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORM_DETAIL_SETUP
    {
        public short SERIAL_NO { get; set; }
        public string TABLE_NAME { get; set; }
        public string COLUMN_NAME { get; set; }
        public short COLUMN_WIDTH { get; set; }
        public string COLUMN_HEADER { get; set; }
        public short TOP_POSITION { get; set; }
        public short LEFT_POSITION { get; set; }
        public string DISPLAY_FLAG { get; set; }
        public string DEFA_VALUE { get; set; }
        public string IS_DESC_FLAG { get; set; }
        public string MASTER_CHILD_FLAG { get; set; }
        public string FORM_CODE { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string FILTER_VALUE { get; set; }
        public string SYN_ROWID { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string MODIFY_BY { get; set; }
    }
    public partial class FORM_DETAIL_SETUP_COLUMN
    {
        public string TABLE_NAME { get; set; }
        public string COLUMN_NAME { get; set; }
    }
}
