//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeoErp.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORM_QUICK_INFO_SETUP
    {
        public string INFO_CODE { get; set; }
        public string FORM_CODE { get; set; }
        public string TABLE_NAME { get; set; }
        public string COLUMN_NAME { get; set; }
        public string ACTION_FLAG { get; set; }
        public string APPLY_ON_FLAG { get; set; }
        public string REMARKS { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string SYN_ROWID { get; set; }
        public string MODIFY_BY { get; set; }
    }
}
