//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeoErp.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IP_PURCHASE_MRR
    {
        public string MRR_NO { get; set; }
        public System.DateTime MRR_DATE { get; set; }
        public string MANUAL_NO { get; set; }
        public string SUPPLIER_CODE { get; set; }
        public string TO_LOCATION_CODE { get; set; }
        public short SERIAL_NO { get; set; }
        public string ITEM_CODE { get; set; }
        public string MU_CODE { get; set; }
        public decimal QUANTITY { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
        public Nullable<decimal> TOTAL_PRICE { get; set; }
        public Nullable<decimal> CALC_UNIT_PRICE { get; set; }
        public Nullable<decimal> CALC_QUANTITY { get; set; }
        public Nullable<decimal> COMPLETED_QUANTITY { get; set; }
        public string REMARKS { get; set; }
        public string FORM_CODE { get; set; }
        public string COMPANY_CODE { get; set; }
        public string BRANCH_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string CURRENCY_CODE { get; set; }
        public Nullable<decimal> EXCHANGE_RATE { get; set; }
        public Nullable<byte> TERMS_DAY { get; set; }
        public string SYN_ROWID { get; set; }
        public Nullable<decimal> CALC_TOTAL_PRICE { get; set; }
        public Nullable<long> TRACKING_NO { get; set; }
        public string SESSION_ROWID { get; set; }
        public string BATCH_NO { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string LOT_NO { get; set; }
        public string SUPPLIER_MRR_NO { get; set; }
        public string PHOTO_FILE_NAME1 { get; set; }
        public string PHOTO_FILE_NAME2 { get; set; }
        public string SPECIFICATION { get; set; }
        public string MODIFY_BY { get; set; }
        public string PP_NO { get; set; }
        public Nullable<System.DateTime> SUPPLIER_MRR_DATE { get; set; }
        public string BRAND_NAME { get; set; }
        public Nullable<System.DateTime> SUPPLIER_INV_DATE { get; set; }
        public string BRAND_ACCEPT_FLAG { get; set; }
        public string BRAND_REMARKS { get; set; }
        public string SUPPLIER_INV_NO { get; set; }
        public string DIVISION_CODE { get; set; }
        public Nullable<decimal> RACK_QTY { get; set; }
        public Nullable<decimal> RACK2_QTY { get; set; }
        public Nullable<decimal> GATE_ENTRY_NO { get; set; }
    }
}
