//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeoErp.Core.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NeoErpCoreEntity : DbContext
    {
        //public NeoErpCoreEntity()
        //    : base("name=NeoErpCoreEntity")
        //{
        //}
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHARGE_SETUP> CHARGE_SETUP { get; set; }
        public virtual DbSet<CHARGE_TRANSACTION> CHARGE_TRANSACTION { get; set; }
        public virtual DbSet<COMPANY_DETAIL_SETUP> COMPANY_DETAIL_SETUP { get; set; }
        public virtual DbSet<COMPANY_SETUP> COMPANY_SETUP { get; set; }
        public virtual DbSet<CURRENCY_SETUP> CURRENCY_SETUP { get; set; }
        public virtual DbSet<CUSTOM_TRANSACTION> CUSTOM_TRANSACTION { get; set; }
        public virtual DbSet<FA_SINGLE_VOUCHER> FA_SINGLE_VOUCHER { get; set; }
        public virtual DbSet<FORM_CUSTOM_SETUP> FORM_CUSTOM_SETUP { get; set; }
        public virtual DbSet<FORM_DETAIL_SETUP> FORM_DETAIL_SETUP { get; set; }
        public virtual DbSet<FORM_SETUP> FORM_SETUP { get; set; }
        public virtual DbSet<IP_PRODUCTION_ISSUE> IP_PRODUCTION_ISSUE { get; set; }
        public virtual DbSet<IP_PRODUCTION_MRR> IP_PRODUCTION_MRR { get; set; }
        public virtual DbSet<IP_PURCHASE_INVOICE> IP_PURCHASE_INVOICE { get; set; }
        public virtual DbSet<IP_PURCHASE_MRR> IP_PURCHASE_MRR { get; set; }
        public virtual DbSet<SA_CUSTOMER_SETUP> SA_CUSTOMER_SETUP { get; set; }
        public virtual DbSet<SA_REGIONAL_SETUP> SA_REGIONAL_SETUP { get; set; }
        public virtual DbSet<SA_SALES_CHALAN> SA_SALES_CHALAN { get; set; }
        public virtual DbSet<SA_SALES_INVOICE> SA_SALES_INVOICE { get; set; }
        public virtual DbSet<SA_SALES_ORDER> SA_SALES_ORDER { get; set; }
        public virtual DbSet<SA_SALES_RETURN> SA_SALES_RETURN { get; set; }
        public virtual DbSet<SC_APPLICATION_USERS> SC_APPLICATION_USERS { get; set; }
        public virtual DbSet<SC_BRANCH_CONTROL> SC_BRANCH_CONTROL { get; set; }
        public virtual DbSet<SC_COMPANY_CONTROL> SC_COMPANY_CONTROL { get; set; }
        public virtual DbSet<CHARGE_TRANSACTION_DETAIL> CHARGE_TRANSACTION_DETAIL { get; set; }
        public virtual DbSet<FORM_QUICK_INFO_SETUP> FORM_QUICK_INFO_SETUP { get; set; }
        public virtual DbSet<SC_DIVISION_CONTROL> SC_DIVISION_CONTROL { get; set; }
        public virtual DbSet<SC_LEDGER_CONTROL> SC_LEDGER_CONTROL { get; set; }
        public virtual DbSet<SC_MODULE_CONTROL> SC_MODULE_CONTROL { get; set; }
    }
}
