//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeoErp.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SA_CUSTOMER_SETUP
    {
        public string CUSTOMER_CODE { get; set; }
        public string CUSTOMER_EDESC { get; set; }
        public string CUSTOMER_NDESC { get; set; }
        public string REGD_OFFICE_EADDRESS { get; set; }
        public string REGD_OFFICE_NADDRESS { get; set; }
        public string TEL_MOBILE_NO1 { get; set; }
        public string TEL_MOBILE_NO2 { get; set; }
        public string FAX_NO { get; set; }
        public string EMAIL { get; set; }
        public string PARTY_TYPE_CODE { get; set; }
        public string CUSTOMER_FLAG { get; set; }
        public string LINK_SUB_CODE { get; set; }
        public Nullable<decimal> CREDIT_RATE { get; set; }
        public Nullable<decimal> CREDIT_LIMIT { get; set; }
        public Nullable<decimal> CUSHION_PERCENT { get; set; }
        public Nullable<int> DUE_BILL_COUNT { get; set; }
        public string ACTIVE_FLAG { get; set; }
        public string REMARKS { get; set; }
        public string GROUP_SKU_FLAG { get; set; }
        public string MASTER_CUSTOMER_CODE { get; set; }
        public string PRE_CUSTOMER_CODE { get; set; }
        public Nullable<decimal> DISCOUNT_FLAT_RATE { get; set; }
        public string EXCLUSIVE_FLAG { get; set; }
        public Nullable<short> DISCOUNT_DAYS { get; set; }
        public Nullable<decimal> DISCOUNT_PERCENT { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string REGION_CODE { get; set; }
        public Nullable<short> CREDIT_DAYS { get; set; }
        public string CREDIT_ACTION_FLAG { get; set; }
        public string ACC_CODE { get; set; }
        public string PR_CODE { get; set; }
        public string TPIN_VAT_NO { get; set; }
        public string SYN_ROWID { get; set; }
        public string DELTA_FLAG { get; set; }
        public string TERMS_CONDITIONS { get; set; }
        public Nullable<decimal> BANK_GUARANTEE { get; set; }
        public Nullable<decimal> PRE_CREDIT_LIMIT { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string BRANCH_CODE { get; set; }
        public string AGENT_CODE { get; set; }
        public string APPROVED_FLAG { get; set; }
        public string PAN_NO { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
        public Nullable<decimal> EXCEED_LIMIT_PERCENTAGE { get; set; }
        public string MODIFY_BY { get; set; }
        public Nullable<decimal> MAX_SALES_VALUE { get; set; }
        public string TEL_MOBILE_NO3 { get; set; }
        public string CASH_CUSTOMER_FLAG { get; set; }
        public string CUSTOMER_ID { get; set; }
        public Nullable<decimal> GROUP_START_NO { get; set; }
        public string PREFIX_TEXT { get; set; }
        public Nullable<decimal> INTEREST_RATE { get; set; }
        public Nullable<System.DateTime> OPENING_DATE { get; set; }
        public Nullable<System.DateTime> MATURITY_DATE { get; set; }
        public string CUSTOMER_GROUP_ID { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string ZONE_CODE { get; set; }
        public string DISTRICT_CODE { get; set; }
        public string CITY_CODE { get; set; }
        public string DEALING_PERSON { get; set; }
    }
}
