//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeoErp.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SC_APPLICATION_USERS
    {
        public int USER_NO { get; set; }
        public int PRE_USER_NO { get; set; }
        public string GROUP_SKU_FLAG { get; set; }
        public string LOGIN_CODE { get; set; }
        public string LOGIN_EDESC { get; set; }
        public string LOGIN_NDESC { get; set; }
        public string PASSWORD { get; set; }
        public string EMPLOYEE_CODE { get; set; }
        public string USER_LOCK_FLAG { get; set; }
        public string USER_SCHEDULE_FLAG { get; set; }
        public string HOLIDAY_LOGON_FLAG { get; set; }
        public string USER_HISTORY_FLAG { get; set; }
        public string IMAGE_FILE_NAME { get; set; }
        public string REMARKS { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string ABBR_CODE { get; set; }
        public string SYN_ROWID { get; set; }
        public string DELTA_FLAG { get; set; }
        public string SUPER_USER_FLAG { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public Nullable<decimal> LOCK_TIME { get; set; }
        public string SU_FLAG { get; set; }
        public string MODIFY_BY { get; set; }
        public string DASHBOARD_LOGON_FLAG { get; set; }
        public string GROUP_ACCESS_FLAG { get; set; }
        public string USER_TYPE { get; set; }
        public string LM_FLAG { get; set; }
        public string LM_ADMIN_FLAG { get; set; }
        public Nullable<System.DateTime> LAST_EXPIRY_DATE { get; set; }
        public Nullable<decimal> SENIOR_NO { get; set; }
        public string GLOBAL_MASTER_EDIT_FLAG { get; set; }
        public string ESIGNATURE { get; set; }
    }
}
