//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeoErp.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SC_DIVISION_CONTROL
    {
        public int USER_NO { get; set; }
        public string DIVISION_CODE { get; set; }
        public string ACCESS_FLAG { get; set; }
        public string MORE_FLAG { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string SYN_ROWID { get; set; }
        public string MODIFY_BY { get; set; }
    }
}
