//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeoErp.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SC_MODULE_CONTROL
    {
        public string MODULE_CODE { get; set; }
        public string MODULE_FLAG { get; set; }
        public string COMPANY_CODE { get; set; }
        public string REGISTER_KEY { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string SYN_ROWID { get; set; }
        public string MODIFY_BY { get; set; }
    }
}
