CREATE TABLE PL_BRD_ACTIVITY_PLAN
(
  PLAN_CODE           NUMBER(12)                NOT NULL,
  PLAN_EDESC          VARCHAR2(200 BYTE)        NOT NULL,
  PLAN_NDESC          VARCHAR2(400 BYTE)        DEFAULT NULL,
  EST_AMOUNT          NUMBER(16,2)              DEFAULT NULL,
  TIME_FRAME_CODE     NUMBER(4)                 NOT NULL,
  CALENDAR_TYPE       VARCHAR2(3 BYTE)          DEFAULT 'LOC',
  START_DATE          DATE                      NOT NULL,
  END_DATE            DATE                      NOT NULL,
  REMARKS             VARCHAR2(400 BYTE)        DEFAULT NULL,
  COMPANY_CODE        VARCHAR2(30 BYTE),
  BRANCH_CODE         VARCHAR2(30 BYTE),
  CREATED_BY          VARCHAR2(30 BYTE),
  CREATED_DATE        DATE,
  LAST_MODIFIED_BY    VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE  DATE,
  APPROVED_FLAG       CHAR(1 BYTE)              DEFAULT 'N',
  APPROVED_BY         VARCHAR2(30 BYTE),
  APPROVED_DATE       DATE,
  DELETED_FLAG        CHAR(1 BYTE)              DEFAULT 'N',
  CONSTRAINT CHK_BATVY_APP_FLAG
  CHECK (APPROVED_FLAG IN ('Y', 'N')),
  CONSTRAINT CHK_BATVY_CALENDAR_TYPE
  CHECK (CALENDAR_TYPE IN ('ENG', 'LOC')),
  CONSTRAINT CHK_BATVY_DEL_FLAG
  CHECK (DELETED_FLAG IN ('Y', 'N'))
)#
CREATE TABLE PL_BRD_ACTIVITY_PLAN_DTL
(
  PLAN_CODE           NUMBER(12)                NOT NULL,
  PLAN_DATE           DATE                      NOT NULL,
  PER_DAY_AMOUNT      NUMBER(16,4)              DEFAULT NULL,
  ACTIVITY_CODE       VARCHAR2(30 BYTE)         DEFAULT NULL,
  DIVISION_CODE       VARCHAR2(30 BYTE)         DEFAULT NULL,
  BRAND_CODE          VARCHAR2(30 BYTE)         DEFAULT NULL,
  FREQUENCY_JSON      VARCHAR2(500 BYTE)        DEFAULT NULL,
  REMARKS             VARCHAR2(400 BYTE)        DEFAULT NULL,
  COMPANY_CODE        VARCHAR2(30 BYTE),
  BRANCH_CODE         VARCHAR2(30 BYTE),
  CREATED_BY          VARCHAR2(30 BYTE),
  CREATED_DATE        DATE,
  LAST_MODIFIED_BY    VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE  DATE,
  APPROVED_FLAG       CHAR(1 BYTE)              DEFAULT 'N',
  APPROVED_BY         VARCHAR2(30 BYTE),
  APPROVED_DATE       DATE,
  DELETED_FLAG        CHAR(1 BYTE)              DEFAULT 'N'
)#
CREATE TABLE PL_BRD_PRCMT_PLAN
(
  PLAN_CODE           NUMBER(12)                NOT NULL,
  PLAN_EDESC          VARCHAR2(200 BYTE)        NOT NULL,
  PLAN_NDESC          VARCHAR2(400 BYTE)        DEFAULT NULL,
  EST_AMOUNT          NUMBER(16,2)              DEFAULT NULL,
  TIME_FRAME_CODE     NUMBER(4)                 NOT NULL,
  CALENDAR_TYPE       VARCHAR2(3 BYTE)          DEFAULT 'LOC',
  START_DATE          DATE                      NOT NULL,
  END_DATE            DATE                      NOT NULL,
  REMARKS             VARCHAR2(400 BYTE)        DEFAULT NULL,
  COMPANY_CODE        VARCHAR2(30 BYTE),
  BRANCH_CODE         VARCHAR2(30 BYTE),
  CREATED_BY          VARCHAR2(30 BYTE),
  CREATED_DATE        DATE,
  LAST_MODIFIED_BY    VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE  DATE,
  APPROVED_FLAG       CHAR(1 BYTE)              DEFAULT 'N',
  APPROVED_BY         VARCHAR2(30 BYTE),
  APPROVED_DATE       DATE,
  DELETED_FLAG        CHAR(1 BYTE)              DEFAULT 'N',
  CONSTRAINT CHK_BPRCMT_APP_FLAG
  CHECK (APPROVED_FLAG IN ('Y', 'N')),
  CONSTRAINT CHK_BPRCMT_CALENDAR_TYPE
  CHECK (CALENDAR_TYPE IN ('ENG', 'LOC')),
  CONSTRAINT CHK_BPRCMT_DEL_FLAG
  CHECK (DELETED_FLAG IN ('Y', 'N'))
)#
CREATE TABLE PL_BRD_PRCMT_PLAN_DTL
(
  PLAN_CODE           NUMBER(12)                NOT NULL,
  PLAN_DATE           DATE                      NOT NULL,
  PER_DAY_AMOUNT      NUMBER(16,4)              DEFAULT NULL,
  ITEM_CODE           VARCHAR2(30 BYTE)         DEFAULT NULL,
  DIVISION_CODE       VARCHAR2(30 BYTE)         DEFAULT NULL,
  BRAND_CODE          VARCHAR2(30 BYTE)         DEFAULT NULL,
  FREQUENCY_JSON      VARCHAR2(500 BYTE)        DEFAULT NULL,
  REMARKS             VARCHAR2(400 BYTE)        DEFAULT NULL,
  COMPANY_CODE        VARCHAR2(30 BYTE),
  BRANCH_CODE         VARCHAR2(30 BYTE),
  CREATED_BY          VARCHAR2(30 BYTE),
  CREATED_DATE        DATE,
  LAST_MODIFIED_BY    VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE  DATE,
  APPROVED_FLAG       CHAR(1 BYTE)              DEFAULT 'N',
  APPROVED_BY         VARCHAR2(30 BYTE),
  APPROVED_DATE       DATE,
  DELETED_FLAG        CHAR(1 BYTE)              DEFAULT 'N',
  CONSTRAINT CHK_BPRCMTD_APP_FLAG
  CHECK (APPROVED_FLAG IN ('Y', 'N')),
  CONSTRAINT CHK_BPRCMTD_DEL_FLAG
  CHECK (DELETED_FLAG IN ('Y', 'N'))
)#
CREATE TABLE PL_COA_PLAN
(
  PLAN_CODE           NUMBER(12)                NOT NULL,
  PLAN_EDESC          VARCHAR2(200 BYTE)        NOT NULL,
  PLAN_NDESC          VARCHAR2(400 BYTE)        DEFAULT NULL,
  SALES_AMOUNT        NUMBER(16,2)              DEFAULT NULL,
  TIME_FRAME_CODE     NUMBER(4)                 NOT NULL,
  CALENDAR_TYPE       VARCHAR2(3 BYTE)          DEFAULT 'LOC',
  START_DATE          DATE                      NOT NULL,
  END_DATE            DATE                      NOT NULL,
  REMARKS             VARCHAR2(400 BYTE)        DEFAULT NULL,
  COMPANY_CODE        VARCHAR2(30 BYTE),
  BRANCH_CODE         VARCHAR2(30 BYTE),
  CREATED_BY          VARCHAR2(30 BYTE),
  CREATED_DATE        DATE,
  LAST_MODIFIED_BY    VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE  DATE,
  APPROVED_FLAG       CHAR(1 BYTE)              DEFAULT 'N',
  APPROVED_BY         VARCHAR2(30 BYTE),
  APPROVED_DATE       DATE,
  DELETED_FLAG        CHAR(1 BYTE)              DEFAULT 'N',
  CONSTRAINT CHK_COA_APPROVED_FLAG
  CHECK (APPROVED_FLAG IN ('Y', 'N')),
  CONSTRAINT CHK_COA_CALENDAR_TYPE
  CHECK (CALENDAR_TYPE IN ('ENG', 'LOC')),
  CONSTRAINT CHK_COA_DELETED_FLAG
  CHECK (DELETED_FLAG IN ('Y', 'N')),
  CONSTRAINT PK_COA_PLAN
  PRIMARY KEY
  (PLAN_CODE)
  USING INDEX PK_COA_PLAN,
  CONSTRAINT UNQ_COA_PLAN
  UNIQUE (PLAN_EDESC, START_DATE, END_DATE)
  USING INDEX UNQ_COA_PLAN
)#
CREATE TABLE PL_COA_PLAN_DTL
(
  PLAN_CODE           NUMBER(12)                NOT NULL,
  PLAN_DATE           DATE                      NOT NULL,
  PER_DAY_AMOUNT      NUMBER(16,4)              DEFAULT NULL,
  ACC_CODE            VARCHAR2(30 BYTE)         DEFAULT NULL,
  DIVISION_CODE       VARCHAR2(30 BYTE)         DEFAULT NULL,
  FREQUENCY_JSON      VARCHAR2(500 BYTE)        DEFAULT NULL,
  REMARKS             VARCHAR2(400 BYTE)        DEFAULT NULL,
  COMPANY_CODE        VARCHAR2(30 BYTE),
  BRANCH_CODE         VARCHAR2(30 BYTE),
  CREATED_BY          VARCHAR2(30 BYTE),
  CREATED_DATE        DATE,
  LAST_MODIFIED_BY    VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE  DATE,
  APPROVED_FLAG       CHAR(1 BYTE)              DEFAULT 'N',
  APPROVED_BY         VARCHAR2(30 BYTE),
  APPROVED_DATE       DATE,
  DELETED_FLAG        CHAR(1 BYTE)              DEFAULT 'N',
  CONSTRAINT CHK_COA_DTL_APP_FLAG
  CHECK (APPROVED_FLAG IN ('Y', 'N')),
  CONSTRAINT CHK_COA_DTL_DEL_FLAG
  CHECK (DELETED_FLAG IN ('Y', 'N')),
  CONSTRAINT UNQ_COA_PLAN_DTL
  UNIQUE (PLAN_CODE, PLAN_DATE, ACC_CODE, DIVISION_CODE, BRANCH_CODE, COMPANY_CODE)
  USING INDEX UNQ_COA_PLAN_DTL,
  CONSTRAINT FK_COA_PLAN_DTL 
  FOREIGN KEY (PLAN_CODE) 
  REFERENCES PL_COA_PLAN (PLAN_CODE)
)#
CREATE TABLE PL_COA_SUB_PLAN
(
  PLAN_CODE           NUMBER(12)                NOT NULL,
  PLAN_EDESC          VARCHAR2(200 BYTE)        NOT NULL,
  PLAN_NDESC          VARCHAR2(400 BYTE)        DEFAULT NULL,
  SALES_AMOUNT        NUMBER(16,2)              DEFAULT NULL,
  TIME_FRAME_CODE     NUMBER(4)                 NOT NULL,
  CALENDAR_TYPE       VARCHAR2(3 BYTE)          DEFAULT 'LOC',
  START_DATE          DATE                      NOT NULL,
  END_DATE            DATE                      NOT NULL,
  REMARKS             VARCHAR2(400 BYTE)        DEFAULT NULL,
  COMPANY_CODE        VARCHAR2(30 BYTE),
  BRANCH_CODE         VARCHAR2(30 BYTE),
  CREATED_BY          VARCHAR2(30 BYTE),
  CREATED_DATE        DATE,
  LAST_MODIFIED_BY    VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE  DATE,
  APPROVED_FLAG       CHAR(1 BYTE)              DEFAULT 'N',
  APPROVED_BY         VARCHAR2(30 BYTE),
  APPROVED_DATE       DATE,
  DELETED_FLAG        CHAR(1 BYTE)              DEFAULT 'N'
)#
CREATE TABLE PL_COA_SUB_PLAN_DTL
(
  PLAN_CODE           NUMBER(12)                NOT NULL,
  PLAN_DATE           DATE                      NOT NULL,
  PER_DAY_AMOUNT      NUMBER(16,4)              DEFAULT NULL,
  ACC_CODE            VARCHAR2(30 BYTE)         DEFAULT NULL,
  SUB_CODE            VARCHAR2(30 BYTE)         DEFAULT NULL,
  DIVISION_CODE       VARCHAR2(30 BYTE)         DEFAULT NULL,
  FREQUENCY_JSON      VARCHAR2(500 BYTE)        DEFAULT NULL,
  REMARKS             VARCHAR2(400 BYTE)        DEFAULT NULL,
  COMPANY_CODE        VARCHAR2(30 BYTE),
  BRANCH_CODE         VARCHAR2(30 BYTE),
  CREATED_BY          VARCHAR2(30 BYTE),
  CREATED_DATE        DATE,
  LAST_MODIFIED_BY    VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE  DATE,
  APPROVED_FLAG       CHAR(1 BYTE)              DEFAULT 'N',
  APPROVED_BY         VARCHAR2(30 BYTE),
  APPROVED_DATE       DATE,
  DELETED_FLAG        CHAR(1 BYTE)              DEFAULT 'N',
  BUDGET_CODE         VARCHAR2(30 BYTE)
)#
CREATE TABLE PL_MASTER_PLAN_MAP
(
  MASTER_PLAN_CODE         NUMBER(12)           NOT NULL,
  PARENT_MASTER_PLAN_CODE  NUMBER(12)           NOT NULL
)#
CREATE TABLE PL_MASTER_SALES_PLAN
(
  MASTER_PLAN_CODE    NUMBER(12)                NOT NULL,
  MASTER_PLAN_EDESC   VARCHAR2(500 BYTE)        NOT NULL,
  MASTER_PLAN_NDESC   VARCHAR2(500 BYTE)        NOT NULL,
  START_DATE          DATE                      NOT NULL,
  END_DATE            DATE                      NOT NULL,
  CUSTOMER_CODE       VARCHAR2(30 BYTE)         DEFAULT NULL,
  EMPLOYEE_CODE       VARCHAR2(30 BYTE)         DEFAULT NULL,
  DIVISION_CODE       VARCHAR2(30 BYTE)         DEFAULT NULL,
  REMARKS             VARCHAR2(400 BYTE)        DEFAULT NULL,
  COMPANY_CODE        VARCHAR2(30 BYTE),
  BRANCH_CODE         VARCHAR2(30 BYTE),
  CREATED_BY          VARCHAR2(30 BYTE),
  CREATED_DATE        DATE,
  LAST_MODIFIED_BY    VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE  DATE,
  APPROVED_FLAG       CHAR(1 BYTE),
  APPROVED_BY         VARCHAR2(30 BYTE),
  APPROVED_DATE       DATE,
  DELETED_FLAG        CHAR(1 BYTE)
)#
CREATE TABLE PL_MATERIAL_PLAN
(
  PLAN_CODE          NUMBER(12)                 NOT NULL,
  PLAN_EDESC         VARCHAR2(200 BYTE)         NOT NULL,
  PLAN_NDESC         VARCHAR2(400 BYTE)         DEFAULT NULL,
  PLAN_DATE          DATE,
  COMPANY_CODE       VARCHAR2(30 BYTE),
  BRANCH_CODE        VARCHAR2(30 BYTE),
  CREATED_BY         VARCHAR2(30 BYTE),
  CREATED_DATE       DATE,
  MODIFIED_BY        VARCHAR2(30 BYTE),
  MODIFIED_DATE      DATE,
  DELETED_FLAG       CHAR(1 BYTE),
  MATERIAL_QUANTITY  NUMBER(10)                 DEFAULT '0',
  REFERENCE_FLAG     NVARCHAR2(10),
  REFERENCE_CODE     NVARCHAR2(10)
)#
CREATE TABLE PL_MATERIAL_PLAN_DTL
(
  PLAN_CODE           NUMBER(12)                NOT NULL,
  PLAN_DATE           DATE                      NOT NULL,
  ITEM_CODE           VARCHAR2(30 BYTE)         DEFAULT NULL,
  FINISHED_ITEM_CODE  VARCHAR2(30 BYTE)         NOT NULL,
  MATERIAL_QUANTITY   NUMBER(10)                DEFAULT '0',
  REQUIRED_QUANTITY   NUMBER(14,4)              DEFAULT NULL,
  CALC_QUANTITY       NUMBER(14,4)              DEFAULT NULL,
  STOCK               NUMBER(14,4)              DEFAULT NULL,
  PO_PENDING          NUMBER(14,4)              DEFAULT NULL,
  REMAINING_QUANTITY  NUMBER(14,4)              DEFAULT NULL,
  COMPANY_CODE        VARCHAR2(30 BYTE),
  BRANCH_CODE         VARCHAR2(30 BYTE),
  CREATED_BY          VARCHAR2(30 BYTE),
  CREATED_DATE        DATE,
  LAST_MODIFIED_BY    VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE  DATE,
  DELETED_FLAG        CHAR(1 BYTE),
  REFERENCE_FLAG     NVARCHAR2(10)
)#
CREATE TABLE PL_PLAN_ITEM_MAPPING
(
  PLAN_CODE           NUMBER(12)                NOT NULL,
  ITEM_CODE           VARCHAR2(30 BYTE)         NOT NULL,
  PRE_ITEM_CODE       VARCHAR2(30 BYTE)         NOT NULL,
  MASTER_ITEM_CODE    VARCHAR2(30 BYTE)         NOT NULL,
  COMPANY_CODE        VARCHAR2(30 BYTE),
  BRANCH_CODE         VARCHAR2(30 BYTE),
  CREATED_BY          VARCHAR2(30 BYTE),
  CREATED_DATE        DATE,
  LAST_MODIFIED_BY    VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE  DATE,
  DELETED_FLAG        CHAR(1 BYTE)
)#
CREATE TABLE PL_PREFERENCE_SETUP
(
  COMPANY_CODE      VARCHAR2(30 BYTE),
  BRANCH_CODE       VARCHAR2(30 BYTE),
  ITEM_GROUP_ENTRY  CHAR(1 BYTE)                DEFAULT 'N',
  SHOW_EMPLOYEE     VARCHAR2(1 BYTE)            DEFAULT 'N',
  SHOW_BRANCH       VARCHAR2(1 BYTE)            DEFAULT 'N',
  SHOW_CUSTOMER     VARCHAR2(1 BYTE)            DEFAULT 'N',
  SHOW_ITEM         VARCHAR2(1 BYTE)            DEFAULT 'N',
  PL_NAME           NVARCHAR2(45),
  SHOW_DIVISION     NVARCHAR2(1)                DEFAULT 'N',
  SHOW_PARTY_TYPE   VARCHAR2(1 BYTE)            DEFAULT 'N'
)#
CREATE TABLE PL_PRO_PLAN
(
  PLAN_CODE           NUMBER(12)                NOT NULL,
  PLAN_EDESC          VARCHAR2(200 BYTE)        NOT NULL,
  PLAN_NDESC          VARCHAR2(400 BYTE)        DEFAULT NULL,
  PRODUCTION_QTY      NUMBER(16,2)              DEFAULT NULL,
  TIME_FRAME_CODE     NUMBER(4)                 NOT NULL,
  CALENDAR_TYPE       VARCHAR2(3 BYTE)          DEFAULT 'LOC',
  START_DATE          DATE                      NOT NULL,
  END_DATE            DATE                      NOT NULL,
  REMARKS             VARCHAR2(400 BYTE)        DEFAULT NULL,
  COMPANY_CODE        VARCHAR2(30 BYTE),
  BRANCH_CODE         VARCHAR2(30 BYTE),
  CREATED_BY          VARCHAR2(30 BYTE),
  CREATED_DATE        DATE,
  LAST_MODIFIED_BY    VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE  DATE,
  APPROVED_FLAG       CHAR(1 BYTE)              DEFAULT 'N',
  APPROVED_BY         VARCHAR2(30 BYTE),
  APPROVED_DATE       DATE,
  DELETED_FLAG        CHAR(1 BYTE)              DEFAULT 'N',
  CONSTRAINT CHK_PRO_APPROVED_FLAG
  CHECK (APPROVED_FLAG IN ('Y', 'N')),
  CONSTRAINT CHK_PRO_CALENDAR_TYPE
  CHECK (CALENDAR_TYPE IN ('ENG', 'LOC')),
  CONSTRAINT CHK_PRO_DELETED_FLAG
  CHECK (DELETED_FLAG IN ('Y', 'N')),
  CONSTRAINT UNQ_PRO_PLAN
  UNIQUE (PLAN_EDESC, START_DATE, END_DATE)  DISABLE
)#
CREATE TABLE PL_PRO_PLAN_DTL
(
  PLAN_CODE           NUMBER(12)                NOT NULL,
  PLAN_DATE           DATE                      NOT NULL,
  PER_DAY_QUANTITY    NUMBER(16,4)              DEFAULT NULL,
  ITEM_CODE           VARCHAR2(30 BYTE)         DEFAULT NULL,
  DIVISION_CODE       VARCHAR2(30 BYTE)         DEFAULT NULL,
  BRAND_CODE          VARCHAR2(30 BYTE)         DEFAULT NULL,
  FREQUENCY_JSON      VARCHAR2(500 BYTE)        DEFAULT NULL,
  REMARKS             VARCHAR2(400 BYTE)        DEFAULT NULL,
  COMPANY_CODE        VARCHAR2(30 BYTE),
  BRANCH_CODE         VARCHAR2(30 BYTE),
  CREATED_BY          VARCHAR2(30 BYTE),
  CREATED_DATE        DATE,
  LAST_MODIFIED_BY    VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE  DATE,
  APPROVED_FLAG       CHAR(1 BYTE)              DEFAULT 'N',
  APPROVED_BY         VARCHAR2(30 BYTE),
  APPROVED_DATE       DATE,
  DELETED_FLAG        CHAR(1 BYTE)              DEFAULT 'N'
)#
CREATE TABLE PL_SALES_PLAN
(
  PLAN_CODE           NUMBER(12)                NOT NULL,
  PLAN_EDESC          VARCHAR2(200 BYTE)        NOT NULL,
  PLAN_NDESC          VARCHAR2(400 BYTE)        DEFAULT NULL,
  SALES_QUANTITY      NUMBER(16,2)              DEFAULT NULL,
  SALES_AMOUNT        NUMBER(16,2)              DEFAULT NULL,
  TIME_FRAME_CODE     NUMBER(4)                 NOT NULL,
  CALENDAR_TYPE       VARCHAR2(3 BYTE),
  START_DATE          DATE                      NOT NULL,
  END_DATE            DATE                      NOT NULL,
  SALES_PRICE_TYPE    VARCHAR2(50 BYTE),
  REMARKS             VARCHAR2(400 BYTE)        DEFAULT NULL,
  COMPANY_CODE        VARCHAR2(30 BYTE),
  BRANCH_CODE         VARCHAR2(30 BYTE),
  CREATED_BY          VARCHAR2(30 BYTE),
  CREATED_DATE        DATE,
  LAST_MODIFIED_BY    VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE  DATE,
  APPROVED_FLAG       CHAR(1 BYTE),
  APPROVED_BY         VARCHAR2(30 BYTE),
  APPROVED_DATE       DATE,
  DELETED_FLAG        CHAR(1 BYTE),
  CHECK ( CALENDAR_TYPE IN ('ENG','LOC')),
  CHECK ( CALENDAR_TYPE IN ('ENG','LOC')),
  CONSTRAINT PK_SALES_PLAN
  PRIMARY KEY
  (PLAN_CODE)
  USING INDEX PK_SALES_PLAN,
  CONSTRAINT UNQ_SALES_PLAN
  UNIQUE (PLAN_EDESC, TIME_FRAME_CODE, START_DATE, END_DATE)
  USING INDEX UNQ_SALES_PLAN
)#
CREATE TABLE PL_SALES_PLAN_DTL
(
  PLAN_CODE            NUMBER(12)               NOT NULL,
  PLAN_DATE            DATE                     NOT NULL,
  PER_DAY_QUANTITY     NUMBER(16,4)             DEFAULT NULL,
  PER_DAY_AMOUNT       NUMBER(16,4)             DEFAULT NULL,
  ITEM_CODE            VARCHAR2(30 BYTE)        DEFAULT NULL,
  CUSTOMER_CODE        VARCHAR2(30 BYTE)        DEFAULT NULL,
  EMPLOYEE_CODE        VARCHAR2(30 BYTE)        DEFAULT NULL,
  DIVISION_CODE        VARCHAR2(30 BYTE)        DEFAULT NULL,
  FREQUENCY_JSON       VARCHAR2(500 BYTE)       DEFAULT NULL,
  SALES_PRICE_APPLIED  NUMBER(16,2)             DEFAULT NULL,
  REMARKS              VARCHAR2(400 BYTE)       DEFAULT NULL,
  COMPANY_CODE         VARCHAR2(30 BYTE),
  BRANCH_CODE          VARCHAR2(30 BYTE),
  CREATED_BY           VARCHAR2(30 BYTE),
  CREATED_DATE         DATE,
  LAST_MODIFIED_BY     VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE   DATE,
  APPROVED_FLAG        CHAR(1 BYTE),
  APPROVED_BY          VARCHAR2(30 BYTE),
  APPROVED_DATE        DATE,
  DELETED_FLAG         CHAR(1 BYTE),
  PARTY_TYPE_CODE      NVARCHAR2(30),
  CONSTRAINT UNQ_SALES_PLAN_DTL
  UNIQUE (PLAN_CODE, PLAN_DATE, ITEM_CODE, CUSTOMER_CODE, DIVISION_CODE, EMPLOYEE_CODE)
  USING INDEX UNQ_SALES_PLAN_DTL,
  CONSTRAINT FK_SALES_PLAN_DTL 
  FOREIGN KEY (PLAN_CODE) 
  REFERENCES PL_SALES_PLAN (PLAN_CODE)
)#
CREATE TABLE PL_SALES_PLAN_MAP
(
  MASTER_PLAN_CODE  NUMBER(12)                  NOT NULL,
  PLAN_CODE         NUMBER(12)                  NOT NULL,
  PARENT_PLAN_CODE  NUMBER(12)                  DEFAULT NULL,
  PLAN_FLAG         CHAR(2 BYTE)                DEFAULT 'SP'
)#
CREATE TABLE PL_TIME_FRAME
(
  TIME_FRAME_CODE     NUMBER(4)                 NOT NULL,
  TIME_FRAME_EDESC    VARCHAR2(100 BYTE)        NOT NULL,
  TIME_FRAME_NDESC    VARCHAR2(400 BYTE)        DEFAULT NULL,
  TIME_FRAME_TYPE     VARCHAR2(20 BYTE)         DEFAULT 'CALENDAR',
  DAYS                NUMBER(3)                 DEFAULT NULL,
  REMARKS             VARCHAR2(400 BYTE)        DEFAULT NULL,
  COMPANY_CODE        VARCHAR2(30 BYTE),
  CREATED_BY          VARCHAR2(30 BYTE),
  CREATED_DATE        DATE,
  LAST_MODIFIED_BY    VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE  DATE,
  APPROVED_BY         VARCHAR2(30 BYTE),
  APPROVED_DATE       DATE,
  DELETED_FLAG        CHAR(1 BYTE),
  CONSTRAINT CK_PL_TIME_FRAME_TYPE
  CHECK ( TIME_FRAME_TYPE IN ('CALENDAR', 'DAYS')),
  CONSTRAINT PK_PL_TIME_FRAME
  PRIMARY KEY
  (TIME_FRAME_CODE)
  USING INDEX PK_PL_TIME_FRAME,
  CONSTRAINT UK_PL_TIME_FRAME
  UNIQUE (TIME_FRAME_EDESC, COMPANY_CODE)
  USING INDEX UK_PL_TIME_FRAME
)#
CREATE TABLE PL_PLAN_MAP
(
  MASTER_PLAN_CODE  NUMBER(12)                  NOT NULL,
  PLAN_CODE         NUMBER(12)                  NOT NULL,
  CONSTRAINT FK_PL_PLAN_MAP1 
  FOREIGN KEY (PLAN_CODE) 
  REFERENCES PL_SALES_PLAN (PLAN_CODE)
)#
CREATE TABLE HR_EMPLOYEE_TREE
(
  EMPLOYEE_CODE         VARCHAR2(30 BYTE)       NOT NULL,
  PARENT_EMPLOYEE_CODE  VARCHAR2(30 BYTE),
  COMPANY_CODE          VARCHAR2(30 BYTE)
)#
ALTER TABLE PL_BRD_PRCMT_PLAN ADD REFERENCE_FLAG NVARCHAR2(10)
#
ALTER TABLE PL_BRD_PRCMT_PLAN ADD REFERENCE_PLAN_CODE NVARCHAR2(10)
#  
ALTER TABLE PL_MATERIAL_PLAN ADD REFERENCE_FLAG NVARCHAR2(10)
#
ALTER TABLE PL_MATERIAL_PLAN ADD REFERENCE_CODE NVARCHAR2(10)
#
 CREATE TABLE PL_EMPLOYEE_HANDOVER
( 
    HANDOVER_CODE number(10) NOT NULL,
    FROM_EMPLOYEE_CODE varchar2(50) NOT NULL,
    TO_EMPLOYEE_CODE varchar2(50) NOT NULL,
    PLAN_CODE number(10) ,
    ITEM_CODE nvarchar2(30),
    REMARKS              VARCHAR2(400 BYTE)       DEFAULT NULL,
    COMPANY_CODE         VARCHAR2(30 BYTE),
    BRANCH_CODE          VARCHAR2(30 BYTE),
    CREATED_BY           VARCHAR2(30 BYTE),
    CREATED_DATE         DATE,
    LAST_MODIFIED_BY     VARCHAR2(30 BYTE),
    LAST_MODIFIED_DATE   DATE,
    APPROVED_FLAG        CHAR(1 BYTE),
    APPROVED_BY          VARCHAR2(30 BYTE),
    APPROVED_DATE        DATE,
    DELETED_FLAG         CHAR(1 BYTE)
)
#
CREATE TABLE PL_FISCAL_YEAR_CODE
(
  FISCAL_YEAR_CODE  VARCHAR2(7 BYTE)            NOT NULL,
  START_DATE        DATE                        NOT NULL,
  END_DATE          DATE                        NOT NULL,
  EREMARKS          VARCHAR2(100 BYTE),
  NREMARKS          VARCHAR2(100 BYTE),
  COMPANY_CODE      VARCHAR2(30 BYTE)           NOT NULL,
  BRANCH_CODE       VARCHAR2(30 BYTE)           NOT NULL,
  CREATED_BY        VARCHAR2(30 BYTE)           NOT NULL,
  CREATED_DATE      DATE                        NOT NULL,
  DELETED_FLAG      CHAR(1 BYTE),
  SYN_ROWID         VARCHAR2(18 BYTE),
  MODIFY_DATE       DATE,
  MODIFY_BY         VARCHAR2(30 BYTE),
  ACTIVE            CHAR(1 BYTE),
  CONSTRAINT PK_PLFISCALYEAR_CODE
  PRIMARY KEY
  (FISCAL_YEAR_CODE, COMPANY_CODE)
)
#
ALTER TABLE PL_SALES_PLAN
  ADD CONSTRAINT UNQ_SALES_PLAN UNIQUE 
(PLAN_EDESC, TIME_FRAME_CODE, START_DATE, END_DATE,CREATED_BY);
#
ALTER TABLE PL_SALES_PLAN_DTL MODIFY PER_DAY_AMOUNT NUMBER(16,4)
#
ALTER TABLE PL_SALES_PLAN_DTL MODIFY PER_DAY_QUANTITY NUMBER(16,4)
#
ALTER TABLE PL_BRD_PRCMT_PLAN_DTL MODIFY PER_DAY_AMOUNT NUMBER(16,4)
#
ALTER TABLE PL_COA_PLAN_DTL MODIFY PER_DAY_AMOUNT NUMBER(16,4)
#
ALTER TABLE PL_SALES_PLAN_DTL ADD AGENT_CODE NVARCHAR2(30)
#
ALTER TABLE PL_PREFERENCE_SETUP ADD  SHOW_AGENT  VARCHAR2(1 BYTE) DEFAULT 'N'
#
CREATE TABLE PL_BRD_COLLECTION_PLAN
(
  PLAN_CODE            NUMBER(12)               NOT NULL,
  PLAN_EDESC           VARCHAR2(200 BYTE)       NOT NULL,
  PLAN_NDESC           VARCHAR2(400 BYTE)       DEFAULT NULL,
  EST_AMOUNT           NUMBER(16,2)             DEFAULT NULL,
  TIME_FRAME_CODE      NUMBER(4)                NOT NULL,
  CALENDAR_TYPE        VARCHAR2(3 BYTE)         DEFAULT 'LOC',
  START_DATE           DATE                     NOT NULL,
  END_DATE             DATE                     NOT NULL,
  REMARKS              VARCHAR2(400 BYTE)       DEFAULT NULL,
  COMPANY_CODE         VARCHAR2(30 BYTE),
  BRANCH_CODE          VARCHAR2(30 BYTE),
  CREATED_BY           VARCHAR2(30 BYTE),
  CREATED_DATE         DATE,
  LAST_MODIFIED_BY     VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE   DATE,
  APPROVED_FLAG        CHAR(1 BYTE)             DEFAULT 'N',
  APPROVED_BY          VARCHAR2(30 BYTE),
  APPROVED_DATE        DATE,
  DELETED_FLAG         CHAR(1 BYTE)             DEFAULT 'N',
  REFERENCE_FLAG       NVARCHAR2(10),
  REFERENCE_PLAN_CODE  NVARCHAR2(10)
)#
CREATE TABLE PL_BRD_COLLECTION_PLAN_DTL
(
  PLAN_CODE           NUMBER(12)                NOT NULL,
  PLAN_DATE           DATE                      NOT NULL,
  PER_DAY_AMOUNT      NUMBER(16,4)              DEFAULT NULL,
  ITEM_CODE           VARCHAR2(30 BYTE)         DEFAULT NULL,
  DIVISION_CODE       VARCHAR2(30 BYTE)         DEFAULT NULL,
  BRAND_CODE          VARCHAR2(30 BYTE)         DEFAULT NULL,
  FREQUENCY_JSON      VARCHAR2(500 BYTE)        DEFAULT NULL,
  REMARKS             VARCHAR2(400 BYTE)        DEFAULT NULL,
  COMPANY_CODE        VARCHAR2(30 BYTE),
  BRANCH_CODE         VARCHAR2(30 BYTE),
  PARTY_TYPE_CODE      NVARCHAR2(30),
  CREATED_BY          VARCHAR2(30 BYTE),
  CREATED_DATE        DATE,
  LAST_MODIFIED_BY    VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE  DATE,
  APPROVED_FLAG       CHAR(1 BYTE)              DEFAULT 'N',
  APPROVED_BY         VARCHAR2(30 BYTE),
  APPROVED_DATE       DATE,
  DELETED_FLAG        CHAR(1 BYTE)              DEFAULT 'N'
);#