CREATE TABLE BRD_ACTIVITY
(
  ACTIVITY_CODE         VARCHAR2(30 BYTE)       NOT NULL,
  ACTIVITY_EDESC        VARCHAR2(100 BYTE)      NOT NULL,
  ACTIVITY_NDESC        VARCHAR2(400 BYTE)      DEFAULT NULL,
  ACTIVITY_TYPE         VARCHAR2(3 BYTE),
  PARENT_ACTIVITY_CODE  NUMBER                  DEFAULT NULL,
  MASTER_ACTIVITY_CODE  VARCHAR2(20 BYTE)       DEFAULT NULL,
  PRE_ACTIVITY_CODE     VARCHAR2(20 BYTE)       DEFAULT NULL,
  GROUP_ACTIVITY_FLAG   VARCHAR2(1 BYTE)        DEFAULT 'N',
  EF1                   VARCHAR2(1 BYTE)        DEFAULT NULL,
  EF2                   VARCHAR2(1 BYTE)        DEFAULT NULL,
  REMARKS               VARCHAR2(100 BYTE)      DEFAULT NULL,
  COMPANY_CODE          VARCHAR2(30 BYTE),
  BRANCH_CODE           VARCHAR2(30 BYTE),
  CREATED_BY            VARCHAR2(30 BYTE),
  CREATED_DATE          DATE,
  LAST_MODIFIED_BY      VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE    DATE,
  APPROVED_BY           VARCHAR2(30 BYTE),
  APPROVED_DATE         DATE,
  DELETED_FLAG          CHAR(1 BYTE)
)#
CREATE TABLE BRD_CONTRACT
(
  CONTRACT_CODE           NUMBER(12)            NOT NULL,
  SUPPLIER_CODE           VARCHAR2(30 BYTE)     DEFAULT NULL,
  CUSTOMER_CODE           VARCHAR2(30 BYTE)     DEFAULT NULL,
  CONTRACT_EDESC          VARCHAR2(100 BYTE)    NOT NULL,
  CONTRACT_NDESC          VARCHAR2(400 BYTE)    NOT NULL,
  BRAND_CODE              VARCHAR2(30 BYTE)     DEFAULT NULL,
  BRANDING_TYPE           VARCHAR2(50 BYTE)     DEFAULT 'DISPLAY',
  SPROVIDER_CODE          NUMBER                DEFAULT NULL,
  START_DATE              DATE                  NOT NULL,
  END_DATE                DATE,
  AREA_CODE               VARCHAR2(30 BYTE)     DEFAULT NULL,
  CONTRACT_TYPE           VARCHAR2(20 BYTE),
  AMOUNT_TYPE             VARCHAR2(20 BYTE)     DEFAULT 'MONEY',
  AMOUNT                  INTEGER               DEFAULT NULL,
  NEXT_PAYMENT_DATE       DATE                  DEFAULT NULL,
  PAYMENT_DATE            DATE                  DEFAULT NULL,
  ADVANCE_AMOUNT          NUMBER(16,2)          DEFAULT NULL,
  CONTRACTOR_NAME         VARCHAR2(30 BYTE),
  CONTRACTOR_ADDRESS      VARCHAR2(30 BYTE),
  CONTRACTOR_EMAIL        VARCHAR2(30 BYTE),
  CONTRACTOR_PHONE        VARCHAR2(30 BYTE),
  CONTRACTOR_MOBILE       VARCHAR2(30 BYTE),
  CONTRACTOR_DESIGNATION  VARCHAR2(30 BYTE),
  CONTRACTOR_PAN_NO       VARCHAR2(30 BYTE),
  CONTRACTOR_VAT_NO       VARCHAR2(30 BYTE),
  OWNER_NAME              VARCHAR2(30 BYTE),
  OWNER_ADDRESS           VARCHAR2(30 BYTE),
  OWNER_EMAIL             VARCHAR2(30 BYTE),
  OWNER_PHONE             VARCHAR2(30 BYTE),
  OWNER_MOBILE            VARCHAR2(30 BYTE),
  OWNER_COMPANY_NAME      VARCHAR2(30 BYTE),
  OWNER_PAN_NO            VARCHAR2(30 BYTE),
  OWNER_VAT_NO            VARCHAR2(30 BYTE),
  JOB_ORDER_NO            VARCHAR2(20 BYTE)     DEFAULT NULL,
  DESCRIPTION             VARCHAR2(2000 BYTE)   DEFAULT NULL,
  CONTRACT_FILES          VARCHAR2(300 BYTE)    DEFAULT NULL,
  REMARKS                 VARCHAR2(400 BYTE)    DEFAULT NULL,
  COMPANY_CODE            VARCHAR2(30 BYTE),
  BRANCH_CODE             VARCHAR2(30 BYTE),
  CREATED_BY              VARCHAR2(30 BYTE),
  CREATED_DATE            DATE,
  LAST_MODIFIED_BY        VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE      DATE,
  APPROVED_FLAG           CHAR(1 BYTE)          DEFAULT 'N',
  APPROVED_BY             VARCHAR2(30 BYTE),
  APPROVED_DATE           DATE,
  DELETED_FLAG            CHAR(1 BYTE),
  SET_CODE                NUMBER,
  CONSTRAINT PK_BRD_ENTITY PRIMARY KEY (CONTRACT_CODE)
)#
CREATE TABLE BRD_CONTRACT_ANSWERS
(
  CONTRACT_ID   VARCHAR2(30 BYTE)               NOT NULL,
  COLUMN_NAME   VARCHAR2(255 BYTE)              NOT NULL,
  ANSWER        VARCHAR2(100 BYTE)              NOT NULL,
  QA_CODE       NUMBER                          NOT NULL,
  CREATED_BY    VARCHAR2(30 BYTE)               NOT NULL,
  CREATED_DATE  DATE                            DEFAULT SYSDATE               NOT NULL,
  DELETED_FLAG  CHAR(1 BYTE)                    DEFAULT 'N',
  COMPANY_CODE  VARCHAR2(30 BYTE),
  BRANCH_CODE   VARCHAR2(30 BYTE),
  SYNC_ID       VARCHAR2(50 BYTE)
)#
CREATE TABLE BRD_CONTRACT_AREA
(
  CONTRACT_CODE  NUMBER                         NOT NULL,
  AREA_CODE      VARCHAR2(15 BYTE)              NOT NULL,
  COMPANY_CODE   VARCHAR2(30 BYTE)              NOT NULL,
  BRANCH_CODE    VARCHAR2(30 BYTE)
)#
CREATE TABLE BRD_CONTRACT_CUSTOMER
(
  CONTRACT_CODE  NUMBER                         NOT NULL,
  CUSTOMER_CODE  VARCHAR2(30 BYTE)              DEFAULT NULL,
  COMPANY_CODE   VARCHAR2(30 BYTE)              NOT NULL,
  BRANCH_CODE    VARCHAR2(30 BYTE)
)#
CREATE TABLE BRD_CONTRACT_ITEMS
(
  CONTRACT_CODE  NUMBER                         NOT NULL,
  ITEM_CODE      VARCHAR2(30 BYTE)              NOT NULL,
  QUANTITY       VARCHAR2(10 BYTE)              NOT NULL,
  MU_CODE        VARCHAR2(5 BYTE)               NOT NULL,
  REMARKS        VARCHAR2(100 BYTE)             DEFAULT NULL,
  COMPANY_CODE   VARCHAR2(30 BYTE),
  BRANCH_CODE    VARCHAR2(30 BYTE),
  CREATED_BY     VARCHAR2(30 BYTE),
  CREATED_DATE   DATE,
  DELETED_FLAG   CHAR(1 BYTE)
)#
CREATE TABLE BRD_CONTRACT_RESELLER
(
  CONTRACT_CODE  NUMBER                         NOT NULL,
  RESELLER_CODE  VARCHAR2(15 BYTE)              NOT NULL,
  COMPANY_CODE   VARCHAR2(30 BYTE)              NOT NULL,
  BRANCH_CODE    VARCHAR2(30 BYTE)
)#
CREATE TABLE BRD_CONTRACT_SCHEME_ITEM
(
  CONTRACT_CODE  NUMBER                         NOT NULL,
  ITEM_CODE      VARCHAR2(15 BYTE)              NOT NULL,
  COMPANY_CODE   VARCHAR2(30 BYTE)              NOT NULL,
  BRANCH_CODE    VARCHAR2(30 BYTE)
)#
CREATE TABLE BRD_ROUTE_ENTITY
(
  ROUTE_CODE    VARCHAR2(4 BYTE),
  ENTITY_CODE   VARCHAR2(30 BYTE)               NOT NULL,
  ENTITY_TYPE   CHAR(1 BYTE)                    DEFAULT 'H'                   NOT NULL,
  ORDER_NO      NUMBER(10)                      NOT NULL,
  CREATED_BY    VARCHAR2(30 BYTE)               NOT NULL,
  CREATED_DATE  DATE                            DEFAULT SYSDATE               NOT NULL,
  DELETED_FLAG  CHAR(1 BYTE)                    DEFAULT 'N',
  MODIFY_DATE   DATE,
  MODIFY_BY     VARCHAR2(30 BYTE),
  COMPANY_CODE  VARCHAR2(30 BYTE)               NOT NULL,
  BRANCH_CODE   VARCHAR2(30 BYTE)
)#
CREATE TABLE BRD_SCHEME
(
  SCHEME_CODE         NUMBER                    NOT NULL,
  CONTRACT_CODE       NUMBER                    NOT NULL,
  RESELLER_CODE       VARCHAR2(50 BYTE)         DEFAULT NULL,
  EMPLOYEE_CODE       VARCHAR2(30 BYTE)         DEFAULT NULL,
  ITEM_CODE           VARCHAR2(30 BYTE),
  QUANTITY            VARCHAR2(10 BYTE)         NOT NULL,
  MU_CODE             VARCHAR2(10 BYTE)         NOT NULL,
  END_USER            CHAR(1 BYTE)              DEFAULT 'N'                   NOT NULL,
  DIVISION_CODE       VARCHAR2(30 BYTE)         DEFAULT NULL,
  BRAND_CODE          VARCHAR2(30 BYTE)         DEFAULT NULL,
  HANDOVER_DATE       DATE,
  ATTACH_DOCS         VARCHAR2(400 BYTE),
  EF1                 VARCHAR2(1 BYTE)          DEFAULT NULL,
  EF2                 VARCHAR2(1 BYTE)          DEFAULT NULL,
  CREATED_BY          VARCHAR2(30 BYTE),
  CREATED_DATE        DATE,
  LAST_MODIFIED_BY    VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE  DATE,
  APPROVED_BY         VARCHAR2(30 BYTE),
  APPROVED_DATE       DATE,
  DELETED_FLAG        CHAR(1 BYTE)              DEFAULT 'N',
  SYNC_ID             VARCHAR2(50 BYTE),
  COMPANY_CODE        VARCHAR2(30 BYTE),
  BRANCH_CODE         VARCHAR2(30 BYTE),
  CONSTRAINT PK_BRD_SCHEME PRIMARY KEY (SCHEME_CODE)
)#
CREATE TABLE BRD_SCHEME_ANSWERS
(
  SCHEME_ID      VARCHAR2(30 BYTE)              NOT NULL,
  RESELLER_CODE  VARCHAR2(50 BYTE),
  COLUMN_NAME    VARCHAR2(255 BYTE)             NOT NULL,
  ANSWER         VARCHAR2(100 BYTE)             NOT NULL,
  QA_CODE        NUMBER                         NOT NULL,
  CREATED_BY     VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_DATE   DATE                           DEFAULT SYSDATE               NOT NULL,
  DELETED_FLAG   CHAR(1 BYTE)                   DEFAULT 'N',
  COMPANY_CODE   VARCHAR2(30 BYTE),
  BRANCH_CODE    VARCHAR2(30 BYTE),
  SYNC_ID        VARCHAR2(50 BYTE)
)#
CREATE TABLE DIST_ADDRESS_MASTER
(
  ZONE_CODE      VARCHAR2(10 BYTE),
  ZONE_NAME      VARCHAR2(55 BYTE),
  DISTRICT_CODE  VARCHAR2(10 BYTE),
  DISTRICT_NAME  VARCHAR2(55 BYTE),
  VDC_CODE       VARCHAR2(10 BYTE),
  VDC_NAME       VARCHAR2(55 BYTE),
  GEO_CODE       VARCHAR2(10 BYTE),
  GEO_NAME       VARCHAR2(55 BYTE),
  REG_CODE       VARCHAR2(10 BYTE),
  REG_NAME       VARCHAR2(25 BYTE)
)#
CREATE TABLE DIST_AREA_MASTER
(
  AREA_CODE      VARCHAR2(4 BYTE)               NOT NULL,
  AREA_NAME      VARCHAR2(200 BYTE),
  ZONE_CODE      VARCHAR2(10 BYTE),
  DISTRICT_CODE  VARCHAR2(10 BYTE),
  VDC_CODE       VARCHAR2(10 BYTE),
  GEO_CODE       VARCHAR2(10 BYTE),
  REG_CODE       VARCHAR2(10 BYTE),
  COMPANY_CODE   VARCHAR2(30 BYTE)              NOT NULL,
  BRANCH_CODE    VARCHAR2(30 BYTE),
  GROUPID        NUMBER(3),
  DELETED_FLAG   VARCHAR2(1 BYTE)               DEFAULT 'N',
  CONSTRAINT PK_DIST_AREA_MST_AREA_CD PRIMARY KEY (AREA_CODE)
)#
CREATE TABLE DIST_BRANDING_ROUTE_DETAIL
(
  ROUTE_CODE    VARCHAR2(4 BYTE),
  EMP_CODE      VARCHAR2(30 BYTE),
  PLAN_CODE     NUMBER(12),
  ASSIGN_DATE   DATE,
  CREATED_DATE  DATE,
  CREATED_BY    VARCHAR2(30 BYTE),
  APPROVE_DATE  DATE,
  APPROVE_BY    VARCHAR2(30 BYTE),
  MODIFY_DATE   DATE,
  MODIFY_BY     VARCHAR2(30 BYTE),
  DELETED_FLAG  CHAR(1 BYTE)                    DEFAULT 'N',
  COMPANY_CODE  VARCHAR2(30 BYTE),
  BRANCH_CODE   VARCHAR2(30 BYTE)
)#
CREATE TABLE DIST_COLLECTION
(
  SP_CODE                VARCHAR2(30 BYTE)      NOT NULL,
  ENTITY_CODE            VARCHAR2(30 BYTE),
  ENTITY_TYPE            CHAR(1 BYTE)           NOT NULL,
  BILL_NO                VARCHAR2(50 BYTE),
  CHEQUE_NO              VARCHAR2(50 BYTE),
  CHEQUE_DEPOSIT_BANK    VARCHAR2(50 BYTE),
  BANK_NAME              VARCHAR2(50 BYTE),
  AMOUNT                 NUMBER,
  PAYMENT_MODE           VARCHAR2(20 BYTE),
  CHEQUE_CLEARANCE_DATE  DATE,
  LATITUDE               VARCHAR2(20 BYTE),
  LONGITUDE              VARCHAR2(20 BYTE),
  REMARKS                VARCHAR2(200 BYTE),
  OTP_CODE               VARCHAR2(30 BYTE),
  CREATED_BY             VARCHAR2(30 BYTE)      NOT NULL,
  CREATED_DATE           DATE                   DEFAULT SYSDATE               NOT NULL,
  MODIFY_BY              VARCHAR2(30 BYTE),
  MODIFY_DATE            DATE,
  DELETED_FLAG           CHAR(1 BYTE)           DEFAULT 'N',
  COMPANY_CODE           VARCHAR2(30 BYTE)      NOT NULL,
  BRANCH_CODE            VARCHAR2(30 BYTE)      NOT NULL,
  SYNC_ID                VARCHAR2(50 BYTE),
  CONSTRAINT CK_DIST_COL_ENT_TYP CHECK ( ENTITY_TYPE IN ('P', 'D', 'R'))
)#
CREATE TABLE DIST_COLLECTION_DETAIL
(
  BILL_NO        VARCHAR2(50 BYTE),
  DIVISION_CODE  VARCHAR2(30 BYTE),
  AMOUNT         NUMBER,
  DELETED_FLAG   CHAR(1 BYTE)                   DEFAULT 'N',
  CREATED_DATE   DATE,
  CREATED_BY     VARCHAR2(50 BYTE),
  COMPANY_CODE   VARCHAR2(30 BYTE),
  BRANCH_CODE    VARCHAR2(30 BYTE)
)#
CREATE TABLE DIST_COMP_FIELDS
(
  FIELD_ID       NUMBER(5)                      NOT NULL,
  ITEM_CODE      NUMBER(5)                      NOT NULL,
  COL_NAME       VARCHAR2(30 BYTE),
  COL_DATA_TYPE  CHAR(3 BYTE),
  CREATED_BY     VARCHAR2(30 BYTE),
  CREATED_DATE   DATE,
  COMPANY_CODE   VARCHAR2(30 BYTE),
  SYNC_ID        VARCHAR2(50 BYTE),
  CONSTRAINT CHK_COMP_FIELD_DATA_TYPE CHECK (COL_DATA_TYPE IN ('NUM', 'TXT', 'BOL'))
)#
CREATE TABLE DIST_COMP_ITEM_MASTER
(
  ITEM_ID        NUMBER(5)                      NOT NULL,
  ITEM_EDESC     VARCHAR2(30 BYTE)       UNIQUE       NOT NULL,
  RATE           NUMBER(16,4),
  UNIT           VARCHAR2(8 BYTE),
  DELETED_FLAG   CHAR(1 BYTE)                   DEFAULT 'N',
  CREATED_BY     VARCHAR2(30 BYTE),
  CREATED_DATE   DATE,
  MODIFIED_BY    VARCHAR2(30 BYTE),
  MODIFIED_DATE  DATE,
  COMPANY_CODE   VARCHAR2(30 BYTE),
  BRANCH_CODE    VARCHAR2(30 BYTE),
  SYNC_ID        VARCHAR2(50 BYTE),
  ITEM_CATEGORY  VARCHAR2(30 BYTE),
  CONSTRAINT PK_COMP_ITEM PRIMARY KEY (ITEM_ID)
)#
CREATE TABLE DIST_COMP_QA
(
  ENTITY_CODE     VARCHAR2(50 BYTE)             NOT NULL,
  ENTITY_TYPE     CHAR(1 BYTE)                  NOT NULL,
  ITEM_CODE       NUMBER(5)                     NOT NULL,
  COMP_ITEM_CODE  NUMBER(5)                     NOT NULL,
  QUESTION_ID     NUMBER(5)                     NOT NULL,
  ANSWER          VARCHAR2(50 BYTE),
  LATITUDE        VARCHAR2(20 BYTE),
  LONGITUDE       VARCHAR2(20 BYTE),
  COMPANY_CODE    VARCHAR2(30 BYTE)             NOT NULL,
  BRANCH_CODE     VARCHAR2(30 BYTE),
  CREATED_BY      VARCHAR2(20 BYTE),
  CREATED_DATE    DATE,
  SYNC_ID         VARCHAR2(50 BYTE),
  CONSTRAINT CHK_COMP_QA_ENT_TYPE CHECK (ENTITY_TYPE IN ('R','D','P','B','O'))
)#
CREATE TABLE DIST_DEALER_MASTER
(
  DEALER_CODE         VARCHAR2(30 BYTE)         NOT NULL,
  AREA_CODE           VARCHAR2(4 BYTE)          NOT NULL,
  REG_OFFICE_ADDRESS  VARCHAR2(100 BYTE),
  CONTACT_NO          VARCHAR2(50 BYTE),
  EMAIL               VARCHAR2(50 BYTE),
  PAN_NO              VARCHAR2(50 BYTE),
  VAT_NO              VARCHAR2(50 BYTE),
  LATITUDE            VARCHAR2(20 BYTE),
  LONGITUDE           VARCHAR2(20 BYTE),
  WEIGHT              NUMBER(7)                 DEFAULT 0                     NOT NULL,
  CREATED_BY          NUMBER(5),
  LUPDATE_BY          NUMBER(5),
  CREATED_DATE        DATE,
  LUPDATE_DATE        DATE,
  ACTIVE              CHAR(1 BYTE)              DEFAULT 'Y',
  COMPANY_CODE        VARCHAR2(30 BYTE)         NOT NULL,
  BRANCH_CODE         VARCHAR2(30 BYTE),
  SYNC_ID             VARCHAR2(50 BYTE),
  DELETED_FLAG        CHAR(1 BYTE)              DEFAULT 'N'                   NOT NULL
)#
CREATE TABLE DIST_DEALER_STOCK
(
  DEALER_CODE    VARCHAR2(30 BYTE)              NOT NULL,
  ITEM_CODE      VARCHAR2(30 BYTE)              NOT NULL,
  MU_CODE        VARCHAR2(5 BYTE)               NOT NULL,
  CURRENT_STOCK  NUMBER(5)                      NOT NULL,
  PURCHASE_QTY   NUMBER(5),
  SP_CODE        VARCHAR2(30 BYTE)              NOT NULL,
  DELETED_FLAG   CHAR(1 BYTE)                   DEFAULT 'N',
  CREATED_DATE   DATE                           DEFAULT SYSDATE               NOT NULL,
  COMPANY_CODE   VARCHAR2(30 BYTE)              NOT NULL,
  BRANCH_CODE    VARCHAR2(30 BYTE),
  SYNC_ID        VARCHAR2(50 BYTE)
)#
CREATE TABLE DIST_DISTRIBUTOR_ITEM
(
  DISTRIBUTOR_CODE  VARCHAR2(30 BYTE)           NOT NULL,
  ITEM_CODE         VARCHAR2(30 BYTE)           NOT NULL,
  CREATED_BY        VARCHAR2(30 BYTE)           NOT NULL,
  CREATED_DATE      DATE                        DEFAULT SYSDATE               NOT NULL,
  DELETED_FLAG      CHAR(1 BYTE)                DEFAULT 'N',
  MODIFY_DATE       DATE,
  MODIFY_BY         VARCHAR2(30 BYTE),
  COMPANY_CODE      VARCHAR2(30 BYTE)           NOT NULL,
  BRANCH_CODE       VARCHAR2(30 BYTE),
  CONSTRAINT PK_DIST_DIST_ITEM_CD PRIMARY KEY (DISTRIBUTOR_CODE, ITEM_CODE, COMPANY_CODE)
)#
CREATE TABLE DIST_DISTRIBUTOR_MASTER
(
  DISTRIBUTOR_CODE    VARCHAR2(30 BYTE)         NOT NULL,
  AREA_CODE           VARCHAR2(4 BYTE)          NOT NULL,
  REG_OFFICE_ADDRESS  VARCHAR2(100 BYTE),
  CONTACT_NO          VARCHAR2(50 BYTE),
  GROUPID             NUMBER(3),
  EMAIL               VARCHAR2(50 BYTE),
  PAN_NO              VARCHAR2(50 BYTE),
  VAT_NO              VARCHAR2(50 BYTE),
  LATITUDE            VARCHAR2(20 BYTE),
  LONGITUDE           VARCHAR2(20 BYTE),
  WEIGHT              NUMBER(7)                 DEFAULT 0                     NOT NULL,
  CREATED_BY          NUMBER(5),
  LUPDATE_BY          NUMBER(5),
  CREATED_DATE        DATE,
  LUPDATE_DATE        DATE,
  ACTIVE              CHAR(1 BYTE)              DEFAULT 'Y',
  COMPANY_CODE        VARCHAR2(30 BYTE)         NOT NULL,
  BRANCH_CODE         VARCHAR2(30 BYTE),
  SYNC_ID             VARCHAR2(50 BYTE),
  DELETED_FLAG        VARCHAR2(1 BYTE)          DEFAULT 'N',
  CONSTRAINT PK_DIST_MST_DIST_CD PRIMARY KEY (DISTRIBUTOR_CODE)
)#
CREATE TABLE DIST_DISTRIBUTOR_OPENINGSTOCK
(
  DISTRIBUTOR_CODE  VARCHAR2(30 BYTE)           NOT NULL,
  ITEM_CODE         VARCHAR2(30 BYTE)           NOT NULL,
  MU_CODE           VARCHAR2(5 BYTE)            NOT NULL,
  CURRENT_STOCK     NUMBER(5)                   NOT NULL,
  PURCHASE_QTY      NUMBER(5),
  SP_CODE           VARCHAR2(30 BYTE),
  DELETED_FLAG      CHAR(1 BYTE)                DEFAULT 'N',
  CREATED_DATE      DATE                        DEFAULT SYSDATE               NOT NULL,
  COMPANY_CODE      VARCHAR2(30 BYTE)           NOT NULL,
  BRANCH_CODE       VARCHAR2(30 BYTE),
  SYNC_ID           VARCHAR2(50 BYTE)
)#
CREATE TABLE DIST_DISTRIBUTOR_OPENING_STOCK
(
  OPENING_STOCK_ID  NUMBER(5)                   NOT NULL,
  DISTRIBUTOR_CODE  VARCHAR2(30 BYTE)           NOT NULL,
  ITEM_CODE         VARCHAR2(30 BYTE)           NOT NULL,
  MU_CODE           VARCHAR2(5 BYTE)            NOT NULL,
  CURRENT_STOCK     NUMBER(5)                   NOT NULL,
  PURCHASE_QTY      NUMBER(5),
  SP_CODE           VARCHAR2(30 BYTE),
  DELETED_FLAG      CHAR(1 BYTE)                DEFAULT 'N',
  CREATED_DATE      DATE                        DEFAULT SYSDATE               NOT NULL,
  COMPANY_CODE      VARCHAR2(30 BYTE)           NOT NULL,
  BRANCH_CODE       VARCHAR2(30 BYTE),
  SYNC_ID           VARCHAR2(50 BYTE)
)#
CREATE TABLE DIST_DISTRIBUTOR_STOCK
(
  DISTRIBUTOR_CODE  VARCHAR2(30 BYTE)           NOT NULL,
  ITEM_CODE         VARCHAR2(30 BYTE)           NOT NULL,
  MU_CODE           VARCHAR2(5 BYTE)            NOT NULL,
  CURRENT_STOCK     NUMBER(5)                   NOT NULL,
  PURCHASE_QTY      NUMBER(5),
  SP_CODE           VARCHAR2(30 BYTE)           NOT NULL,
  DELETED_FLAG      CHAR(1 BYTE)                DEFAULT 'N',
  CREATED_DATE      DATE                        DEFAULT SYSDATE               NOT NULL,
  COMPANY_CODE      VARCHAR2(30 BYTE)           NOT NULL,
  BRANCH_CODE       VARCHAR2(30 BYTE),
  SYNC_ID           VARCHAR2(50 BYTE),
  STOCK_ID          NUMBER(5)
)#
CREATE TABLE DIST_EOD_UPDATE
(
  SP_CODE            VARCHAR2(30 BYTE)          NOT NULL,
  PO_DCOUNT          NUMBER(5)                  DEFAULT 0,
  PO_RCOUNT          NUMBER(5)                  DEFAULT 0,
  RES_MASTER         NUMBER(5)                  DEFAULT 0,
  RES_DETAIL         NUMBER(5)                  DEFAULT 0,
  RES_ENTITY         NUMBER(5)                  DEFAULT 0,
  RES_STORE_PHOTO    NUMBER(5)                  DEFAULT 0,
  RES_CONTACT_PHOTO  NUMBER(5)                  DEFAULT 0,
  LATITUDE           VARCHAR2(30 BYTE)          NOT NULL,
  LONGITUDE          VARCHAR2(30 BYTE)          NOT NULL,
  REMARKS            VARCHAR2(200 BYTE),
  CREATED_DATE       DATE                       NOT NULL,
  CREATED_BY         NUMBER                     NOT NULL,
  COMPANY_CODE       VARCHAR2(30 BYTE)          NOT NULL,
  BRANCH_CODE        VARCHAR2(30 BYTE)
)#
CREATE TABLE DIST_EXTRA_ACTIVITY
(
  SP_CODE       VARCHAR2(30 BYTE)               NOT NULL,
  VISIT_DATE    DATE                            DEFAULT SYSDATE,
  LATITUDE      VARCHAR2(20 BYTE)               NOT NULL,
  LONGITUDE     VARCHAR2(20 BYTE)               NOT NULL,
  REMARKS       VARCHAR2(255 BYTE)              NOT NULL,
  COMPANY_CODE  VARCHAR2(30 BYTE)               NOT NULL,
  BRANCH_CODE   VARCHAR2(30 BYTE),
  SYNC_ID       VARCHAR2(50 BYTE)
)#
CREATE TABLE DIST_GROUP_MAPPING
(
  GROUPID         NUMBER(3)                     NOT NULL,
  MAPPED_GROUPID  NUMBER(3)                     NOT NULL,
  COMPANY_CODE    VARCHAR2(3 BYTE),
  DELETED_FLAG    CHAR(1 BYTE)                  DEFAULT 'N'                   NOT NULL,
  CREATED_BY      VARCHAR2(20 BYTE),
  CREATED_DATE    DATE,
  CONSTRAINT PK_GROUP_MAP PRIMARY KEY (GROUPID, MAPPED_GROUPID)
)#
CREATE TABLE DIST_GROUP_MASTER
(
  GROUPID       NUMBER(3)                       NOT NULL,
  GROUP_CODE    VARCHAR2(10 BYTE)               NOT NULL,
  GROUP_EDESC   VARCHAR2(100 BYTE)              NOT NULL,
  CREATED_BY    VARCHAR2(30 BYTE)               NOT NULL,
  CREATED_DATE  DATE                            DEFAULT SYSDATE               NOT NULL,
  DELETED_FLAG  CHAR(1 BYTE)                    DEFAULT 'N',
  MODIFY_DATE   DATE,
  MODIFY_BY     VARCHAR2(30 BYTE),
  COMPANY_CODE  VARCHAR2(30 BYTE)               NOT NULL,
  BRANCH_CODE   VARCHAR2(30 BYTE),
  CONSTRAINT PK_DIST_GRP_MST_GPID PRIMARY KEY (GROUPID, COMPANY_CODE)
)#
CREATE TABLE DIST_IMAGE_CATEGORY
(
  CATEGORYID      NUMBER(15)                    NOT NULL,
  CATEGORY_CODE   VARCHAR2(10 BYTE)             NOT NULL,
  CATEGORY_EDESC  VARCHAR2(100 BYTE)            NOT NULL,
  MAX_ITEMS       NUMBER,
  CREATED_BY      VARCHAR2(30 BYTE)             NOT NULL,
  CREATED_DATE    DATE                          DEFAULT SYSDATE               NOT NULL,
  DELETED_FLAG    CHAR(1 BYTE)                  DEFAULT 'N',
  MODIFY_DATE     DATE,
  MODIFY_BY       VARCHAR2(30 BYTE),
  COMPANY_CODE    VARCHAR2(30 BYTE)             NOT NULL,
  BRANCH_CODE     VARCHAR2(30 BYTE),
  CONSTRAINT PK_DIST_IMG_CTG_CTGID PRIMARY KEY (CATEGORYID, COMPANY_CODE)
)#
CREATE TABLE DIST_IP_SSD_CLOSING_STOCK
(
  VOUCHER_NO     NUMBER(10)                     NOT NULL,
  CLOSING_DATE   DATE                           NOT NULL,
  CUSTOMER_CODE  VARCHAR2(30 BYTE)              NOT NULL,
  ITEM_CODE      VARCHAR2(30 BYTE)              NOT NULL,
  MU_CODE        VARCHAR2(5 BYTE)               NOT NULL,
  BALANCE_QTY    NUMBER(15,2),
  PARTICULARS    VARCHAR2(200 BYTE),
  CREATED_BY     VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_DATE   DATE                           NOT NULL,
  DELETED_FLAG   CHAR(1 BYTE),
  CURRENCY_CODE  VARCHAR2(3 BYTE),
  EXCHANGE_RATE  NUMBER,
  SYN_ROWID      VARCHAR2(18 BYTE),
  MODIFY_DATE    DATE,
  MODIFY_BY      VARCHAR2(30 BYTE),
  REMARKS        VARCHAR2(200 BYTE),
  COMPANY_CODE   VARCHAR2(30 BYTE)              NOT NULL,
  BRANCH_CODE    VARCHAR2(30 BYTE)              NOT NULL
)#
CREATE TABLE DIST_IP_SSD_PURCHASE_ORDER
(
  ORDER_NO               NUMBER(10)             NOT NULL,
  ORDER_DATE             DATE                   NOT NULL,
  CUSTOMER_CODE          VARCHAR2(30 BYTE)      NOT NULL,
  ITEM_CODE              VARCHAR2(30 BYTE)      NOT NULL,
  MU_CODE                VARCHAR2(5 BYTE),
  QUANTITY               NUMBER(15,2),
  UNIT_PRICE             NUMBER(15,2),
  TOTAL_PRICE            NUMBER(15,2),
  PARTY_TYPE_CODE        VARCHAR2(5 BYTE),
  BILLING_CUSTOMER_CODE  VARCHAR2(30 BYTE),
  BILLING_NAME           VARCHAR2(100 BYTE),
  CITY_CODE              VARCHAR2(8 BYTE),
  SALES_TYPE_CODE        VARCHAR2(5 BYTE),
  SHIPPING_CONTACT       VARCHAR2(50 BYTE),
  REMARKS                VARCHAR2(200 BYTE),
  ORDER_FROM             CHAR(1 BYTE)           DEFAULT 'R'                   NOT NULL,
  REMARKS_REVIEW         VARCHAR2(500 BYTE),
  APPROVE_QTY            NUMBER(15,2),
  APPROVE_AMT            NUMBER(15,2),
  SALES_ORDER_NO         VARCHAR2(20 BYTE),
  CREATED_BY             VARCHAR2(30 BYTE)      NOT NULL,
  CREATED_DATE           DATE                   NOT NULL,
  CURRENCY_CODE          VARCHAR2(3 BYTE),
  EXCHANGE_RATE          NUMBER,
  APPROVED_FLAG          CHAR(1 BYTE)           DEFAULT 'N'                   NOT NULL,
  DISPATCH_FLAG          CHAR(1 BYTE)           DEFAULT 'N'                   NOT NULL,
  ACKNOWLEDGE_FLAG       CHAR(1 BYTE)           DEFAULT 'N'                   NOT NULL,
  REJECT_FLAG            CHAR(1 BYTE)           DEFAULT 'N'                   NOT NULL,
  DELETED_FLAG           CHAR(1 BYTE)           DEFAULT 'N'                   NOT NULL,
  SYN_ROWID              VARCHAR2(18 BYTE),
  MODIFY_DATE            DATE,
  MODIFY_BY              VARCHAR2(30 BYTE),
  COMPANY_CODE           VARCHAR2(30 BYTE)      NOT NULL,
  BRANCH_CODE            VARCHAR2(30 BYTE)      NOT NULL,
  SYNC_ID                VARCHAR2(50 BYTE),
  TEMP_ORDER_NO          VARCHAR2(50 BYTE),
  WHOLESELLER_CODE       VARCHAR2(30 BYTE),
  CONSTRAINT CK_DIST_IP_SSD_PUR_ORD_ORD_FRM CHECK ( ORDER_FROM IN ('O', 'S', 'P', 'D', 'W', 'R')),
  CONSTRAINT PK_DIST_IP_SSD_PUR_ORD_ORD_ITM PRIMARY KEY (ORDER_NO, CUSTOMER_CODE, ITEM_CODE)
)#
CREATE TABLE DIST_IP_SSR_CLOSING_STOCK
(
  VOUCHER_NO     NUMBER(10)                     NOT NULL,
  CLOSING_DATE   DATE                           NOT NULL,
  RESELLER_CODE  VARCHAR2(30 BYTE)              NOT NULL,
  ITEM_CODE      VARCHAR2(30 BYTE)              NOT NULL,
  MU_CODE        VARCHAR2(5 BYTE)               NOT NULL,
  BALANCE_QTY    NUMBER(15,2),
  PARTICULARS    VARCHAR2(200 BYTE),
  CREATED_BY     VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_DATE   DATE                           NOT NULL,
  DELETED_FLAG   CHAR(1 BYTE)                   DEFAULT 'N',
  CURRENCY_CODE  VARCHAR2(3 BYTE),
  EXCHANGE_RATE  NUMBER,
  SYN_ROWID      VARCHAR2(18 BYTE),
  MODIFY_DATE    DATE,
  MODIFY_BY      VARCHAR2(30 BYTE),
  COMPANY_CODE   VARCHAR2(30 BYTE)              NOT NULL,
  BRANCH_CODE    VARCHAR2(30 BYTE)              NOT NULL
)#
CREATE TABLE DIST_IP_SSR_PURCHASE_ORDER
(
  ORDER_NO               NUMBER(10)             NOT NULL,
  ORDER_DATE             DATE                   NOT NULL,
  RESELLER_CODE          VARCHAR2(30 BYTE)      NOT NULL,
  CUSTOMER_CODE          VARCHAR2(30 BYTE)      NOT NULL,
  ITEM_CODE              VARCHAR2(30 BYTE)      NOT NULL,
  MU_CODE                VARCHAR2(5 BYTE),
  QUANTITY               NUMBER(15,2),
  UNIT_PRICE             NUMBER(15,2),
  TOTAL_PRICE            NUMBER(15,2),
  PARTY_TYPE_CODE        VARCHAR2(5 BYTE),
  BILLING_CUSTOMER_CODE  VARCHAR2(30 BYTE),
  BILLING_NAME           VARCHAR2(100 BYTE),
  CITY_CODE              VARCHAR2(8 BYTE),
  SALES_TYPE_CODE        VARCHAR2(5 BYTE),
  SHIPPING_CONTACT       VARCHAR2(50 BYTE),
  REMARKS                VARCHAR2(200 BYTE),
  DISPATCH_FROM          CHAR(1 BYTE)           NOT NULL,
  REMARKS_REVIEW         VARCHAR2(500 BYTE),
  APPROVE_QTY            NUMBER(15,2),
  APPROVE_AMT            NUMBER(15,2),
  SALES_ORDER_NO         VARCHAR2(20 BYTE),
  CREATED_BY             VARCHAR2(30 BYTE)      NOT NULL,
  CREATED_DATE           DATE                   NOT NULL,
  CURRENCY_CODE          VARCHAR2(3 BYTE),
  EXCHANGE_RATE          NUMBER,
  APPROVED_FLAG          CHAR(1 BYTE)           DEFAULT 'N'                   NOT NULL,
  DISPATCH_FLAG          CHAR(1 BYTE)           DEFAULT 'N'                   NOT NULL,
  ACKNOWLEDGE_FLAG       CHAR(1 BYTE)           DEFAULT 'N'                   NOT NULL,
  REJECT_FLAG            CHAR(1 BYTE)           DEFAULT 'N'                   NOT NULL,
  DELETED_FLAG           CHAR(1 BYTE)           DEFAULT 'N'                   NOT NULL,
  SYN_ROWID              VARCHAR2(18 BYTE),
  MODIFY_DATE            DATE,
  MODIFY_BY              VARCHAR2(30 BYTE),
  COMPANY_CODE           VARCHAR2(30 BYTE)      NOT NULL,
  BRANCH_CODE            VARCHAR2(30 BYTE)      NOT NULL,
  SYNC_ID                VARCHAR2(50 BYTE),
  TEMP_ORDER_NO          VARCHAR2(50 BYTE),
  WHOLESELLER_CODE       VARCHAR2(30 BYTE),
  CONSTRAINT CK_DIST_IP_SSR_PUR_ORD_DIS_FRM CHECK ( DISPATCH_FROM IN ('P', 'D', 'W', 'R')),
  CONSTRAINT PK_DIST_IP_SSR_PUR_ORD PRIMARY KEY (ORDER_NO, RESELLER_CODE, CUSTOMER_CODE, ITEM_CODE)
)#
CREATE TABLE DIST_LM_LOCATION_TRACKING
(
  SP_CODE       VARCHAR2(30 BYTE),
  SUBMIT_DATE   DATE                            DEFAULT SYSDATE,
  LATITUDE      VARCHAR2(20 BYTE),
  LONGITUDE     VARCHAR2(20 BYTE),
  TRACK_TYPE    CHAR(3 BYTE)                    DEFAULT 'TRK'                 NOT NULL,
  COMPANY_CODE  VARCHAR2(30 BYTE),
  BRANCH_CODE   VARCHAR2(30 BYTE),
  SYNC_ID       VARCHAR2(50 BYTE),
  CONSTRAINT CK_DIST_LM_LOC_TRK_TRK_TYP CHECK ( TRACK_TYPE IN ('ATN', 'TRK', 'EOD'))
)#
CREATE TABLE DIST_LOCATION_TRACK
(
  SP_CODE        VARCHAR2(30 BYTE),
  UPDATE_DATE    DATE                           DEFAULT SYSDATE               NOT NULL,
  LATITUDE       VARCHAR2(20 BYTE)              NOT NULL,
  LONGITUDE      VARCHAR2(20 BYTE)              NOT NULL,
  CUSTOMER_CODE  VARCHAR2(30 BYTE),
  CUSTOMER_TYPE  CHAR(1 BYTE),
  DESTINATION    VARCHAR2(255 BYTE)             NOT NULL,
  MAC_ADDRESS    VARCHAR2(30 BYTE),
  IS_VISITED     VARCHAR2(1 BYTE),
  REMARKS        VARCHAR2(255 BYTE),
  ROUTE_CODE     VARCHAR2(4 BYTE),
  COMPANY_CODE   VARCHAR2(30 BYTE)              NOT NULL,
  BRANCH_CODE    VARCHAR2(30 BYTE),
  SYNC_ID        VARCHAR2(50 BYTE)
)#
CREATE TABLE DIST_LOGIN_DEVICE
(
  USERID          NUMBER(5)                     NOT NULL,
  IMEI_NO         VARCHAR2(100 BYTE)            NOT NULL,
  DEVICE_NAME     VARCHAR2(100 BYTE),
  APPROVED_FLAG   CHAR(1 BYTE)                  DEFAULT 'N',
  ACTIVE          CHAR(1 BYTE)                  DEFAULT 'N',
  CREATED_BY      VARCHAR2(30 BYTE),
  CREATED_DATE    DATE                          DEFAULT SYSDATE,
  UPDATED_BY      VARCHAR2(30 BYTE),
  UPDATED_DATE    DATE,
  APP_VERSION     VARCHAR2(10 BYTE),
  FIREBASE_ID     VARCHAR2(200 BYTE),
  CURRENT_LOGIN   CHAR(1 BYTE)                  DEFAULT 'N',
  INSTALLED_APPS  VARCHAR2(500 BYTE)
)#
CREATE TABLE DIST_USER_DEVICE_LOG
(
  SP_CODE VARCHAR(50 BYTE) NOT NULL,
  SWITCH_STATUS VARCHAR(3 BYTE) NOT NULL,
  CREATED_DATE DATE DEFAULT SYSDATE,
  BATTERY_PERCENT NUMBER(3),
  COMPANY_CODE VARCHAR(2 BYTE),
  BRANCH_CODE VARCHAR(2 BYTE),
  SYNC_ID       VARCHAR2(50 BYTE),
  CONSTRAINT CHK_DEVICE_LOG_SWITCH CHECK (SWITCH_STATUS IN ('ON','OFF'))
 )#
CREATE TABLE DIST_LOGIN_HISTORY
(
  USERID          NUMBER(5),
  LOGIN_DATE      DATE,
  WORKSTATION_ID  VARCHAR2(80 BYTE),
  COMPANY_CODE    VARCHAR2(30 BYTE)             NOT NULL,
  BRANCH_CODE     VARCHAR2(30 BYTE)
)#
CREATE TABLE DIST_LOGIN_USER
(
  USERID            NUMBER(5)                   NOT NULL,
  USER_NAME         VARCHAR2(50 BYTE)           NOT NULL,
  PASS_WORD         VARCHAR2(50 BYTE)           NOT NULL,
  FULL_NAME         VARCHAR2(100 BYTE),
  SP_CODE           VARCHAR2(30 BYTE),
  CONTACT_NO        VARCHAR2(50 BYTE),
  LINK_SYN_USER_NO  NUMBER(6),
  USER_TYPE         CHAR(1 BYTE),
  GROUPID           NUMBER(3),
  SUPER_USER        CHAR(1 BYTE)                DEFAULT 'N',
  IS_MOBILE         CHAR(1 BYTE)                DEFAULT 'N',
  ATTENDANCE        CHAR(1 BYTE)                DEFAULT 'N',
  ACTIVE            CHAR(1 BYTE)                DEFAULT 'Y',
  PASSWORD_CHANGE   CHAR(1 BYTE)                DEFAULT 'Y',
  CREATED_BY        VARCHAR2(30 BYTE),
  CREATED_DATE      DATE,
  LUPDATE_BY        NUMBER(5),
  LUPDATE_DATE      DATE,
  EXPIRY_DATE       DATE,
  PARENT_USERID     NUMBER(5),
  EMAIL             VARCHAR2(50 BYTE),
  COMPANY_CODE      VARCHAR2(30 BYTE),
  BRANCH_CODE       VARCHAR2(30 BYTE),
  AREA_CODE         VARCHAR2(4 BYTE),
  BRANDING          CHAR(1 BYTE)                DEFAULT 'N',
  CONSTRAINT PK_DIST_LOGIN_USR_USR_ID PRIMARY KEY (USERID),
  CONSTRAINT UK_DIST_LOGIN_USR_USR_NAME UNIQUE (USER_NAME)
)#
CREATE TABLE DIST_MITI_MASTER
(
  MITI_YEAR  NUMBER(4)                          NOT NULL,
  E_DATE     DATE                               NOT NULL,
  MITI_1     NUMBER(2)                          NOT NULL,
  MITI_2     NUMBER(2)                          NOT NULL,
  MITI_3     NUMBER(2)                          NOT NULL,
  MITI_4     NUMBER(2)                          NOT NULL,
  MITI_5     NUMBER(2)                          NOT NULL,
  MITI_6     NUMBER(2)                          NOT NULL,
  MITI_7     NUMBER(2)                          NOT NULL,
  MITI_8     NUMBER(2)                          NOT NULL,
  MITI_9     NUMBER(2)                          NOT NULL,
  MITI_10    NUMBER(2)                          NOT NULL,
  MITI_11    NUMBER(2)                          NOT NULL,
  MITI_12    NUMBER(2)                          NOT NULL,
  CONSTRAINT PK_DIST_MITI_MST_MITI_YR PRIMARY KEY (MITI_YEAR)
)#
CREATE TABLE DIST_MKT_INFO
(
  MKT_CODE      NUMBER(10)                      NOT NULL,
  INFO_TEXT     VARCHAR2(200 BYTE)              NOT NULL,
  ENTITY_TYPE   VARCHAR2(1 BYTE),
  ENTITY_CODE   VARCHAR2(30 BYTE)               NOT NULL,
  USER_ID       NUMBER                          NOT NULL,
  CREATE_DATE   DATE                            NOT NULL,
  COMPANY_CODE  VARCHAR2(30 BYTE)               NOT NULL,
  BRANCH_CODE   VARCHAR2(30 BYTE),
  SYNC_ID       VARCHAR2(50 BYTE),
  CONSTRAINT FK_DIST_MKT_INFO_USR_ID FOREIGN KEY (USER_ID) REFERENCES DIST_LOGIN_USER (USERID)
)#
CREATE TABLE DIST_MODULE_MASTER_SETUP
(
  MODULE_CODE   NUMBER(2)                       NOT NULL,
  MODULE_NAME   VARCHAR2(100 BYTE)              NOT NULL,
  PARENT_CODE   VARCHAR2(3 BYTE),
  ORDER_NO      NUMBER,
  ACTIVE        CHAR(1 BYTE)                    DEFAULT 'Y',
  COMPANY_CODE  VARCHAR2(30 BYTE),
  BRANCH_CODE   VARCHAR2(30 BYTE),
  CONSTRAINT PK_DIST_MOD_MST_SETUP_MOD_CD PRIMARY KEY (MODULE_CODE)
)#
CREATE TABLE DIST_NOTIFICATIONS
(
  NOTIFICATION_ID     NUMBER(5),
  NOTIFICATION_TITLE  VARCHAR2(50 BYTE),
  NOTIFICATION_TEXT   VARCHAR2(500 BYTE),
  NOTIFICATION_TYPE   VARCHAR2(50 BYTE),
  SP_CODE             VARCHAR2(30 BYTE),
  DELETED_FLAG        CHAR(1 BYTE)              DEFAULT 'N',
  STATUS              CHAR(1 BYTE)              DEFAULT 'A',
  COMPANY_CODE        VARCHAR2(30 BYTE),
  BRANCH_CODE         VARCHAR2(30 BYTE)
)#
CREATE TABLE DIST_OUTLET_SUBTYPE
(
  SUBTYPE_ID     NUMBER                         NOT NULL,
  SUBTYPE_CODE   VARCHAR2(10 BYTE)              NOT NULL,
  SUBTYPE_EDESC  VARCHAR2(100 BYTE)             NOT NULL,
  TYPE_ID        VARCHAR2(10 BYTE)              NOT NULL,
  CREATED_BY     VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_DATE   DATE                           DEFAULT SYSDATE               NOT NULL,
  DELETED_FLAG   CHAR(1 BYTE)                   DEFAULT 'N',
  MODIFY_DATE    DATE,
  MODIFY_BY      VARCHAR2(30 BYTE),
  COMPANY_CODE   VARCHAR2(30 BYTE)              NOT NULL,
  BRANCH_CODE    VARCHAR2(30 BYTE)
)#
CREATE TABLE DIST_OUTLET_TYPE
(
  TYPE_ID       NUMBER                          NOT NULL,
  TYPE_CODE     VARCHAR2(10 BYTE)               NOT NULL,
  TYPE_EDESC    VARCHAR2(100 BYTE)              NOT NULL,
  CREATED_BY    VARCHAR2(30 BYTE)               NOT NULL,
  CREATED_DATE  DATE                            DEFAULT SYSDATE               NOT NULL,
  DELETED_FLAG  CHAR(1 BYTE)                    DEFAULT 'N',
  MODIFY_DATE   DATE,
  MODIFY_BY     VARCHAR2(30 BYTE),
  COMPANY_CODE  VARCHAR2(30 BYTE)               NOT NULL,
  BRANCH_CODE   VARCHAR2(30 BYTE)
)#
CREATE TABLE DIST_PHOTO_INFO
(
  FILENAME      VARCHAR2(50 BYTE)               NOT NULL,
  DESCRIPTION   VARCHAR2(200 BYTE),
  URL           VARCHAR2(100 BYTE),
  ENTITY_TYPE   VARCHAR2(1 BYTE),
  ENTITY_CODE   VARCHAR2(30 BYTE)               NOT NULL,
  MEDIA_TYPE    VARCHAR2(10 BYTE)               NOT NULL,
  CATEGORYID    NUMBER(15),
  REMARKS       VARCHAR2(500 BYTE),
  CREATED_BY    VARCHAR2(30 BYTE)               NOT NULL,
  CREATE_DATE   DATE                            NOT NULL,
  COMPANY_CODE  VARCHAR2(30 BYTE)               NOT NULL,
  BRANCH_CODE   VARCHAR2(30 BYTE),
  SYNC_ID       VARCHAR2(50 BYTE),
  CONSTRAINT CK_DIST_PH_INF_ENT_TYP CHECK ( ENTITY_TYPE IN ('P', 'D', 'R', 'S') ),
  CONSTRAINT CK_DIST_PH_INF_MED_TYP CHECK ( MEDIA_TYPE IN ('GENERAL', 'STORE', 'PCONTACT', 'ATTN') )
)#
CREATE TABLE DIST_PREFERENCE_SETUP
(
  MO_GPS                         CHAR(1 BYTE)   DEFAULT 'N'                   NOT NULL,
  MO_AGPS                        CHAR(1 BYTE)   DEFAULT 'N'                   NOT NULL,
  PO_COMPANY_LIST                CHAR(1 BYTE)   DEFAULT 'N'                   NOT NULL,
  PO_PARTY_TYPE                  CHAR(1 BYTE)   DEFAULT 'N'                   NOT NULL,
  PO_BILLING_NAME                CHAR(1 BYTE)   DEFAULT 'N'                   NOT NULL,
  PO_SYN_RATE                    CHAR(1 BYTE)   DEFAULT 'N'                   NOT NULL,
  PO_CUSTOM_RATE                 CHAR(1 BYTE)   DEFAULT 'N'                   NOT NULL,
  PO_REMARKS                     CHAR(1 BYTE)   DEFAULT 'N'                   NOT NULL,
  PO_CONVERSION_UNIT             CHAR(1 BYTE)   DEFAULT 'N'                   NOT NULL,
  PO_CONVERSION_FACTOR           CHAR(1 BYTE)   DEFAULT 'N'                   NOT NULL,
  PO_SALES_TYPE                  CHAR(1 BYTE)   DEFAULT 'N'                   NOT NULL,
  PO_SHIPPING_ADDRESS            CHAR(1 BYTE)   DEFAULT 'N'                   NOT NULL,
  PO_SHIPPING_CONTACT            CHAR(1 BYTE)   DEFAULT 'N'                   NOT NULL,
  PO_DISPLAY_DIST_ITEM           CHAR(1 BYTE)   DEFAULT 'N'                   NOT NULL,
  SO_CREDIT_LIMIT_CHK            CHAR(1 BYTE)   DEFAULT 'N'                   NOT NULL,
  SO_CREDIT_DAYS_CHK             CHAR(1 BYTE)   DEFAULT 'N'                   NOT NULL,
  SO_CONSOLIDATE_DEFAULT         CHAR(1 BYTE)   DEFAULT 'N'                   NOT NULL,
  CS_CONVERSION_UNIT             CHAR(1 BYTE)   DEFAULT 'N'                   NOT NULL,
  QA_MKT_INFO                    CHAR(1 BYTE)   DEFAULT 'N'                   NOT NULL,
  QA_COMPT_INFO                  CHAR(1 BYTE)   DEFAULT 'N'                   NOT NULL,
  SQL_NN_CONVERSION_UNIT_FACTOR  CHAR(1 BYTE)   DEFAULT 'N'                   NOT NULL,
  ATN_DEFAULT                    CHAR(1 BYTE)   DEFAULT 'N'                   NOT NULL,
  ATN_IMAGE                      CHAR(1 BYTE)   DEFAULT 'N'                   NOT NULL,
  SET_RES_MAP_WHOLESALER         CHAR(1 BYTE)   DEFAULT 'N'                   NOT NULL,
  COMPANY_CODE                   VARCHAR2(30 BYTE),
  BRANCH_CODE                    VARCHAR2(30 BYTE),
  SQL_MULTIPLE_COMPANY           CHAR(1 BYTE)   DEFAULT ('Y'),
  SQL_COMPANY_ENTITY             CHAR(1 BYTE)   DEFAULT 'N',
  LO_BG_TRACK                    CHAR(1 BYTE)   DEFAULT 'N'                   NOT NULL,
  PO_RATE_TABLE                  VARCHAR2(50 BYTE),
  PO_RATE_COLUMN                 VARCHAR2(30 BYTE) DEFAULT 'STANDARD_RATE',
  PO_DIST_RATE_COLUMN            VARCHAR2(30 BYTE) DEFAULT 'STANDARD_RATE',
  LO_BG_TIME                     NUMBER(5,2),
  SQL_PEV_DAYS                   NUMBER(2),
  SQL_FOL_DAYS                   NUMBER(2),
  MO_DISABLE_PLAYSTORE           CHAR(1 BYTE)   DEFAULT 'N'                   NOT NULL,
  MO_SAVE_DATA                   CHAR(1 BYTE)   DEFAULT 'N'                   NOT NULL
)#
ALTER TABLE DIST_PREFERENCE_SETUP
ADD SQL_GROUP_MAP CHAR(1 BYTE) DEFAULT 'N'#
ALTER TABLE DIST_PREFERENCE_SETUP
ADD SQL_OPEN_ADDOUTLET CHAR(1 BYTE) DEFAULT 'N'#
CREATE TABLE DIST_QA_ANSWER
(
  SP_CODE       VARCHAR2(30 BYTE)               NOT NULL,
  ENTITY_CODE   VARCHAR2(30 BYTE)               NOT NULL,
  ENTITY_TYPE   CHAR(1 BYTE)                    NOT NULL,
  QA_CODE       NUMBER                          NOT NULL,
  ANSWER        VARCHAR2(100 BYTE),
  CREATED_BY    VARCHAR2(30 BYTE)               NOT NULL,
  CREATED_DATE  DATE                            DEFAULT SYSDATE               NOT NULL,
  MODIFY_BY     VARCHAR2(30 BYTE),
  MODIFY_DATE   DATE,
  DELETED_FLAG  CHAR(1 BYTE)                    DEFAULT 'N',
  COMPANY_CODE  VARCHAR2(30 BYTE),
  BRANCH_CODE   VARCHAR2(30 BYTE),
  SYNC_ID       VARCHAR2(50 BYTE)
)#
CREATE TABLE DIST_QA_DETAIL
(
  QA_CODE       NUMBER                          NOT NULL,
  SNO           NUMBER,
  ANSWERS       VARCHAR2(40 BYTE),
  CREATED_BY    VARCHAR2(30 BYTE)               NOT NULL,
  CREATED_DATE  DATE                            DEFAULT SYSDATE               NOT NULL,
  MODIFY_BY     VARCHAR2(30 BYTE),
  MODIFY_DATE   DATE,
  DELETED_FLAG  CHAR(1 BYTE)                    DEFAULT 'N',
  COMPANY_CODE  VARCHAR2(30 BYTE),
  BRANCH_CODE   VARCHAR2(30 BYTE),
  CONSTRAINT UK_DIST_QA_DTL_QA_SN_CD UNIQUE (QA_CODE, SNO)
)#
CREATE TABLE DIST_QA_MASTER
(
  QA_CODE       NUMBER                          NOT NULL,
  QA_TYPE       VARCHAR2(3 BYTE),
  SET_CODE      NUMBER,
  QUESTION      VARCHAR2(255 BYTE)              NOT NULL,
  CREATED_BY    VARCHAR2(30 BYTE)               NOT NULL,
  CREATED_DATE  DATE                            DEFAULT SYSDATE               NOT NULL,
  MODIFY_BY     VARCHAR2(30 BYTE),
  MODIFY_DATE   DATE,
  DELETED_FLAG  CHAR(1 BYTE)                    DEFAULT 'N',
  COMPANY_CODE  VARCHAR2(30 BYTE)               NOT NULL,
  BRANCH_CODE   VARCHAR2(30 BYTE),
  CONSTRAINT CK_DIST_QA_MST_QA_TYP CHECK ( QA_TYPE IN ('BOL', 'MCC', 'MCR', 'NUM', 'TXT')),
  CONSTRAINT PK_DIST_QA_MST_QA_CD PRIMARY KEY (QA_CODE)
)#
CREATE TABLE DIST_QA_SET
(
  SET_CODE      NUMBER                          NOT NULL,
  TITLE         VARCHAR2(200 BYTE),
  SET_DATE      DATE                            NOT NULL,
  CREATED_BY    VARCHAR2(30 BYTE)               NOT NULL,
  CREATED_DATE  DATE                            DEFAULT SYSDATE               NOT NULL,
  MODIFY_BY     VARCHAR2(30 BYTE),
  MODIFY_DATE   DATE,
  DELETED_FLAG  CHAR(1 BYTE)                    DEFAULT 'N',
  COMPANY_CODE  VARCHAR2(30 BYTE)               NOT NULL,
  BRANCH_CODE   VARCHAR2(30 BYTE),
  QA_TYPE       CHAR(1 BYTE)                    DEFAULT 'G',
  IS_ACTIVE     CHAR(1 BYTE)                    DEFAULT 'Y'                   NOT NULL,
  CONSTRAINT CHECK_QA_TYPE_GEN CHECK (QA_TYPE IN ('G','B','S','O')),
  CONSTRAINT PK_DIST_QA_SET_SET_CD PRIMARY KEY (SET_CODE)
)#
CREATE TABLE DIST_QA_SET_SALESPERSON_MAP
(
  SURVEY_CODE  NUMBER                          NOT NULL,
  SURVEY_EDESC  VARCHAR(500 BYTE),
  SP_CODE       VARCHAR2(30 BYTE)               NOT NULL,
  AREA_CODES       VARCHAR2(100 BYTE)               NOT NULL,
  GROUP_CODES       VARCHAR2(100 BYTE)               NOT NULL,
  CREATED_BY    NUMBER                          NOT NULL,
  CREATED_DATE  DATE                            DEFAULT SYSDATE               NOT NULL,
  DELETED_FLAG  CHAR(1 BYTE)                    DEFAULT 'N'                   NOT NULL,
  COMPANY_CODE  VARCHAR2(30 BYTE),
  BRANCH_CODE   VARCHAR2(30 BYTE),
  EXPIRY_DATE   DATE                            DEFAULT (SYSDATE+60)
)#
CREATE TABLE DIST_QA_SURVEY_MAP
(
SURVEY_ID NUMBER(5),
SET_ID NUMBER(5),
SET_TYPE CHAR(1) DEFAULT 'G',
CONSTRAINT CHK_QA_SP_MAP_SET_TYPE CHECK (SET_TYPE IN ('G','T'))
)#
CREATE TABLE DIST_QA_TAB_TABLE
(
  TABLE_ID      NUMBER                          NOT NULL,
  TABLE_TITLE   VARCHAR2(200 BYTE)              NOT NULL,
  CREATED_DATE  DATE                            DEFAULT SYSDATE               NOT NULL,
  DELETED_FLAG  CHAR(1 BYTE)                    DEFAULT 'N'                   NOT NULL,
  COMPANY_CODE  VARCHAR2(30 BYTE)               NOT NULL,
  BRANCH_CODE   VARCHAR2(30 BYTE),
  QA_TYPE       CHAR(1 BYTE)                    DEFAULT 'G',
  IS_ACTIVE     CHAR(1 BYTE)                    DEFAULT 'Y'                   NOT NULL,
  CONSTRAINT CHECK_QA_TYPE_TAB
  CHECK (QA_TYPE IN ('G','B','S','O')),
  CONSTRAINT PK_DIST_QA_TAB_TBL_ID PRIMARY KEY (TABLE_ID),
  CONSTRAINT UK_DIST_QA_TAB_TBL_TITLE UNIQUE (TABLE_TITLE)
)#
CREATE TABLE DIST_QUICKCAP
(
  ID                      INTEGER               NOT NULL,
  QUICKCAP_NO             NVARCHAR2(50),
  QUICKCAP_EDESC          NVARCHAR2(100),
  MODULE_CODE             NVARCHAR2(10),
  DISTRIBUTOR_CODE        VARCHAR2(30 BYTE)     NOT NULL,
  SQL_STATEMENT           VARCHAR2(500 BYTE),
  QUICKCAP_TITLE          NVARCHAR2(100),
  QUICKCAP_BGCOLOR        NVARCHAR2(20),
  QUICKCAP_FONTCOLOR      NVARCHAR2(20),
  QUICKCAP_ICON           NVARCHAR2(50),
  DELETED_FLAG            VARCHAR2(1 BYTE),
  CREATED_BY              VARCHAR2(10 BYTE),
  CREATED_DATE            DATE,
  ISACTIVE                VARCHAR2(1 BYTE),
  ORDERNO                 NUMBER,
  TYPE                    NUMBER,
  QUICKTYPE               VARCHAR2(10 BYTE),
  MIDBGCOLOR              NVARCHAR2(20),
  MIDFONTCOLOR            NVARCHAR2(20),
  MIDISBLINK              NVARCHAR2(1),
  MAXBGCOLOR              NVARCHAR2(20),
  MAXFONTCOLOR            NVARCHAR2(20),
  MAXISBLINK              NVARCHAR2(1),
  MAXVALUES               NUMBER,
  MINVALUES               NUMBER,
  MINISBLINK              NVARCHAR2(1),
  LABELPOSITION           VARCHAR2(10 BYTE),
  SPEEDOMETERMAXVALUE     NUMBER,
  MAXVALUEQUERY           NVARCHAR2(500),
  MINVALUEQUERY           NVARCHAR2(500),
  USERPERMISSION          VARCHAR2(100 BYTE),
  MODIFY_DATE             DATE,
  MODIFY_BY               VARCHAR2(30 BYTE),
  DISTRIBUTOR_CHECK_TYPE  VARCHAR2(5 BYTE)
)#
CREATE TABLE DIST_RESELLER_DETAIL
(
  RESELLER_CODE   VARCHAR2(30 BYTE)             NOT NULL,
  CONTACT_SUFFIX  VARCHAR2(5 BYTE),
  CONTACT_NAME    VARCHAR2(50 BYTE),
  CONTACT_NO      VARCHAR2(50 BYTE),
  DESIGNATION     VARCHAR2(50 BYTE),
  CREATED_BY      VARCHAR2(30 BYTE)             NOT NULL,
  CREATED_DATE    DATE                          DEFAULT SYSDATE               NOT NULL,
  DELETED_FLAG    CHAR(1 BYTE)                  DEFAULT 'N',
  MODIFY_DATE     DATE,
  MODIFY_BY       VARCHAR2(30 BYTE),
  COMPANY_CODE    VARCHAR2(30 BYTE)             NOT NULL,
  BRANCH_CODE     VARCHAR2(30 BYTE),
  SYNC_ID         VARCHAR2(50 BYTE)
)#
CREATE TABLE DIST_RESELLER_ENTITY
(
  RESELLER_CODE  VARCHAR2(30 BYTE)              NOT NULL,
  ENTITY_CODE    VARCHAR2(30 BYTE)              NOT NULL,
  ENTITY_TYPE    CHAR(1 BYTE)                   DEFAULT 'D'                   NOT NULL,
  CREATED_BY     VARCHAR2(30 BYTE)              NOT NULL,
  CREATED_DATE   DATE                           DEFAULT SYSDATE               NOT NULL,
  DELETED_FLAG   CHAR(1 BYTE)                   DEFAULT 'N',
  MODIFY_DATE    DATE,
  MODIFY_BY      VARCHAR2(30 BYTE),
  COMPANY_CODE   VARCHAR2(30 BYTE)              NOT NULL,
  BRANCH_CODE    VARCHAR2(30 BYTE),
  SYNC_ID        VARCHAR2(50 BYTE),
  CONSTRAINT CK_DST_RES_ENT_ENT_TYP CHECK ( ENTITY_TYPE IN ('D', 'W')),
  CONSTRAINT PK_DIST_RES_ENT_ENT_CD PRIMARY KEY (RESELLER_CODE, ENTITY_CODE, COMPANY_CODE)
)#
CREATE TABLE DIST_RESELLER_MASTER
(
  RESELLER_CODE       VARCHAR2(30 BYTE)         NOT NULL,
  RESELLER_NAME       VARCHAR2(200 BYTE)        NOT NULL,
  RESELLER_CONTACT    VARCHAR2(50 BYTE),
  DISTRIBUTOR_CODE    VARCHAR2(30 BYTE),
  AREA_CODE           VARCHAR2(4 BYTE),
  RETAIL_CODE         VARCHAR2(20 BYTE),
  REG_OFFICE_ADDRESS  VARCHAR2(100 BYTE),
  CONTACT_SUFFIX      VARCHAR2(5 BYTE),
  CONTACT_NAME        VARCHAR2(50 BYTE),
  CONTACT_NO          VARCHAR2(150 BYTE),
  EMAIL               VARCHAR2(200 BYTE),
  LATITUDE            VARCHAR2(20 BYTE),
  LONGITUDE           VARCHAR2(20 BYTE),
  WEIGHT              NUMBER(7)                 DEFAULT 0                     NOT NULL,
  VAT_NO              VARCHAR2(30 BYTE),
  PAN_NO              VARCHAR2(30 BYTE),
  OUTLET_TYPE_ID      NUMBER,
  OUTLET_SUBTYPE_ID   NUMBER,
  GROUPID             NUMBER(3),
  CREATED_BY          NUMBER(5),
  LUPDATE_BY          NUMBER(5),
  CREATED_DATE        DATE                      DEFAULT SYSDATE               NOT NULL,
  LUPDATE_DATE        DATE,
  ACTIVE              CHAR(1 BYTE)              DEFAULT 'Y',
  WHOLESELLER         CHAR(1 BYTE)              DEFAULT 'N',
  COMPANY_CODE        VARCHAR2(30 BYTE)         NOT NULL,
  BRANCH_CODE         VARCHAR2(30 BYTE)         NOT NULL,
  SOURCE              CHAR(3 BYTE)              DEFAULT 'WEB'                 NOT NULL,
  SYNC_ID             VARCHAR2(50 BYTE),
  DELETED_FLAG        CHAR(1 BYTE)              DEFAULT 'N'                   NOT NULL,
  REMARKS             VARCHAR2(500 BYTE),
  TEMP_ROUTE_CODE     VARCHAR2(4 BYTE),
  IS_CLOSED           CHAR(1 BYTE)              DEFAULT 'N'                   NOT NULL,
  CONSTRAINT CK_DIST_RES_MST_SRC CHECK ( SOURCE IN ('WEB', 'MOB')),
  CONSTRAINT PK_DIST_RES_MST_RES_CD PRIMARY KEY (RESELLER_CODE),
  CONSTRAINT UK_DIST_RES_MST_RES_MST UNIQUE (RESELLER_CODE, RESELLER_NAME, CONTACT_NO)
)#
CREATE TABLE DIST_RESELLER_STOCK
(
  RESELLER_CODE  VARCHAR2(30 BYTE)              NOT NULL,
  ITEM_CODE      VARCHAR2(30 BYTE)              NOT NULL,
  MU_CODE        VARCHAR2(5 BYTE)               NOT NULL,
  CURRENT_STOCK  NUMBER(5)                      NOT NULL,
  PURCHASE_QTY   NUMBER(5)                      NOT NULL,
  SP_CODE        VARCHAR2(30 BYTE)              NOT NULL,
  DELETED_FLAG   CHAR(1 BYTE)                   DEFAULT 'N',
  CREATED_DATE   DATE                           DEFAULT SYSDATE               NOT NULL,
  COMPANY_CODE   VARCHAR2(30 BYTE)              NOT NULL,
  BRANCH_CODE    VARCHAR2(30 BYTE),
  SYNC_ID        VARCHAR2(50 BYTE)
)#
CREATE TABLE DIST_ROLE_MASTER_SETUP
(
  ROLE_CODE     NUMBER(2)                       NOT NULL,
  ROLE_NAME     VARCHAR2(50 BYTE)               NOT NULL,
  CREATED_BY    NUMBER(5),
  CREATED_DATE  DATE,
  LUPDATE_BY    NUMBER(5),
  LUPDATE_DATE  DATE,
  ACTIVE        CHAR(1 BYTE)                    DEFAULT 'Y',
  COMPANY_CODE  VARCHAR2(30 BYTE),
  BRANCH_CODE   VARCHAR2(30 BYTE),
  CONSTRAINT PK_DIST_ROL_MST_SETUP_ROL_CD PRIMARY KEY (ROLE_CODE)
)#
CREATE TABLE DIST_ROLE_USER
(
  USERID        NUMBER                          NOT NULL,
  ROLE_CODE     NUMBER(2)                       NOT NULL,
  CREATED_BY    NUMBER(5),
  CREATED_DATE  DATE,
  LUPDATE_BY    NUMBER(5),
  LUPDATE_DATE  DATE,
  ACTIVE        CHAR(1 BYTE)                    DEFAULT 'Y',
  COMPANY_CODE  VARCHAR2(30 BYTE),
  BRANCH_CODE   VARCHAR2(30 BYTE),
  CONSTRAINT FK_DIST_ROL_USR_ROL_CD FOREIGN KEY (ROLE_CODE) REFERENCES DIST_ROLE_MASTER_SETUP (ROLE_CODE),
  CONSTRAINT FK_DIST_ROL_USR_USR_ID FOREIGN KEY (USERID) REFERENCES DIST_LOGIN_USER (USERID)
)#
CREATE TABLE DIST_ROUTE_ENTITY
(
  ROUTE_CODE    VARCHAR2(4 BYTE),
  ENTITY_CODE   VARCHAR2(30 BYTE)               NOT NULL,
  ENTITY_TYPE   CHAR(1 BYTE)                    NOT NULL,
  ORDER_NO      NUMBER(10)                      NOT NULL,
  CREATED_BY    VARCHAR2(30 BYTE)               NOT NULL,
  CREATED_DATE  DATE                            DEFAULT SYSDATE               NOT NULL,
  DELETED_FLAG  CHAR(1 BYTE)                    DEFAULT 'N',
  MODIFY_DATE   DATE,
  MODIFY_BY     VARCHAR2(30 BYTE),
  COMPANY_CODE  VARCHAR2(30 BYTE)               NOT NULL,
  BRANCH_CODE   VARCHAR2(30 BYTE),
  CONSTRAINT CK_DIST_ROU_ENT_ENT_TYP CHECK ( ENTITY_TYPE IN ('P', 'D', 'R'))
)#
CREATE TABLE DIST_ROUTE_MASTER
(
  ROUTE_CODE    VARCHAR2(4 BYTE)                NOT NULL,
  ROUTE_NAME    VARCHAR2(200 BYTE),
  COMPANY_CODE  VARCHAR2(30 BYTE)               NOT NULL,
  BRANCH_CODE   VARCHAR2(30 BYTE),
  DELETED_FLAG  CHAR(1 BYTE)                    DEFAULT 'N'                   NOT NULL,
  ROUTE_TYPE    CHAR(1 BYTE)                    DEFAULT 'D'                   NOT NULL,
  CONSTRAINT ROUTE_TYPE_CHK CHECK (ROUTE_TYPE IN ('D','B')),
  CONSTRAINT PK_DIST_ROU_MST_ROU_CD PRIMARY KEY (ROUTE_CODE),
  CONSTRAINT UK_DIST_ROU_MST_ROU_NAME UNIQUE (ROUTE_NAME)
)#
CREATE TABLE DIST_ROUTE_PLAN
(
  PLAN_CODE           NUMBER(12)                NOT NULL,
  PLAN_EDESC          VARCHAR2(100 BYTE)        NOT NULL,
  PLAN_NDESC          VARCHAR2(100 BYTE),
  START_DATE          DATE                      NOT NULL,
  END_DATE            DATE                      NOT NULL,
  TARGET_NAME         VARCHAR2(100 BYTE),
  TARGET_VALUE        NUMBER(12),
  TIME_FRAME_CODE     NUMBER(12),
  REMARKS             VARCHAR2(200 BYTE),
  COMPANY_CODE        VARCHAR2(30 BYTE),
  BRANCH_CODE         VARCHAR2(500 BYTE),
  CREATED_BY          VARCHAR2(30 BYTE),
  CREATED_DATE        DATE,
  LAST_MODIFIED_BY    VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE  DATE,
  APPROVED_BY         VARCHAR2(30 BYTE),
  APPROVED_DATE       DATE,
  DELETED_FLAG        CHAR(1 BYTE),
  ROUTE_TYPE          CHAR(1 BYTE)              DEFAULT 'D'                   NOT NULL,
  CONSTRAINT ROUTEPLAN_TYPE_CHK CHECK (ROUTE_TYPE IN ('D','B')),
  CONSTRAINT PK_DIST_ROU_PL_PL_CD PRIMARY KEY (PLAN_CODE)
)#
CREATE TABLE DIST_ROUTE_PLAN_DETAIL
(
  PLAN_CODE           NUMBER(12)                NOT NULL,
  ROUTE_CODE          VARCHAR2(4 BYTE)          NOT NULL,
  COMPANY_CODE        VARCHAR2(30 BYTE),
  BRANCH_CODE         VARCHAR2(500 BYTE),
  CREATED_BY          VARCHAR2(30 BYTE),
  CREATED_DATE        DATE,
  LAST_MODIFIED_BY    VARCHAR2(30 BYTE),
  LAST_MODIFIED_DATE  DATE,
  APPROVED_BY         VARCHAR2(30 BYTE),
  APPROVED_DATE       DATE,
  DELETED_FLAG        CHAR(1 BYTE),
  ROUTE_TYPE          CHAR(1 BYTE)              DEFAULT 'D'                   NOT NULL,
  CONSTRAINT ROUTE_TYPEDETAIL_CHK CHECK (ROUTE_TYPE IN ('D','B'))
)#
CREATE TABLE DIST_SALESPERSON_MASTER
(
  SP_CODE             VARCHAR2(30 BYTE)         NOT NULL,
  SUPERVISOR_CODE     VARCHAR2(30 BYTE),
  REG_OFFICE_ADDRESS  VARCHAR2(100 BYTE),
  CONTACT_NO          VARCHAR2(50 BYTE),
  EMAIL               VARCHAR2(50 BYTE),
  PAN_NO              VARCHAR2(50 BYTE),
  VAT_NO              VARCHAR2(50 BYTE),
  CREATED_BY          NUMBER(5),
  LUPDATE_BY          NUMBER(5),
  CREATED_DATE        DATE                      DEFAULT SYSDATE               NOT NULL,
  LUPDATE_DATE        DATE,
  ACTIVE              CHAR(1 BYTE)              DEFAULT 'Y',
  COMPANY_CODE        VARCHAR2(30 BYTE)         NOT NULL,
  BRANCH_CODE         VARCHAR2(30 BYTE)         NOT NULL
)#
CREATE TABLE DIST_TASK_MANAGER
(
  TASK_ID          NUMBER(5)                    NOT NULL,
  TASK_TITLE       VARCHAR2(100 BYTE)           NOT NULL,
  TASK_DECS        VARCHAR2(255 BYTE)           NOT NULL,
  TASK_BEGIN       DATE                         NOT NULL,
  TASK_END         DATE,
  TASK_CLOSED      DATE                         NOT NULL,
  TASK_STATUS      CHAR(1 BYTE)                 DEFAULT 'P',
  TASK_PROGRESS    NUMBER(3)                    DEFAULT 0,
  PROGRESS_DESC    VARCHAR2(255 BYTE),
  PRIOR_INFO_DAYS  NUMBER(2)                    DEFAULT 1,
  COMMENTS         VARCHAR2(255 BYTE),
  PRIORITY         CHAR(1 BYTE)                 DEFAULT 'H',
  FROM_USER        NUMBER(5)                    DEFAULT NULL,
  TO_USER          NUMBER(5)                    DEFAULT NULL,
  COMPANY_CODE     VARCHAR2(30 BYTE)            NOT NULL,
  BRANCH_CODE      VARCHAR2(30 BYTE)
)#
CREATE TABLE DIST_USER_AREAS
(
  SP_CODE       VARCHAR2(20 BYTE),
  AREA_CODE     VARCHAR2(20 BYTE),
  USER_ID       NUMBER(5),
  DELETED_FLAG  VARCHAR2(1 BYTE)                DEFAULT 'N',
  CREATED_BY    VARCHAR2(20 BYTE),
  CREATED_DATE  DATE,
  COMPANY_CODE  VARCHAR2(5 BYTE)                DEFAULT NULL
)#
CREATE TABLE DIST_VISIT_IMAGE
(
  IMAGE_CODE    NUMBER                          NOT NULL,
  IMAGE_NAME    VARCHAR2(200 BYTE)              NOT NULL,
  IMAGE_TITLE   VARCHAR2(200 BYTE),
  IMAGE_DESC    VARCHAR2(500 BYTE),
  CATEGORYID    NUMBER(15),
  SP_CODE       VARCHAR2(30 BYTE)               NOT NULL,
  ENTITY_CODE   VARCHAR2(30 BYTE)               NOT NULL,
  TYPE          CHAR(1 BYTE)                    NOT NULL,
  UPLOAD_DATE   DATE                            NOT NULL,
  LATITUDE      VARCHAR2(20 BYTE),
  LONGITUDE     VARCHAR2(20 BYTE),
  COMPANY_CODE  VARCHAR2(30 BYTE)               NOT NULL,
  BRANCH_CODE   VARCHAR2(30 BYTE),
  SYNC_ID       VARCHAR2(50 BYTE),
  CONSTRAINT CK_DIST_VIS_IMG_TYP CHECK ( TYPE IN ('P', 'D', 'R')),
  CONSTRAINT PK_VST_IMG_IMG_CD PRIMARY KEY (IMAGE_CODE)
)#
 alter table DIST_VISIT_IMAGE drop constraint CK_DIST_VIS_IMG_TYP #
 alter table DIST_VISIT_IMAGE add constraint CK_DIST_VIS_IMG_TYP  CHECK ( TYPE IN ('P', 'D', 'R','B')) enable novalidate#
CREATE INDEX IX_DIST_DST_MST_GRP_ID ON DIST_DISTRIBUTOR_MASTER (GROUPID)#
CREATE INDEX IX_DIST_IP_SSD_PUR_ORD_CMP_CD ON DIST_IP_SSD_PURCHASE_ORDER (COMPANY_CODE)#
CREATE INDEX IX_DIST_IP_SSD_PUR_ORD_CRT_BY ON DIST_IP_SSD_PURCHASE_ORDER (CREATED_BY)#
CREATE INDEX IX_DIST_IP_SSD_PUR_ORD_CUS_CD ON DIST_IP_SSD_PURCHASE_ORDER (CUSTOMER_CODE)#
CREATE INDEX IX_DIST_IP_SSD_PUR_ORD_ITM_CD ON DIST_IP_SSD_PURCHASE_ORDER (ITEM_CODE)#
CREATE INDEX IX_DIST_IP_SSD_PUR_ORD_ORD_DT ON DIST_IP_SSD_PURCHASE_ORDER (ORDER_DATE)#
CREATE INDEX IX_DIST_IP_SSD_PUR_ORD_ORD_FRM ON DIST_IP_SSD_PURCHASE_ORDER (ORDER_FROM)#
CREATE INDEX IX_DIST_IP_SSD_PUR_ORD_ORD_NO ON DIST_IP_SSD_PURCHASE_ORDER (ORDER_NO)#
CREATE INDEX IX_DIST_IP_SSD_PUR_ORD_PTYP_CD ON DIST_IP_SSD_PURCHASE_ORDER (PARTY_TYPE_CODE)#
CREATE INDEX IX_DIST_IP_SSD_PUR_ORD_SO_NO ON DIST_IP_SSD_PURCHASE_ORDER (SALES_ORDER_NO)#
CREATE INDEX IX_DIST_IP_SSR_PUR_ORD_CMP_CD ON DIST_IP_SSR_PURCHASE_ORDER (COMPANY_CODE)#
CREATE INDEX IX_DIST_IP_SSR_PUR_ORD_CRT_BY ON DIST_IP_SSR_PURCHASE_ORDER (CREATED_BY)#
CREATE INDEX IX_DIST_IP_SSR_PUR_ORD_CUS_CD ON DIST_IP_SSR_PURCHASE_ORDER (CUSTOMER_CODE)#
CREATE INDEX IX_DIST_IP_SSR_PUR_ORD_DIS_FRM ON DIST_IP_SSR_PURCHASE_ORDER (DISPATCH_FROM)#
CREATE INDEX IX_DIST_IP_SSR_PUR_ORD_ITM_CD ON DIST_IP_SSR_PURCHASE_ORDER (ITEM_CODE)#
CREATE INDEX IX_DIST_IP_SSR_PUR_ORD_ORD_DT ON DIST_IP_SSR_PURCHASE_ORDER (ORDER_DATE)#
CREATE INDEX IX_DIST_IP_SSR_PUR_ORD_ORD_NO ON DIST_IP_SSR_PURCHASE_ORDER (ORDER_NO)#
CREATE INDEX IX_DIST_IP_SSR_PUR_ORD_PTYP_CD ON DIST_IP_SSR_PURCHASE_ORDER (PARTY_TYPE_CODE)#
CREATE INDEX IX_DIST_IP_SSR_PUR_ORD_RES_CD ON DIST_IP_SSR_PURCHASE_ORDER (RESELLER_CODE)#
CREATE INDEX IX_DIST_LM_LOC_TRK_TRK_TYP ON DIST_LM_LOCATION_TRACKING (TRACK_TYPE)#
CREATE INDEX IX_DIST_LOC_TRK_CMP_CD ON DIST_LOCATION_TRACK (COMPANY_CODE)#
CREATE INDEX IX_DIST_LOC_TRK_CUS_CD ON DIST_LOCATION_TRACK (CUSTOMER_CODE)#
CREATE INDEX IX_DIST_LOC_TRK_CUS_TYP ON DIST_LOCATION_TRACK (CUSTOMER_TYPE)#
CREATE INDEX IX_DIST_LOC_TRK_SP_CD ON DIST_LOCATION_TRACK (SP_CODE)#
CREATE INDEX IX_DIST_LOC_TRK_UP_DT ON DIST_LOCATION_TRACK (UPDATE_DATE)#
CREATE INDEX IX_DIST_LOG_USR_AREA_CD ON DIST_LOGIN_USER (AREA_CODE)#
CREATE INDEX IX_DIST_LOG_USR_CMP_CD ON DIST_LOGIN_USER (COMPANY_CODE)#
CREATE INDEX IX_DIST_LOG_USR_GRP_ID ON DIST_LOGIN_USER (GROUPID)#
CREATE INDEX IX_DIST_LOG_USR_SP_CD ON DIST_LOGIN_USER (SP_CODE)#
CREATE INDEX IX_DIST_PHOTO_INF_CTG_ID ON DIST_PHOTO_INFO (CATEGORYID)#
CREATE INDEX IX_DIST_RES_MST_CMP_CD ON DIST_RESELLER_MASTER (COMPANY_CODE)#
CREATE INDEX IX_DIST_RES_MST_GRP_ID ON DIST_RESELLER_MASTER (GROUPID)#
CREATE INDEX IX_DIST_RES_MST_OTL_STYP_ID ON DIST_RESELLER_MASTER (OUTLET_SUBTYPE_ID)#
CREATE INDEX IX_DIST_RES_MST_OTL_TYP_ID ON DIST_RESELLER_MASTER (OUTLET_TYPE_ID)#
CREATE INDEX IX_DIST_ROU_BRD_DTL_ASG_DT ON DIST_BRANDING_ROUTE_DETAIL (ASSIGN_DATE)#
CREATE INDEX IX_DIST_ROU_BRD_DTL_CMP_CD ON DIST_BRANDING_ROUTE_DETAIL (COMPANY_CODE)#
CREATE INDEX IX_DIST_ROU_BRD_DTL_EMP_CD ON DIST_BRANDING_ROUTE_DETAIL (EMP_CODE)#
CREATE INDEX IX_DIST_ROU_BRD_DTL_ROU_CD ON DIST_BRANDING_ROUTE_DETAIL (ROUTE_CODE)#
CREATE INDEX IX_DIST_ROU_ENT_CMP_CD ON DIST_ROUTE_ENTITY (COMPANY_CODE)#
CREATE INDEX IX_DIST_ROU_ENT_ENT_CD ON DIST_ROUTE_ENTITY (ENTITY_CODE)#
CREATE INDEX IX_DIST_ROU_ENT_ENT_TYP ON DIST_ROUTE_ENTITY (ENTITY_TYPE)#
CREATE INDEX IX_DIST_ROU_ENT_ROU_CD ON DIST_ROUTE_ENTITY (ROUTE_CODE)#
CREATE INDEX IX_DIST_VIS_IMG_CTG_ID ON DIST_VISIT_IMAGE (CATEGORYID)#
CREATE SEQUENCE SEQ_DIST_ROUTE_PLAN_CODE
  START WITH 101
  MAXVALUE 999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER#
CREATE TRIGGER "TRIG_GET_DIST_ROUTE_PLAN_CODE"
BEFORE INSERT ON DIST_ROUTE_PLAN 
FOR EACH ROW
BEGIN
  SELECT SEQ_DIST_ROUTE_PLAN_CODE.NEXTVAL
  INTO   :new.PLAN_CODE  
  FROM   dual;
END#
CREATE TABLE BRD_OTHER_ENTITY
(
  CODE            VARCHAR2(30 BYTE)             NOT NULL,
  DESCRIPTION     VARCHAR2(100 BYTE)            NOT NULL,
  CONTACT_PERSON  VARCHAR2(100 BYTE),
  AREA_CODE       VARCHAR2(4 BYTE),
  GROUP_ID        NUMBER(3),
  CONTACT_NO      VARCHAR2(50 BYTE),
  LATITUDE        VARCHAR2(20 BYTE),
  LONGITUDE       VARCHAR2(20 BYTE),
  COMPANY_CODE    VARCHAR2(30 BYTE)             NOT NULL,
  BRANCH_CODE     VARCHAR2(30 BYTE),
  DELETED_FLAG    CHAR(1 BYTE)                  DEFAULT 'N'                   NOT NULL,
  CREATED_BY      VARCHAR2(20 BYTE),
  CREATED_DATE    DATE,
  SYNC_ID         VARCHAR2(50 BYTE),
  CONSTRAINT PK_OTHER_ENTITY PRIMARY KEY (CODE),
  CONSTRAINT FK_OTHER_ENTITY_AREA FOREIGN KEY (AREA_CODE) REFERENCES DIST_AREA_MASTER (AREA_CODE)
)#
CREATE TABLE DIST_AREA_BOUNDARY_SETUP
(
  AREA_CODE     VARCHAR2(4 BYTE)                NOT NULL,
  AREA_PATH     CLOB,
  REMARKS       VARCHAR2(200 BYTE),
  CREATED_BY    VARCHAR2(30 BYTE)               NOT NULL,
  CREATED_DATE  DATE                            DEFAULT SYSDATE               NOT NULL,
  MODIFY_BY     VARCHAR2(30 BYTE),
  MODIFY_DATE   DATE,
  DELETED_FLAG  CHAR(1 BYTE)                    DEFAULT 'N',
  COMPANY_CODE  VARCHAR2(30 BYTE)               NOT NULL,
  BRANCH_CODE   VARCHAR2(30 BYTE),
  CONSTRAINT FK_DIST_AREA_BOU_SETUP_AREA_CD FOREIGN KEY (AREA_CODE) REFERENCES DIST_AREA_MASTER (AREA_CODE)
)#
CREATE TABLE DIST_COMPT_INFO
(
  COMPT_CODE    NUMBER(10)                      NOT NULL,
  INFO_TEXT     VARCHAR2(200 BYTE)              NOT NULL,
  ENTITY_TYPE   VARCHAR2(1 BYTE),
  ENTITY_CODE   VARCHAR2(30 BYTE)               NOT NULL,
  USER_ID       NUMBER(5)                       NOT NULL,
  CREATE_DATE   DATE                            NOT NULL,
  COMPANY_CODE  VARCHAR2(30 BYTE),
  BRANCH_CODE   VARCHAR2(30 BYTE),
  SYNC_ID       VARCHAR2(50 BYTE),
  CONSTRAINT FK_DIST_COMPT_INFO_USR_ID FOREIGN KEY (USER_ID) REFERENCES DIST_LOGIN_USER (USERID)
)#
CREATE TABLE DIST_COMP_ITEM_MAP
(
  ITEM_CODE     NUMBER(5)                       NOT NULL,
  COMP_ITEM_ID  NUMBER(5)                       NOT NULL,
  CREATED_BY    VARCHAR2(30 BYTE),
  CREATED_DATE  DATE,
  COMPANY_CODE  VARCHAR2(30 BYTE),
  SYNC_ID       VARCHAR2(50 BYTE),
  CONSTRAINT PK_COMP_ITEM_MAP PRIMARY KEY (ITEM_CODE, COMP_ITEM_ID),
  CONSTRAINT FK_COMP_ITEM FOREIGN KEY (COMP_ITEM_ID) REFERENCES DIST_COMP_ITEM_MASTER (ITEM_ID)
)#
CREATE TABLE DIST_MENU_MASTER_SETUP
(
  MENU_CODE     NUMBER(3)                       NOT NULL,
  MODULE_CODE   NUMBER(2)                       NOT NULL,
  MENU_NAME     VARCHAR2(50 BYTE)               NOT NULL,
  URL           VARCHAR2(200 BYTE)              NOT NULL,
  ICON_NAME     VARCHAR2(100 BYTE),
  ACTIVE        CHAR(1 BYTE)                    DEFAULT 'Y',
  COMPANY_CODE  VARCHAR2(30 BYTE),
  BRANCH_CODE   VARCHAR2(30 BYTE),
  CONSTRAINT PK_DIST_MNU_MST_SETUP_MNU_CD PRIMARY KEY (MENU_CODE),
  CONSTRAINT FK_DIST_MNU_MST_SETUP_MOD_CD FOREIGN KEY (MODULE_CODE) REFERENCES DIST_MODULE_MASTER_SETUP (MODULE_CODE)
)#
CREATE TABLE DIST_QA_TAB_CELL
(
  CELL_ID     NUMBER                            NOT NULL,
  TABLE_ID    NUMBER                            NOT NULL,
  ROW_NO      NUMBER                            NOT NULL,
  CELL_NO     NUMBER                            NOT NULL,
  CELL_TYPE   CHAR(4 BYTE)                      DEFAULT 'TXT',
  CELL_LABEL  VARCHAR2(30 BYTE),
  CONSTRAINT CK_DIST_QA_TAB_CELL_CELL_TYPE CHECK ( CELL_TYPE IN ('LBL', 'CHK', 'RDO', 'TXT', 'NUM','FILE')),
  CONSTRAINT PK_DIST_QA_TAB_CELL_CELL_ID PRIMARY KEY (CELL_ID),
  CONSTRAINT FK_DIST_QA_TAB_CELL_TBL_ID FOREIGN KEY (TABLE_ID) REFERENCES DIST_QA_TAB_TABLE (TABLE_ID)
)#
CREATE TABLE DIST_QA_TAB_CELL_ANSWER
(
  ANSWER_ID     NUMBER                          NOT NULL,
  CELL_ID       NUMBER                          NOT NULL,
  ANSWER        VARCHAR2(30 BYTE),
  ENTITY_CODE   VARCHAR2(30 BYTE),
  ENTITY_TYPE   CHAR(1 BYTE)                    NOT NULL,
  SP_CODE       VARCHAR2(30 BYTE)               NOT NULL,
  CREATED_DATE  DATE                            DEFAULT SYSDATE               NOT NULL,
  SYNC_ID       VARCHAR2(50 BYTE),
  CONSTRAINT CK_DST_QA_TAB_CELL_ANS_ENT_TYP CHECK (ENTITY_TYPE IN ('P', 'D', 'R','B')),
  CONSTRAINT PK_DIST_QA_TAB_CELL_ANS_ANS_ID PRIMARY KEY (ANSWER_ID),
  CONSTRAINT FK_DIST_QA_TAB_CELL_ANS_CID FOREIGN KEY (CELL_ID) REFERENCES DIST_QA_TAB_CELL (CELL_ID)
)#
CREATE TABLE DIST_ROLE_MENU_SETUP
(
  ROLE_CODE     NUMBER(2)                       NOT NULL,
  MENU_CODE     NUMBER(3)                       NOT NULL,
  CREATED_BY    NUMBER(5),
  CREATED_DATE  DATE,
  LUPDATE_BY    NUMBER(5),
  LUPDATE_DATE  DATE,
  ACTIVE        CHAR(1 BYTE)                    DEFAULT 'Y',
  COMPANY_CODE  VARCHAR2(30 BYTE),
  BRANCH_CODE   VARCHAR2(30 BYTE),
  CONSTRAINT FK_DIST_ROL_MNU_SETUP_MNU_CD FOREIGN KEY (MENU_CODE) REFERENCES DIST_MENU_MASTER_SETUP (MENU_CODE),
  CONSTRAINT FK_DIST_ROL_MNU_SETUP_ROL_CD FOREIGN KEY (ROLE_CODE) REFERENCES DIST_ROLE_MASTER_SETUP (ROLE_CODE)
)#
CREATE TABLE DIST_ROUTE_AREA
(
  ROUTE_CODE    VARCHAR2(4 BYTE),
  AREA_CODE     VARCHAR2(4 BYTE),
  COMPANY_CODE  VARCHAR2(30 BYTE)               NOT NULL,
  BRANCH_CODE   VARCHAR2(30 BYTE),
  CONSTRAINT FK_DIST_ROU_AREA_AREA_CD FOREIGN KEY (AREA_CODE) REFERENCES DIST_AREA_MASTER (AREA_CODE),
  CONSTRAINT FK_DIST_ROU_AREA_ROU_CD FOREIGN KEY (ROUTE_CODE) REFERENCES DIST_ROUTE_MASTER (ROUTE_CODE)
)#
CREATE TABLE DIST_ROUTE_DETAIL
(
  ROUTE_CODE    VARCHAR2(4 BYTE),
  EMP_CODE      VARCHAR2(30 BYTE),
  PLAN_CODE     NUMBER(12),
  ASSIGN_DATE   DATE,
  CREATED_DATE  DATE,
  CREATED_BY    VARCHAR2(30 BYTE),
  APPROVE_DATE  DATE,
  APPROVE_BY    VARCHAR2(30 BYTE),
  MODIFY_DATE   DATE,
  MODIFY_BY     VARCHAR2(30 BYTE),
  DELETED_FLAG  CHAR(1 BYTE)                    DEFAULT 'N',
  COMPANY_CODE  VARCHAR2(30 BYTE),
  BRANCH_CODE   VARCHAR2(30 BYTE),
  CONSTRAINT FK_DIST_ROU_DTL_ROU_CD FOREIGN KEY (ROUTE_CODE) REFERENCES DIST_ROUTE_MASTER (ROUTE_CODE)
)#
CREATE TABLE NEO_HRIS_ATTENDANCE
(
  EMPLOYEE_ID      NUMBER(7)                    NOT NULL,
  COMPANY_CODE     VARCHAR2(30 BYTE),
  ATTENDANCE_DT    DATE                         NOT NULL,
  IP_ADDRESS       VARCHAR2(20 BYTE),
  ATTENDANCE_FROM  VARCHAR2(50 BYTE),
  ATTENDANCE_TIME  TIMESTAMP(6)                 NOT NULL
)#
 CREATE TABLE DIST_USER_ITEM_MAPPING
(
  SP_CODE       VARCHAR2(20 BYTE),
  USER_ID       NUMBER(5),
  ITEM_CODE     VARCHAR2(20 BYTE),
  DELETED_FLAG  VARCHAR2(1 BYTE)                DEFAULT 'N',
  CREATED_BY    VARCHAR2(20 BYTE),
  CREATED_DATE  DATE,
  COMPANY_CODE  VARCHAR2(5 BYTE)                DEFAULT NULL
)#
alter table DIST_QA_SET drop constraint 
  CHECK_QA_TYPE_GEN#
  ALTER TABLE DIST_QA_SET ADD (
  CONSTRAINT CHECK_QA_TYPE_GEN
  CHECK (QA_TYPE IN ('G','B','S','O','w')
))#
CREATE TABLE DIST_WEB_QUE_ANS
(
  WEB_QUE_ANS_ID  NUMBER                        NOT NULL,
  CUSTOMER_CODE   VARCHAR2(50 BYTE),
  CUSTOMER_NAME   VARCHAR2(100 BYTE),
  QUESTION        VARCHAR2(100 BYTE),
  ANSWER          VARCHAR2(500 BYTE),
  CREATED_BY      NUMBER                        NOT NULL,
  CREATED_DATE    DATE                          DEFAULT SYSDATE               NOT NULL,
  DELETED_FLAG    CHAR(1 BYTE)                  DEFAULT 'N'                   NOT NULL,
  COMPANY_CODE    VARCHAR2(30 BYTE)
)#
CREATE TABLE BRD_CONTRACT_SCHEME_BRAND
(
  CONTRACT_CODE  NUMBER                         NOT NULL,
  BRAND_CODE      VARCHAR2(15 BYTE)              NOT NULL,
  COMPANY_CODE   VARCHAR2(30 BYTE)              NOT NULL,
  BRANCH_CODE    VARCHAR2(30 BYTE)
)#
CREATE TABLE DIST_SYNERGY_EMPLOYEE_MAP
                    (
                      LOGIN_SP_CODE         VARCHAR2(50)                     NOT NULL,
                      DIST_SP_CODE  VARCHAR2(50)                     NOT NULL,
                      COMPANY_CODE    VARCHAR2(3 BYTE),
                      DELETED_FLAG    CHAR(1 BYTE)                  DEFAULT 'N'                   NOT NULL,
                      CREATED_BY      VARCHAR2(20 BYTE),
                      CREATED_DATE    DATE,
                      CONSTRAINT PK_DIST_SYNERGY_EMPLOYEE_MAP
                      PRIMARY KEY
                      (LOGIN_SP_CODE, DIST_SP_CODE)
                    )#
alter table dist_reseller_master
add created_by_name varchar(100)#
ALTER TABLE DIST_PREFERENCE_SETUP
ADD AUTO_LOG_OUT CHAR (1 BYTE) DEFAULT 'Y'#
ALTER TABLE DIST_PREFERENCE_SETUP
ADD DISABLE_LOCATION CHAR (1 BYTE) DEFAULT 'N'#
CREATE TABLE HRIS_ATTENDANCE
(
  EMPLOYEE_ID      NUMBER(7),
  ATTENDANCE_DT    DATE                         NOT NULL,
  IP_ADDRESS       VARCHAR2(20 BYTE),
  ATTENDANCE_FROM  VARCHAR2(50 BYTE),
  ATTENDANCE_TIME  TIMESTAMP(6)                 NOT NULL,
  REMARKS          VARCHAR2(255 BYTE),
  THUMB_ID         NUMBER
)#
    ALTER TABLE DIST_ROUTE_MASTER
MODIFY  ROUTE_CODE VARCHAR2(7 byte)#
CREATE TABLE DISTRICT_CODE
(
  DISTRICT_CODE   VARCHAR2(8 BYTE)              NOT NULL,
  DISTRICT_EDESC  VARCHAR2(100 BYTE)            NOT NULL,
  DISTRICT_NDESC  VARCHAR2(100 BYTE),
  ZONE_CODE       VARCHAR2(15 BYTE),
  REGION_CODE     VARCHAR2(15 BYTE),
  REMARKS         VARCHAR2(200 BYTE),
  MODIFY_DATE     DATE,
  MODIFY_BY       VARCHAR2(30 BYTE)
)#
 alter  table DIST_PREFERENCE_SETUP
 add SQL_SP_FILTER      CHAR(1 BYTE)   DEFAULT 'N'  not null#
 alter table dist_preference_setup ADD TRACK_ACTUAL_LOCATION  CHAR(1 BYTE)   DEFAULT 'N' NOT NULL#
CREATE UNIQUE INDEX PK_DISTRICT_CODE ON DISTRICT_CODE
(DISTRICT_CODE)#
ALTER TABLE DISTRICT_CODE ADD (
  CONSTRAINT PK_DISTRICT_CODE
  PRIMARY KEY
  (DISTRICT_CODE)
  USING INDEX PK_DISTRICT_CODE)#
  CREATE OR REPLACE FORCE VIEW DIST_LOGIN_GROUP
(
   SP_CODE,
   FULL_NAME,
   GROUP_EDESC,
   GROUP_CODE,
   GROUPID
)
AS
   SELECT U.SP_CODE,
          U.FULL_NAME,
          DM.GROUP_EDESC,
          DM.GROUP_CODE,
          DM.GROUPID
     FROM DIST_LOGIN_USER U, DIST_GROUP_MASTER DM
    WHERE U.GROUPID = DM.GROUPID AND U.COMPANY_CODE = DM.COMPANY_CODE#
CREATE INDEX IX_DIST_ROU_DTL_ASG_DT ON DIST_ROUTE_DETAIL (ASSIGN_DATE)#
CREATE INDEX IX_DIST_ROU_DTL_CMP_CD ON DIST_ROUTE_DETAIL (COMPANY_CODE)#
CREATE INDEX IX_DIST_ROU_DTL_EMP_CD ON DIST_ROUTE_DETAIL (EMP_CODE)#
CREATE INDEX IX_DIST_EOD_UPDATE_CD ON dist_eod_update (SP_CODE)#
CREATE INDEX IX_DIST_EOD_UPDATE_COMP ON dist_eod_update (COMPANY_CODE)#
CREATE INDEX IX_DIST_LM_LOCATION_SUBMITDATE ON DIST_LM_LOCATION_TRACKING (SUBMIT_DATE)#
CREATE INDEX IX_DIST_LM_LOCATION_SPCODE ON DIST_LM_LOCATION_TRACKING (SP_CODE)#
CREATE INDEX IX_DIST_ROU_DTL_ROU_CD ON DIST_ROUTE_DETAIL (ROUTE_CODE)