INSERT ALL 
INTO DIST_ROLE_MASTER_SETUP (ROLE_CODE, ROLE_NAME, CREATED_BY, CREATED_DATE, ACTIVE, COMPANY_CODE) VALUES (1, 'System User', 1, TO_DATE('07/15/2017 13:32:13', 'MM/DD/YYYY HH24:MI:SS'), 'Y', '06')
INTO DIST_ROLE_MASTER_SETUP (ROLE_CODE, ROLE_NAME, CREATED_BY, CREATED_DATE, ACTIVE, COMPANY_CODE) VALUES (2, 'Distributor', 2, TO_DATE('07/15/2017 13:32:13', 'MM/DD/YYYY HH24:MI:SS'), 'Y', '06')
INTO DIST_ROLE_MASTER_SETUP (ROLE_CODE, ROLE_NAME, CREATED_BY, CREATED_DATE, ACTIVE, COMPANY_CODE) VALUES (3, 'Reseller', 2, TO_DATE('07/15/2017 13:32:13', 'MM/DD/YYYY HH24:MI:SS'), 'Y', '06')
INTO DIST_ROLE_MASTER_SETUP (ROLE_CODE, ROLE_NAME, CREATED_BY, CREATED_DATE, ACTIVE, COMPANY_CODE) VALUES (4, 'Retail Sales Executive', 2, TO_DATE('07/15/2017 13:32:13', 'MM/DD/YYYY HH24:MI:SS'), 'Y', '06')
INTO DIST_ROLE_MASTER_SETUP (ROLE_CODE, ROLE_NAME, CREATED_BY, CREATED_DATE, ACTIVE, COMPANY_CODE) VALUES (5, 'Distributor In-Charge', 2, TO_DATE('07/15/2017 13:32:13', 'MM/DD/YYYY HH24:MI:SS'), 'Y', '06')
INTO DIST_ROLE_MASTER_SETUP (ROLE_CODE, ROLE_NAME, CREATED_BY, CREATED_DATE, ACTIVE, COMPANY_CODE) VALUES (6, 'Deputy Regional Sales Manager', 2, TO_DATE('07/15/2017 13:32:13', 'MM/DD/YYYY HH24:MI:SS'), 'Y', '06')
SELECT 1 FROM DUAL