
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NeoERP.DocumentTemplate.Service.Models
{
    public class DocumentSetupModel
    {

    }


    public class CustomerSetupModel
    {
        public string CUSTOMER_CODE { get; set; }
        public string CUSTOMER_EDESC { get; set; }
        public string CUSTOMER_NDESC { get; set; }
        public string REGD_OFFICE_EADDRESS { get; set; }
        public string PRE_CUSTOMER_CODE { get; set; }
        public string MASTER_CUSTOMER_CODE { get; set; }
        public string GROUP_SKU_FLAG { get; set; }
        public DateTime? CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string MODIFY_BY { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public int CHILD_AUTOGENERATED { get; set; }
        public string CHILD_CUSTOMER_CODE { get; set; }
        public string CHILD_CUSTOMER_EDESC { get; set; }
        public string CHILD_CUSTOMER_ID { get; set; }
        public string CHILD_CUSTOMER_NDESC { get; set; }
        public string CHILD_GROUP_ID { get; set; }
        public string PERMANENT_ADDRESS { get; set; }
        public string TEMPORARY_ADDRESS { get; set; }
        public string TELEPHONE { get; set; }
        public string FAX { get; set; }
        public string COUNTRY { get; set; }
        public string ZONE { get; set; }
        public string REGION { get; set; }
        public string DISTRICT { get; set; }
        public string CITY { get; set; }
        public string TELEPHONE2 { get; set; }
        public string TELEPHONE3 { get; set; }
        public string PAN_VAT { get; set; }
        public string EXCISE { get; set; }
        public string EMAIL { get; set; }
        public string PARTY_TYPE { get; set; }
        public string ACCOUNTMAP { get; set; }
        public string AGENTNAME { get; set; }
        public string DEALING_PERSON { get; set; }
        public string PARTY_TYPE_EDESC { get; set; }
        public string ACC_EDESC { get; set; }
        public bool CASH_CUSTOMER { get; set; }
        public bool ACTIVE_CUSTOMER { get; set; }

    }
    public class MappedCustomerModel
    {

        public string PARTY_TYPE_CODE { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public List<CustSubList> CustSubList { get; set; }
    }

    public class CustSubList
    {
        public string CUSTOMER_CODE { get; set; }
        public string CUSTOMER_EDESC { get; set; }
        public string TPIN_VAT_NO { get; set; }
        public string REGD_OFFICE_EADDRESS { get; set; }

        public string SUB_CODE { get; set; }
    }


    public class AccountSetupModel
    {
        public string ACC_NATURE { get; set; }
        public string TRANSACTION_TYPE { get; set; }
        public string PREFIX_TEXT { get; set; }
        public string ACC_CODE { get; set; }
        public string ACC_EDESC { get; set; }
        public string ACC_NDESC { get; set; }
        // public string TRANSACTION_TYPE { get; set; }
        public string TPB_FLAG { get; set; }
        public string ACC_TYPE_FLAG { get; set; }
        public string MASTER_ACC_CODE { get; set; }
        public string PRE_ACC_CODE { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string SYN_ROWID { get; set; }
        public string DELTA_FLAG { get; set; }
        public string FREEZE_FLAG { get; set; }
        public decimal? CURRENT_BALANCE { get; set; }
        public decimal? LIMIT { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        //   public string ACC_NATURE { get; set; }
        public string BRANCH_CODE { get; set; }
        public decimal? SHARE_VALUE { get; set; }
        public string MODIFY_BY { get; set; }
        public string IND_VAT_FLAG { get; set; }
        public string BANK_ACCOUNT_NO { get; set; }
        public string PRINTING_FLAG { get; set; }
        public string ACC_SNAME { get; set; }
        public string TEL_NO { get; set; }
        public string IND_TDS_FLAG { get; set; }
        public string ACC_ID { get; set; }
        public string MOBILE_NO { get; set; }
        public string EMAIL_ID { get; set; }
        public string LINK_ID { get; set; }
        public string CONTACT_PERSON { get; set; }
        public string GROUP_START_CODE { get; set; }
        public string GROUP_END_CODE { get; set; }
        public string PARENT_ACC_CODE { get; set; }
        public string IND_MDF_FLAG { get; set; }


    }
    public class DealerModel
    {
        public string PARTY_TYPE_CODE { get; set; }
        public string PARTY_TYPE_EDESC { get; set; }
        public string PARTY_TYPE_NDESC { get; set; }
        public string REMARKS { get; set; }
        public string ACC_CODE { get; set; }
        public string SYN_ROWID { get; set; }
        public string TEL_NO { get; set; }
        public int? CREDIT_LIMIT { get; set; }
        public int? CREDIT_DAYS { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string DELTA_FLAG { get; set; }
        public string PARTY_TYPE_FLAG { get; set; }
        public int? PAN_NO { get; set; }
        public string TEL_NO2 { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public int LEVEL { get; set; }
        public string BRANCH_CODE { get; set; }
        public string ADDRESS { get; set; }
        public string MODIFY_BY { get; set; }
        public string OWNER_NAME { get; set; }
        public string LINK_BRANCH_CODE { get; set; }
        public int? AREA_CODE { get; set; }
        public string ZONE_CODE { get; set; }
        public int? BG_AMOUNT { get; set; }
        public string TERMS_CONDITIONS { get; set; }
        public string APPROVED_FLAG { get; set; }
        public string PRE_PARTY_CODE { get; set; }
        public string MASTER_PARTY_CODE { get; set; }
        public int? EXCEED_LIMIT_PERCENTAGE { get; set; }
        public int? TRADE_DISCOUNT { get; set; }
        public int? ANNUAL_BONUS { get; set; }
        public int? BG_PER_UNIT { get; set; }
        public int? CD_PER_UNIT { get; set; }
        public int? PDC_CHEQUE_AMT { get; set; }
        public int? SALES_TARGET { get; set; }
        public string GROUP_SKU_FLAG { get; set; }
        public string PARENT_DEALER_CODE { get; set; }
        //public string PARTY_TYPE_FLAG { get; set; }
    }
    public class BudgetCenterSetupModel
    {
        public string BUDGET_CODE { get; set; }
        public string BUDGET_EDESC { get; set; }
        public string BUDGET_NDESC { get; set; }
        public string GROUP_SKU_FLAG { get; set; }
        public string PRE_BUDGET_CODE { get; set; }
        public string REMARKS { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string SYN_ROWID { get; set; }
        public string FREEZE_FLAG { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public string ACC_CODE { get; set; }
        public string MODIFY_BY { get; set; }
        public string MASTER_BUDGET_CODE { get; set; }
        public string BUDGET_TYPE_FLAG { get; set; }
        public string PARENT_BUDGET_CODE { get; set; }
        public string ASSIGN_TO { get; set; }
        public string CASH_ACC_CODE { get; set; }

    }

    public class PartyTypeModel
    {
        public string PARTY_TYPE_CODE { get; set; }
        public string PARTY_TYPE_EDESC { get; set; }
        public string PARTY_TYPE_NDESC { get; set; }
        public string REMARKS { get; set; }
        public string ACC_CODE { get; set; }
        public string SYN_ROWID { get; set; }
        public string TEL_NO { get; set; }
        public int? CREDIT_LIMIT { get; set; }
        public int? CREDIT_DAYS { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string DELTA_FLAG { get; set; }
        public string PARTY_TYPE_FLAG { get; set; }
        public int? PAN_NO { get; set; }
        public string TEL_NO2 { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public int LEVEL { get; set; }
        public string BRANCH_CODE { get; set; }
        public string ADDRESS { get; set; }
        public string MODIFY_BY { get; set; }
        public string OWNER_NAME { get; set; }
        public string LINK_BRANCH_CODE { get; set; }
        public string TERMS_CONDITIONS { get; set; }
        public string APPROVED_FLAG { get; set; }
        public string PRE_PARTY_CODE { get; set; }
        public string MASTER_PARTY_CODE { get; set; }
        public string GROUP_SKU_FLAG { get; set; }
        public string PARENT_DEALER_CODE { get; set; }


    }


    public class CurrencymultiModel
    {
        public string CURRENCY_EDESC { get; set; }
        public string CURRENCY_CODE { get; set; }
        public string COUNTRY { get; set; }
        public string CURRENCY_SYMBOL { get; set; }

    }

    //form 
    public class FormcodeList
    {
        public string FORM_CODE { get; set; }
        public string FORM_EDESC { get; set; }
        public string REF_TABLE_NAME { get; set; }


    }
    public class PreferenceModel
    {
        public string BRANCH_CODE { get; set; }
        public string COMPANY_CODE { get; set; }
        public string BRANCH_EDESC { get; set; }
        public string COMPANY_EDESC { get; set; }
        public string PURCHASE_INV_FORM_CODE { get; set; }
        public string SALES_INV_FORM_CODE { get; set; }
        public int FREQUENT_NO { get; set; }
        public int ALERT_REFRESH_RATE { get; set; }
        public string FISCAL_YEAR { get; set; }
        public DateTime FY_START_DATE { get; set; }
        public DateTime FY_END_DATE { get; set; }
        public string SYSTEM_NAV_TITLE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string SYSTEM_NAV_SHORTKEY { get; set; }
        public string DEFINITION_TITLE { get; set; }
        public string DEFINITION_SHORTKEY { get; set; }
        public DateTime MODIFY_DATE { get; set; }
        public string MODIFY_BY { get; set; }
        public string SETUP_TITLE { get; set; }
        public string SETUP_SHORTKEY { get; set; }
        public string TRANSACTION_TITLE { get; set; }
        public string TRANSACTION_SHORTKEY { get; set; }
        public string REPORT_TITLE { get; set; }
        public string REPORT_SHORTKEY { get; set; }
        public string PREFERENCE_TITLE { get; set; }
        public string PREFERENCE_SHORTKEY { get; set; }
        public int DECIMAL_PLACE { get; set; }
        public string DEFAULT_CURRENCY_CODE { get; set; }
        public decimal EXCHANGE_RATE { get; set; }
        public int SECURED_BACK_DAYS { get; set; }
        public string CASH_ACC_CODE { get; set; }
        public string PURCHASE_EXP_FORM_CODE { get; set; }
        public string ORGANIZATION { get; set; }
        public string GL_FLAG { get; set; }
        public string SL_FLAG { get; set; }
        public string AUTO_LEDGER_FLAG { get; set; }
        public string AUTO_CUSTOMER_FLAG { get; set; }
        public string AUTO_SUPPLIER_FLAG { get; set; }
        public string AUTO_ITEM_FLAG { get; set; }
        public string START_BACKUP { get; set; }
        public string METHOD { get; set; }
        public string NEGATIVE_STOCK_FLAG { get; set; }
        public string REFERENCE_TRAN_FLAG { get; set; }
        public string SALES_RETURN_FORM_CODE { get; set; }
        public string PUR_RETURN_FORM_CODE { get; set; }
        public string SIM_FLAG { get; set; }
        public string BRANCH_SCMAP_FLAG { get; set; }
        public string SUB_NARRATION_FLAG { get; set; }
        public string STOCK_GENERIC_FLAG { get; set; }
        public string CUSTOMER_APPROVAL_FLAG { get; set; }
        public string RATE3_INFO_FLAG { get; set; }
        public string REFERENCE_EDIT_FLAG { get; set; }
        public string GB_FLAG { get; set; }
        public string MASTER_MODIFY { get; set; }
        public string BRANCH_BCMAP_FLAG { get; set; }
        public string PRINT_TYPE { get; set; }
        public string SUPPLIER_APPROVAL_FLAG { get; set; }
        public string SUBLEDGER_BILL_ADJUST_FLAG { get; set; }
        public string VERSION_CONTROL_FLAG { get; set; }
        public string FREEZE_PUR_EXP_OPTION { get; set; }
        public int PASS_EXPIRY_DAYS { get; set; }
        public string PRINT_DATE_FLAG { get; set; }
        public string TB_GENERIC_FLAG { get; set; }
        public DateTime FREEZE_ENTRY_DATE { get; set; }
        //
        public string COA_BUDGET_CONTROL_FLAG { get; set; }
        public string COA_BUDGET_INFO_FLAG { get; set; }
        public string COST_BUDGET_CONTROL_FLAG { get; set; }
        public string COST_BUDGET_INFO_FLAG { get; set; }
        public string USER_TARGET_CONTROL_FLAG { get; set; }
        public string TRANS_ALERT_CAPTURE_FLAG { get; set; }
        public string DEFAULT_BRANCH_CONSOLE { get; set; }
        public string DEFAULT_COGS_VALUE { get; set; }
        public string PARTY_ACTIVE_INFO_FLAG { get; set; }
        public string PUR_RATE_VERIANCE_FLAG { get; set; }
        public string PUR_RATE_PERCENT { get; set; }
        public string LEDGER_VAT_FLAG { get; set; }
        public string COST_CATEGORY_FLAG { get; set; }
        public string SUBLEDGER_ORDER_FLAG { get; set; }
        public string AUTO_GENERATE_LS_FLAG { get; set; }
        public string TB_SUB_LEDGER_LOAD { get; set; }
        public string RATE_SCHEDULE_TYPE { get; set; }
        public string IND_VOUCHER_VERIFY { get; set; }
        public string PRINT_DATE_TIME { get; set; }
        public string TABLE_NOT_UNPOST_FLAG { get; set; }
        public int LS_BACK_ACCESS_DAYS { get; set; }
        public string VAT_DR_CR_ENTRY { get; set; }
        public string PP_DETAIL_ENTRY { get; set; }
        public string DIVISION_FLAG { get; set; }
        public string DOCUMENT_HISTORY_FLAG { get; set; }
        public string BILL_QTY_FLAG { get; set; }
        public string ORDER_TAXABLE_RATE { get; set; }
        public string EXCHANGE_RATE_EDITABLE_FLAG { get; set; }
        public string VNO_AS_SESSION_ID_CONTROL { get; set; }
        public string DEALER_SYSTEM_FLAG { get; set; }
        public string CASH_BANK_NEGATIVE_FLAG { get; set; }
        public string SALES_CUPON_SCHEME_FLAG { get; set; }
        public string AFP_BUDGET_CONTROL_FLAG { get; set; }
        public string MASTER_FIELD_MANDATORY_FLAG { get; set; }
        public string PAN_VAT_CONTROL_FLAG { get; set; }
        public string SYNC_WITH_IRD { get; set; }
        public string CREDIT_CONTROL_FLAG { get; set; }
        public string CREDIT_CONTROL_AT { get; set; }
        public string FREIGHT_NEGATIVE_FLAG { get; set; }
        public string FREIGHT_RATE_FLAG { get; set; }
        public string CREDIT_CONTROL_AS { get; set; }
        public string TAXABLE_RATE_CALCULATE { get; set; }
        public string DEFAULT_DIVISION { get; set; }
        public string BUDGET_CONTROL_FLAG { get; set; }

        public string AUTO_ITEM_FLA { get; set; }

    }

    public class RejectableItem
    {
        public string ITEM_ID { get; set; }
        public string ITEM_CODE { get; set; }
        public string ITEM_NAME { get; set; }
        public string REMARKS { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public string CREATED_DATE { get; set; }
        public string MODIFY_BY { get; set; }
        public string MODIFY_DATE { get; set; }

    }


    public class BranchSetupModel
    {
        public string BRANCH_CODE { get; set; }
        public string BRANCH_EDESC { get; set; }
        public string BRANCH_NDESC { get; set; }
        public string ADDRESS { get; set; }
        public string TELEPHONE_NO { get; set; }
        public string EMAIL { get; set; }
        public string PRE_BRANCH_CODE { get; set; }
        public string GROUP_SKU_FLAG { get; set; }
        public string REMARKS { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime? CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string SYN_ROWID { get; set; }
        public string DELTA_FLAG { get; set; }
        public string ABBR_CODE { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public string MODIFY_BY { get; set; }
        public string MASTER_BRANCH_CODE { get; set; }
        public string PARENT_BRANCH_CODE { get; set; }

    }

    public class IssueTypeSetupModel
    {
        public string ISSUE_TYPE_CODE { get; set; }
        public string ISSUE_TYPE_EDESC { get; set; }
        public string ISSUE_TYPE_NDESC { get; set; }
        public string REMARKS { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public string CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string SYN_ROWID { get; set; }
        public string MODIFY_DATE { get; set; }
        public string MODIFY_BY { get; set; }
        public string ISSUE_TYPE_FLAG { get; set; }

    }

    public class MeasurementUnit
    {
        public string MU_CODE { get; set; }
        public string MU_EDESC { get; set; }
        public string MU_NDESC { get; set; }
        public string REMARKS { get; set; }

    }
    public class VehicleSetupModel
    {
        public string VEHICLE_CODE { get; set; }
        public string VEHICLE_TYPE { get; set; }
        public string VEHICLE_EDESC { get; set; }
        public string VEHICLE_ID { get; set; }
        public string OWNER_NAME { get; set; }
        public string OWNER_MOBILE_NO { get; set; }
        public string DRIVER_NAME { get; set; }
        public string DRIVER_LICENCE_NO { get; set; }
        public string DRIVER_MOBILE_NO { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime? CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string SYN_ROWID { get; set; }
        public string DELTA_FLAG { get; set; }
        public string GROUP_EDESC { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public string MODIFY_BY { get; set; }
        public string ACC_CODE { get; set; }
        public string VEHICLE_LABOUR_EDESC { get; set; }
        public string REMARKS { get; set; }
        public string ACC_FLAG { get; set; }
    }



    public class PrioritySeupModel
    {
        public string PRIORITY_CODE { get; set; }
        public string PRIORITY_EDESC { get; set; }
        public string PRIORITY_NDESC { get; set; }
        public string REMARKS { get; set; }
        public string MODIFY_BY { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime? CREATED_DATE { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
    }

    public class VehicleRegistrationModel
    {
        public string TRANSACTION_NO { get; set; }
        public string REFERENCE_NO { get; set; }
        public string REFERENCE_FORM_CODE { get; set; }
        public string VEHICLE_NAME { get; set; }
        public DateTime? TRANSACTION_DATE { get; set; }
        public string COMPANY_CODE { get; set; }
        public string BRANCH_CODE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string ACCESS_FLAG { get; set; }
        public string READ_FLAG { get; set; }
        public string REMARKS { get; set; }
        public string VEHICLE_OWNER_NAME { get; set; }
        public string VEHICLE_OWNER_NO { get; set; }
        public string DRIVER_NAME { get; set; }
        public string DRIVER_LICENCE_NO { get; set; }
        public string DRIVER_MOBILE_NO { get; set; }
        public string IN_TIME { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime? CREATED_DATE { get; set; }
        public string OUT_TIME { get; set; }
        public string SYN_ROWID { get; set; }
        public string LOAD_IN_TIME { get; set; }
        public string LOAD_OUT_TIME { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public string MODIFY_BY { get; set; }
        public string TOTAL_VEHICLE_HR { get; set; }
        public int? TEAR_WT { get; set; }
        public int? GROSS_WT { get; set; }
        public int? NET_WT { get; set; }
        public int? QUANTITY { get; set; }
        public string ACCESS_BY { get; set; }
        public DateTime? ACCESS_DATE { get; set; }
        public string DESTINATION { get; set; }
        public string BROKER_NAME { get; set; }
        public DateTime? VEHICLE_IN_DATE { get; set; }
        public DateTime? VEHICLE_OUT_DATE { get; set; }
        public string TRANSPORT_NAME { get; set; }
        public string WB_SLIP_NO { get; set; }
        public string TRANSPORTER_CODE { get; set; }
        public string time1 { get; set; }
        public string time2 { get; set; }
        public string time3 { get; set; }
        public string time4 { get; set; }
        public string MITI { get; set; }



    }

    public class LoadingSlipModal
    {
        public string LOADING_SLIP_NO { get; set; }
        public string TRANSACTION_NO { get; set; }
        public string SERIAL_NO { get; set; }
        public string REFERENCE_NO { get; set; }
        public string REFERENCE_FORM_CODE { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string ITEM_CODE { get; set; }
        public string MU_CODE { get; set; }
        public string QUANTITY { get; set; }
        public string UNIT_PRICE { get; set; }
        public string VEHICLE_NAME { get; set; }
        public DateTime VOUCHER_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime? CREATED_DATE { get; set; }
        public string COMPANY_CODE { get; set; }
        public string BRANCH_CODE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string ACCESS_FLAG { get; set; }
        public string READ_FLAG { get; set; }
        public string DRIVER_NAME { get; set; }
        public string DRIVER_MOBILE_NO { get; set; }
        public string IN_TIME { get; set; }
        public string OUT_TIME { get; set; }
        public string LOAD_IN_TIME { get; set; }
        public string LOAD_OUT_TIME { get; set; }
        public string ACCESS_BY { get; set; }
        public DateTime ACCESS_DATE { get; set; }
        public string DESTINATION { get; set; }
        public string BROKER_NAME { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public string SYN_ROWID { get; set; }
        public string DISPATCH_NO { get; set; }
        public DateTime VEHICLE_OUT_DATE { get; set; }
        public string MODIFY_BY { get; set; }
        public string TRANSPORT_NAME { get; set; }
        public string WB_SLIP_NO { get; set; }
        public string WB_WEIGHT { get; set; }
        public string TO_LOCATION { get; set; }
        public string PENDING_DISPATCH_QTY { get; set; }
        public string ORDER_QTY { get; set; }
        public string FROM_LOCATION { get; set; }
        public string WB_TIME { get; set; }

    }

    public class LoadingSlipModalForPrint
    {
        public int LOADING_SLIP_NO { get; set; }
        public string TRANSACTION_NO { get; set; }
        public int SERIAL_NO { get; set; }
        public string REFERENCE_NO { get; set; }
        public string REFERENCE_FORM_CODE { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string CUSTOMER_EDESC { get; set; }
        public string ITEM_CODE { get; set; }
        public string ITEM_EDESC { get; set; }
        public string MU_CODE { get; set; }
        public int QUANTITY { get; set; }
        public int UNIT_PRICE { get; set; }
        public string VEHICLE_NAME { get; set; }
        public DateTime VOUCHER_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime? CREATED_DATE { get; set; }
        public string COMPANY_CODE { get; set; }
        public string BRANCH_CODE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string ACCESS_FLAG { get; set; }
        public string READ_FLAG { get; set; }
        public string DRIVER_NAME { get; set; }
        public string DRIVER_MOBILE_NO { get; set; }
        public string DRIVER_LICENCE_NO { get; set; }
        public string IN_TIME { get; set; }
        public string OUT_TIME { get; set; }
        public string LOAD_IN_TIME { get; set; }
        public string LOAD_OUT_TIME { get; set; }
        public string ACCESS_BY { get; set; }
        public DateTime ACCESS_DATE { get; set; }
        public string DESTINATION { get; set; }
        public string BROKER_NAME { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public string SYN_ROWID { get; set; }
        public string DISPATCH_NO { get; set; }
        public DateTime VEHICLE_OUT_DATE { get; set; }
        public string MODIFY_BY { get; set; }
        public string TRANSPORT_NAME { get; set; }
        public string WB_SLIP_NO { get; set; }
        public string WB_WEIGHT { get; set; }
        public string TO_LOCATION { get; set; }
        public string PENDING_DISPATCH_QTY { get; set; }
        public string ORDER_QTY { get; set; }
        public string FROM_LOCATION { get; set; }
        public string WB_TIME { get; set; }

    }

    public class CompanySetupModel
    {
        public string COMPANY_CODE { get; set; }
        public string COMPANY_EDESC { get; set; }
        public string COMPANY_NDESC { get; set; }
        public string ADDRESS { get; set; }
        public string TELEPHONE { get; set; }
        public string EMAIL { get; set; }
        public string FAX { get; set; }
        public string WEB { get; set; }
        public string REMARKS { get; set; }
        public DateTime? VALID_DATE { get; set; }
        public string TPIN_VAT_NO { get; set; }
        public string SMTP_HOST { get; set; }
        public string FOOTER_LOGO_FILE_NAME { get; set; }

        public string CREATED_BY { get; set; }
        public DateTime? CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string SYN_ROWID { get; set; }
        public string CONSOLIDATE_FLAG { get; set; }
        public string ABBR_CODE { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public string MODIFY_BY { get; set; }
        public string REGISTRATION_NO { get; set; }
        public string LOGO_FILE_NAME { get; set; }
        public string PRE_COMPANY_CODE { get; set; }

    }





    public class DivisionSetupModel
    {
        public string DIVISION_CODE { get; set; }
        public string DIVISION_EDESC { get; set; }

        public string ADDRESS { get; set; }
        public string TELEPHONE_NO { get; set; }
        public string EMAIL { get; set; }
        public string PRE_DIVISION_CODE { get; set; }
        public string GROUP_SKU_FLAG { get; set; }
        public string REMARKS { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime? CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string SYN_ROWID { get; set; }

        public string ABBR_CODE { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public string MODIFY_BY { get; set; }
        public string MASTER_DIVISION_CODE { get; set; }
        public string PARENT_DIVISION_CODE { get; set; }

    }

    public class RegionalSetupModel
    {
        public string REGION_CODE { get; set; }
        public string REGION_EDESC { get; set; }
        public string REGION_NDESC { get; set; }
        public string REMARKS { get; set; }
        public string PRE_REGION_CODE { get; set; }
        public string GROUP_SKU_FLAG { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime? CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string COMPANY_CODE { get; set; }
        public string SYN_ROWID { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public string MODIFY_BY { get; set; }
        public string PARENT_REGION_CODE { get; set; }
    }
    public class LocationSetupModel
    {
        public string LOCATION_CODE { get; set; }
        public string LOCATION_EDESC { get; set; }
        public string LOCATION_NDESC { get; set; }
        public string PRE_LOCATION_CODE { get; set; }
        public string ADDRESS { get; set; }
        public string AUTH_CONTACT_PERSON { get; set; }
        public string TELEPHONE_MOBILE_NO { get; set; }
        public string EMAIL { get; set; }
        public string FAX { get; set; }
        public string LOCATION_TYPE_CODE { get; set; }
        public string GROUP_SKU_FLAG { get; set; }
        public string REMARKS { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime? CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string SYN_ROWID { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public string MODIFY_BY { get; set; }
        public string BRANCH_CODE { get; set; }
        public string BRANCH_EDESC { get; set; }
        public decimal? STORAGE_CAPACITY { get; set; }
        public string MU_CODE { get; set; }
        public string LOCATION_ID { get; set; }
        public string PARENT_LOCATION_CODE { get; set; }
    }

    public class ResourceSetupModel
    {
        public string RESOURCE_CODE { get; set; }
        public string RESOURCE_EDESC { get; set; }
        public string RESOURCE_NDESC { get; set; }
        public string RESOURCE_FLAG { get; set; }
        public string GROUP_SKU_FLAG { get; set; }
        public string PRE_RESOURCE_CODE { get; set; }
        public string REMARKS { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime? CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string SYN_ROWID { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public string RESOURCE_TYPE { get; set; }
        public string MODIFY_BY { get; set; }
        public string PARENT_RESOURCE_CODE { get; set; }
    }

    public class ProcessSetupModel
    {
        public string PRE_PROCESS_CODE { get; set; }
        public string INDEX_ITEM_CODE { get; set; }
        public decimal? INDEX_CAPACITY { get; set; }
        public string INDEX_MU_CODE { get; set; }
        public string REMARKS { get; set; }
        public string LOCATION_CODE { get; set; }
        public string LOCATION_EDESC { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime? CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string INDEX_PERIOD_CODE { get; set; }
        public decimal? INDEX_TIME_REQUIRED { get; set; }
        public string INDEX_TIME_MU_CODE { get; set; }
        public string INDEX_TIME_PERIOD_CODE { get; set; }
        public string INPUT_INDEX_ITEM_CODE { get; set; }
        public decimal? PRIORITY_ORDER_NO { get; set; }
        public string SYN_ROWID { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public string MODIFY_BY { get; set; }
        public string PROCESS_CODE { get; set; }
        public string PROCESS_EDESC { get; set; }
        public string PROCESS_NDESC { get; set; }
        public string PROCESS_TYPE_CODE { get; set; }
        public string PROCESS_FLAG { get; set; }
        public string PARENT_PROCESS_CODE { get; set; }
    }
    public class ItemSetupModalSet
    {
        //public ItemSetupModalSet()
        //{
        //    this.model = new ItemSetupModel();
        //}
        public ItemSetupModel model { get; set; }

    }

    public class ItemChargesModel
    {
        public string SERIAL_NO { get; set; }
        public string ITEM_CODE { get; set; }
        public string FORM_CODE { get; set; }
        public string CHARGE_CODE { get; set; }
        public string CHARGE_TYPE { get; set; }
        public string VALUE_QUANTITY_BASED { get; set; }
        public string VALUE_PERCENT_FLAG { get; set; }
        public decimal VALUE_PERCENT_AMOUNT { get; set; }
        public string CHARGE_INDEX_UNIT { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime? CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string ACC_CODE { get; set; }
        public string SUB_CODE { get; set; }
        public string IMPACT_ON { get; set; }
        public string APPLY_QUANTITY { get; set; }
        public string SYN_ROWID { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public string MODIFY_BY { get; set; }
        public string CHARGE_ACTIVE_FLAG { get; set; }

    }

    public class ItemSetupIntegrationModel
    {
        public string ACC_CODE { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime? CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string FORM_CODE { get; set; }
        public string INSERT_FLAG { get; set; }
        public string ITEM_CODE { get; set; }
        public string SYN_ROWID { get; set; }
    }
    public class ItemMultiMuCodeModel
    {
        public string ITEM_CODE { get; set; }
        public string MU_CODE { get; set; }
        public decimal? CONVERSION_FACTOR { get; set; }
        public decimal? FRACTION { get; set; }
        public string REMARKS { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime? CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public decimal? SERIAL_NO { get; set; }
        public string SYN_ROWID { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public string MODIFY_BY { get; set; }
    }
    public class ItemSetupModel
    {
        public ItemSetupSpecModel specModel { get; set; }
        public List<ItemSetupIntegrationModel> assoModel { get; set; }
        public List<ItemMultiMuCodeModel> multiMu { get; set; }
        public List<ItemChargesModel> charges { get; set; }
        public string ITEM_CODE { get; set; }
        public string ITEM_EDESC { get; set; }
        public string ITEM_NDESC { get; set; }
        public string CATEGORY_CODE { get; set; }
        public string DIMENSION { get; set; }
        public string INDEX_MU_CODE { get; set; }
        public decimal? FRACTION_VALUE { get; set; }
        public string MASTER_ITEM_CODE { get; set; }
        public string PRE_ITEM_CODE { get; set; }
        public string IMAGE_FILE_NAME { get; set; }
        public decimal? SHELF_LIFE_DAYS { get; set; }
        public decimal? MAX_USAGE { get; set; }
        public decimal? MIN_USAGE { get; set; }
        public decimal? NORMAL_USAGE { get; set; }
        public decimal? MAX_LEVEL { get; set; }
        public decimal? MIN_LEVEL { get; set; }
        public decimal? PREFERRED_LEVEL { get; set; }
        public decimal? REORDER_LEVEL { get; set; }
        public decimal? DANGER_LEVEL { get; set; }
        public decimal? ECO_ORDER_QUANTITY { get; set; }
        public string PREFERRED_SUPPLIER_CODE { get; set; }
        public decimal? LEAD_TIME { get; set; }
        public string COSTING_METHOD_FLAG { get; set; }
        public string GROUP_SKU_FLAG { get; set; }
        public string HS_CODE { get; set; }
        public string LINK_SUB_CODE { get; set; }
        public string REMARKS { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public decimal? DEFAULT_WIP_STOCK { get; set; }
        public string SERVICE_ITEM_FLAG { get; set; }
        public decimal? PURCHASE_PRICE { get; set; }
        public decimal? SALES_PRICE { get; set; }
        public string REMARKS2ND { get; set; }
        public decimal? CURRENT_STOCK { get; set; }
        public string SYN_ROWID { get; set; }
        public string DELTA_FLAG { get; set; }
        public string BATCH_FLAG { get; set; }
        public string MULTI_MU_CODE { get; set; }
        public string SERIAL_FLAG { get; set; }
        public string BATCH_SERIAL_FLAG { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public string VALUATION_FLAG { get; set; }
        public string BRANCH_CODE { get; set; }
        public string PRODUCT_CODE { get; set; }
        public decimal? AVG_RATE { get; set; }
        public decimal? MIN_VALUE { get; set; }
        public decimal? MAX_VALUE { get; set; }
        public string MODIFY_BY { get; set; }
        public decimal? REEM_WEIGHT_KG { get; set; }
        public string SERIAL_PREFIX_TEXT { get; set; }
        public decimal? SERIAL_PREFIX_LENGTH { get; set; }
        public string PARENT_ITEM_CODE { get; set; }
        public string MU_EDESC { get; set; }
        public string CATEGORY_EDESC { get; set; }
        public string ACC_CODE { get; set; }
        public string FORM_CODE { get; set; }


    }

    public class ItemSetupSpecModel
    {
        public string ITEM_CODE { get; set; }
        public string PART_NUMBER { get; set; }
        public string BRAND_NAME { get; set; }
        public string ITEM_SPECIFICATION { get; set; }
        public string ITEM_APPLY_ON { get; set; }
        public string INTERFACE { get; set; }
        public string TYPE { get; set; }
        public string LAMINATION { get; set; }
        public string ITEM_SIZE { get; set; }
        public string THICKNESS { get; set; }
        public string COLOR { get; set; }
        public string GRADE { get; set; }
        public string REMARKS { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime? CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public string SYN_ROWID { get; set; }
        public string MODIFY_BY { get; set; }
        public string GSM { get; set; }
        public string SIZE_LENGHT { get; set; }
        public string SIZE_WIDTH { get; set; }
        public string SPEC_COMPULSORY_FLAG { get; set; }
    }
    public class SuplierSetupModel
    {
        public List<SuplierContactmodel> suplierContactmodelList { get; set; }
        public SuplierContactmodel suplierContactmodel { get; set; }
        public List<SupplierSisterConcernmodel> supplierSisterConcernmodelList { get; set; }
        public SupplierSisterConcernmodel supplierSisterConcernmodel { get; set; }
        public List<SupplierBudgetCenterInfo> supplierBudgetCenterInfoList { get; set; }
        public SupplierBudgetCenterInfo supplierBudgetCenterInfo { get; set; }
        public List<SupplierOpeningBalanceModel> supplierOpeningBalanceModelList { get; set; }
        public SupplierOpeningBalanceModel supplierOpeningBalanceModel { get; set; }
        public string SUPPLIER_CODE { get; set; }
        public string PARENT_SUPPLIER_CODE { get; set; }
        public string SUPPLIER_EDESC { get; set; }
        public string SUPPLIER_NDESC { get; set; }
        public string REGD_OFFICE_EADDRESS { get; set; }
        public string REGD_OFFICE_NADDRESS { get; set; }
        public string TEL_MOBILE_NO1 { get; set; }
        public string TEL_MOBILE_NO2 { get; set; }
        public string FAX_NO { get; set; }
        public string EMAIL { get; set; }
        public string PARTY_TYPE_CODE { get; set; }
        public string PARTY_TYPE_EDESC { get; set; }
        public string LINK_SUB_CODE { get; set; }
        public string REMARKS { get; set; }
        public string ACTIVE_FLAG { get; set; }
        public string GROUP_SKU_FLAG { get; set; }
        public string MASTER_SUPPLIER_CODE { get; set; }
        public string PRE_SUPPLIER_CODE { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public int? CREDIT_DAYS { get; set; }
        public string CREDIT_ACTION_FLAG { get; set; }
        public string ACC_CODE { get; set; }
        public string PR_CODE { get; set; }
        public string TPIN_VAT_NO { get; set; }
        public string SYN_ROWID { get; set; }
        public string DELTA_FLAG { get; set; }
        public int? CREDIT_LIMIT { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public string BRANCH_CODE { get; set; }
        public string MODIFY_BY { get; set; }
        public DateTime? OPENING_DATE { get; set; }
        public string M_DAYS { get; set; }
        public string APPROVED_FLAG { get; set; }
        public string SUBSTITUTE_NAME { get; set; }
        public DateTime? MATURITY_DATE { get; set; }
        public string IMAGE_FILE_NAME { get; set; }
        public int? INTEREST_RATE { get; set; }
        public string CASH_SUPPLIER_FLAG { get; set; }
        public string SUPPLIER_ID { get; set; }
        public int? GROUP_START_NO { get; set; }
        public string PREFIX_TEXT { get; set; }
        public string EXCISE_NO { get; set; }
        public string SHORTCUT { get; set; }
        public string TIN { get; set; }

    }

    public class CountryModels
    {
        public string COUNTRY_CODE { get; set; }
        public string COUNTRY_EDESC { get; set; }
    }
    public class ZoneModels
    {
        public string ZONE_CODE { get; set; }
        public string ZONE_EDESC { get; set; }
    }
    public class RegionModels
    {
        public string REGION_CODE { get; set; }
        public string REGION_EDESC { get; set; }
    }
    public class DistrictModels
    {
        public string DISTRICT_CODE { get; set; }
        public string DISTRICT_EDESC { get; set; }
    }
    public class CityModels
    {
        public string CITY_CODE { get; set; }
        public string CITY_EDESC { get; set; }
        public string CITY_NDESC { get; set; }
        public string CITY_VDC_FLAG { get; set; }
        public string DISTRICT_CODE { get; set; }
        public string REMARKS { get; set; }
    }

    public class CityModelForSave
    {
        public string CITY_CODE { get; set; }
        public string CITY_EDESC { get; set; }
        public string CITY_NDESC { get; set; }
        public string CITY_VDC_FLAG { get; set; }
        public string DISTRICT_CODE { get; set; }
        public string REMARKS { get; set; }
        public string MODIFY_DATE { get; set; }
        public string MODIFY_BY { get; set; }
        public string DELETED_FLAG { get; set; }

    }
    public class PartyTypeModels
    {
        public string PARTY_TYPE_CODE { get; set; }
        public string PARTY_TYPE_EDESC { get; set; }
        public string ACC_CODE { get; set; }
    }
    public class AccTypeModels
    {
        public string ACC_CODE { get; set; }
        public string ACC_EDESC { get; set; }
    }
    public class SuplierSetupModalSet
    {

        public SuplierSetupModel suplierSetupModel { get; set; }


    }
    public class SuplierContactmodel
    {
        public string SUPPLIER_CODE { get; set; }
        public string OWNER_NAME { get; set; }
        public string DESIGNATION { get; set; }
        public string CONTACT_PERSON { get; set; }
        public string ADDRESS { get; set; }
        public string TEL_MOBILE_NO { get; set; }
        public string FAX_NO { get; set; }
        public string EMAIL { get; set; }
        public string IMAGE_FILE_NAME { get; set; }
        public string REMARKS { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string SYN_ROWID { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public string MODIFY_BY { get; set; }
    }
    public class SupplierSisterConcernmodel
    {
        public string SUPPLIER_CODE { get; set; }
        public string SISTER_CONCERN_EDESC { get; set; }
        public string SISTER_CONCERN_NDESC { get; set; }
        public string REMARKS { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string SYN_ROWID { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public string MODIFY_BY { get; set; }
    }
    public class SupplierBudgetCenterInfo
    {
        public string SUPPLIER_CODE { get; set; }
        public string BUDGET_CODE { get; set; }
        public string REMARKS { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string SYN_ROWID { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public string MODIFY_BY { get; set; }
    }
    public class SupplierOpeningBalanceModel
    {
        public string SUPPLIER_CODE { get; set; }
        public string REFERENCE_NO { get; set; }
        public DateTime? INVOICE_DATE { get; set; }
        public decimal BALANCE_AMOUNT { get; set; }
        public string REMARKS { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string CURRENCY_CODE { get; set; }
        public int? EXCHANGE_RATE { get; set; }
        public DateTime? DUE_DATE { get; set; }
        public string TRANSACTION_TYPE { get; set; }
        public string SYN_ROWID { get; set; }
        public string BRANCH_CODE { get; set; }
        public string ACC_CODE { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public string MODIFY_BY { get; set; }
        public string DIVISION_CODE { get; set; }
    }
    public class QuickSetupModel
    {
        public string PARENT_CODE { get; set; }
        public string ENG_NAME { get; set; }
        public string NEP_NAME { get; set; }
        public string REMARKS { get; set; }
        public string FLAG { get; set; }
        public string MASTER_CODE { get; set; }
        public string REGD_OFFICE_EADDRESS { get; set; }
        public string TEL_MOBILE_NO1 { get; set; }
        public string EMAIL { get; set; }
        public string CATEGORY_CODE { get; set; }
        public string INDEX_MU_CODE { get; set; }
    }
    public class CurrencySetupModel
    {
        public string CURRENCY_SYMBOL { get; set; }
        public string CURRENCY_CODE { get; set; }
        public string CURRENCY_EDESC { get; set; }
        public string CURRENCY_NDESC { get; set; }
        public string COUNTRY { get; set; }
        public string REMARKS { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime? CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string SYN_ROWID { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public string MODIFY_BY { get; set; }
    }
    public class CategorySetupModel
    {
        public string CATEGORY_CODE { get; set; }
        public string CATEGORY_EDESC { get; set; }
        public string CATEGORY_NDESC { get; set; }
        public string REMARKS { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime? CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string SYN_ROWID { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public string MODIFY_BY { get; set; }
        public string CATEGORY_TYPE { get; set; }
        public string PREFIX_TEXT { get; set; }
    }

    public class RoutineInputModel
    {
        public string PROCESS_CODE { get; set; }
        public string ITEM_CODE { get; set; }
        public int QUANTITY { get; set; }
        public string MU_CODE { get; set; }
        public string REMARKS { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime? CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string SYN_ROWID { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public string MODIFY_BY { get; set; }
        public string CATEGORY_TYPE { get; set; }

    }

    public class RoutineOutputModel
    {
        public string PROCESS_CODE { get; set; }
        public string ITEM_CODE { get; set; }
        public int QUANTITY { get; set; }
        public string MU_CODE { get; set; }
        public int OUTPUT_PERCENT { get; set; }
        public string VALUATION_FLAG { get; set; }
        public string REMARKS { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime? CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string SYN_ROWID { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public string MODIFY_BY { get; set; }
        public string CATEGORY_TYPE { get; set; }
    }


    public class TDSTypeModel
    {
        public string TDS_CODE { get; set; }
        public string TDS_EDESC { get; set; }
        public string TDS_TYPE_CODE { get; set; }
        public string REMARKS { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime? CREATED_DATE { get; set; }
        public string DELETED_FLAG { get; set; }
        public string SYN_ROWID { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public string MODIFY_BY { get; set; }

    }
}
